### ISSUE TITLE
Auto update after boot dont work

### ISSUE THREAD

**Issue by prescott66** [manjaro/pamac#10]
After running system (Antergos 64bit) pamac dont update repos automatically. i must do it manually.

**Comment by philmmanjaro** [comment]
Seems to be related to pamac-tray and pamac-refresh if you have no working internet connection, example proxy. Have to test this more at home.

**Comment by guinux** [comment]
Why this issue is related with #5 ? Is pamac not removing the lock file in some situations when checking update ?

**Comment by prescott66** [comment]
I have wifi connection without proxy...sometimes autorefresh works...maybe pamac should wait longer for connection get established

**Comment by guinux** [comment]
I created "/etc/NetworkManager/dispatcher.d/99_update_pamac_tray" script to check updates when a connection is up but I just found that "systemctl enable NetworkManager-dispatcher" need to be runned first. Can you check if this file exists, run systemctl command and try again ?

**Comment by prescott66** [comment]
after next reboot, was not refreshed repos again. so problem persists.only db vas not locked, so i can install updates manually without problems.
