### ISSUE TITLE
[Feature Request] Warn users of breaking changes on update

### ISSUE THREAD

**Issue by tgharib** [manjaro/pamac#100]
So after reading this [post](https://old.forum.manjaro.org/index.php?topic=31356.msg257698#msg257698), it occurred to me that it might be a good idea to warn users of breaking changes when hitting "apply" on the software updater. I don't check the website for every update and it's one of the reasons why I use Manjaro. If you do implement this feature, it might be a good idea to add the update changelog (that gets posted on the main website) right below it. If this is a duplicate of #85, then feel free to close this issue.

**Comment by guinux** [comment]
#49
