### ISSUE TITLE
Process dialog window

### ISSUE THREAD

**Issue by prescott66** [manjaro/pamac#102]
When updating is done, process dialog window(with displayed terminal) stays opened. User must close it manually. I  think it is a bug, because before it was closed automatically and it is annoying.

**Comment by guinux** [comment]
I pamac doesn't auto-close the progress window if details (the terminal) were made visible by the user or because there is some imortant output.

**Comment by philmmanjaro** [comment]
This is wanted and [was requested](https://github.com/manjaro/pamac/issues/96). However we can think about an settings option to override it so the old behaviour might be possible to set back. However by default **pamac** should stay open if there are changes in details list.
