### ISSUE TITLE
 pamac-manager drops pending requests after network interruption

### ISSUE THREAD

**Issue by Boruch-Baum** [manjaro/pamac#103]
1] Select some package(s) to install
2] Ask pamac-manager to begin the installation
3] Simulate a network interruption (eg. disconnect eth0/wlan0)
4] pamac-manager correctly reports a download error
5] pamac-manager returns to its initial screen, but in its initial state, ie. it doesn't 'remember' what was pending in order to allow the user to re-try.

**Comment by guinux** [comment]
Yes downloading comes with the commit transaction step and on error, pamac can't know if databases were modified or not so it cleans the pending operation by security. You just have to select again the packages and re-try.
