### ISSUE TITLE
Update Manager :: Hangs with spinning circle cursor

### ISSUE THREAD

**Issue by lots0logs** [manjaro/pamac#104]
![2016-02-29_10-51-24-pm](https://cloud.githubusercontent.com/assets/4675662/13418037/fc677d3a-df36-11e5-9f1d-74677a4cf19f.png)

~~Running from the terminal I see this error:~~
```
File '/etc/pacman-mirrors.conf' doesn't exist.
No such file or directory
```

~~The file mentioned is not one which is standard for official pacman from Arch. I am assuming it is specific to Manjaro?~~

***Edit:*** Actually, I don't think that is related to this issue. I don't have time to look further into it at the moment but I will try to look at it tomorrow if you guys havent done it already. Cheers!

**Comment by philmmanjaro** [comment]
Yes, this file is specific to Manjaro.

**Comment by guinux** [comment]
What version of pamac do you use? This error should not occurs anymore.

**Comment by pointhi** [comment]
I have on Antergos the same problem with the package: ```pamac-3.2rc1-2-x86_64.pkg.tar.xz``` (which seems to be an Antergos and not an Arch specific package)

**Comment by philmmanjaro** [comment]
Yep, this issue was already reported by me. That's why we removed that package again from our repositories. However this is now [fixed](https://github.com/manjaro/packages-extra/commit/babaefb48d7d95bebe52747b168b214ce93a0c1e).
