### ISSUE TITLE
[Feature request] Multiple AUR helpers

### ISSUE THREAD

**Issue by Yoshi2889** [manjaro/pamac#105]
Pamac explicitly requires yaourt for AUR operations right now, and the patches to make it work with pacaur are rather simple (essentially, you'd just change all instances of 'yaourt' to 'pacaur', as per https://github.com/Yoshi2889/pamac/commit/157a298a8cac38bcbf63b123c7c3af68d51579c0 )

My suggestion: Add a setting to the preferences dialog that allows you to swap AUR helpers.

**Comment by guinux** [comment]
#84
