### ISSUE TITLE
Progress dialog stuck

### ISSUE THREAD

**Issue by blade1201** [manjaro/pamac#107]
Sometimes progress dialog stuck when I update manjaro. It simply stop displaying progress of downloading updates. The same thing is with checking for new updates. After synchronising extra repository stuck for some time before displaying community repo. Pamac version is 3.2.0

**Comment by guinux** [comment]
Now Pamac has a longer timeout before stopping a too slow download. It's simply waiting.

**Comment by philmmanjaro** [comment]
Can we add a settings option to tweak the timeout?

**Comment by blade1201** [comment]
This is the best option because (in my opinion) now is too long.

**Comment by guinux** [comment]
Yes but we can't tweak a slow connection with a server.
@blade1201 : you should try to refresh your mirrorlist

**Comment by blade1201** [comment]
I already tried but in terminal I always have a good connection. I think that this is related with something else. Today I have a ~140MB big updates. Pamac stuck at ~41MB and then after 10-15 sec jump to ~90MB so I think that it downloaded updates in background but simply didn^t display that.
