### ISSUE TITLE
freeze when opening details during db-update

### ISSUE THREAD

**Issue by oberon2007** [manjaro/pamac#108]
There have been two reports of this issue on the forum:
https://forum.manjaro.org/index.php?topic=32002.msg262880#msg262880
Apparently when you click on 'details' while databases are updating, pamac freezes.

**Comment by oberon2007** [comment]
I can reproduce this.

**Comment by oberon2007** [comment]
Thank you. Working as it should again with **3.2.1** :)

**Comment by kouros17** [comment]
I still have the problem with pamac 3.2.1
