### ISSUE TITLE
Issue with number of downloaded data

### ISSUE THREAD

**Issue by prescott66** [manjaro/pamac#11]
As you can see on screenshot, amount of downloaded data is bigger than total downloadable data.

![snimka obrazovky z 2014-12-17 15 55 29](https://cloud.githubusercontent.com/assets/735265/5472939/be61d41c-8605-11e4-81bb-2f5ab15051cc.png)

**Comment by manjaro** [comment]
Is this issue still be present within pamac 2.1?
