### ISSUE TITLE
Unintuitive scrolling

### ISSUE THREAD

**Issue by mirh** [manjaro/pamac#110]
![istantanea_2016-03-21_17-15-16](https://cloud.githubusercontent.com/assets/9366725/13925495/c27c1d08-ef88-11e5-811d-8cf61574b87f.png)

EDIT: ok, I just figured out there is indeed a scrolling bar on the bottom of the window, which only appears if you move the mouse over. 
Though.. it's all but immediate to notice it's there. 

Or even better why not having text fitting the panel?

**Comment by philmmanjaro** [comment]
Try a different theme

**Comment by mirh** [comment]
No difference.

**Comment by philmmanjaro** [comment]
I think with **v4.1** we can close this one?

**Comment by mirh** [comment]
Agreed.
