### ISSUE TITLE
Downloading from HTTPS mirrors always returns "Failed to create SSL context"

### ISSUE THREAD

**Issue by Rainmaker52** [manjaro/pamac#112]
When using pamac-updater, downloading packages from HTTPS enabled mirrors always returns "Failed to create SSL context".

Using yaourt from the command line works fine.

I've tried several different mirrors. The SSL certificate of the site is valid, within validity range and signed by public CA.

**Comment by guinux** [comment]
Can you give me the mirror url, I will see this.

**Comment by philmmanjaro** [comment]
Normally we just use the HTTP URLs. Ssl URLs we have to check.

**Comment by Rainmaker52** [comment]
I use 
https://mirror.i3d.net/pub/archlinux/$repo/os/$arch

Also tried:
Server = https://arch.32g.eu/$repo/os/$arch
Server = https://mirror.compojoom.com/archlinux/$repo/os/$arch
Server = https://archlinux.cyborg-connect.de/$repo/os/$arch
Server = https://mirror.f4st.host/archlinux/$repo/os/$arch

And some others :)

I use SSL mirrors because my laptop is quite often behind a guest wifi network. Login pages and stuff, corrupt the pacman database.

That bug was reported as https://bugs.archlinux.org/task/46107?opened=21341&type%5B0%5D=&sev%5B0%5D=&due%5B0%5D=&cat%5B0%5D=&status%5B0%5D=open&percent%5B0%5D=&reported%5B0%5D= , in case anyone is interested.

**Comment by guinux** [comment]
As you are using Archlinux, it's maybe because openssl was updated, can you try to rebuild pamac ?

**Comment by Rainmaker52** [comment]
For a reason beyond my comprehension, rebuilding actually worked. 

I don't really understand why I should recompile when a shared library gets updated. Before rebuild, the program already seemed to be correctly linked :
~  ldd `which pamac-updater` | grep ssl
	libssl.so.1.0.0 => /usr/lib/libssl.so.1.0.0 (0x00007f69459d2000)

But, it worked. Thanks.

**Comment by Rainmaker52** [comment]
This may require an extra look.
Without changing or upgrading anything, the error is back (?).

Exact error is:
Error: failed retrieving file 'multilib.db' from ftp.fau.de : SSL: couldn't create a context: error:140A90F1:lib(20):func(169):reason(241)

Could someone try to reproduce?

**Comment by Strit** [comment]
I also have a similar error when using my own repo, which is on a https site.
I believe mine says something about cURL too.
Updating with pacman directly is no problem.

Also it only happens with the updater, not the software installer.

**Comment by seilaeu** [comment]
I had this issue in Arch Linux and the solution for me it was the update of my mirrorlist with command 'sudo reflector --verbose -p https -f 30 -l 30 -n 15 --sort rate --save /etc/pacman.d/mirrorlist'.

**Comment by ringo32** [comment]
like netcologne of manjaro repo also have a SSL part

**Comment by rnfll** [comment]
can confirm, that this error is still exists (atleast in pamac 4.0-1)

Im on manjaro, uses self-modified mirrorlist (actually, some of manjaro mirrors can in https). 
Tried to update with pamac today - got packages list without problems, but, on upgrade, this error happened: 
> SSL: couldn't create a context: error:140A90F1:lib(20):func(169):reason(241)

Tru pacman, everything went fine

**Comment by guinux** [comment]
I tried to fix SSL support in my last commit, please try and report.

**Comment by rasisin** [comment]
I'm getting the same error messages when doing normal updates of Manjaro. I work outside the IT field so my system has a default Manjaro setup. The update seems to happen successfully, but I think the problem slows down the update--the updater (pacman?) looks like it's searching through a long list of mirrors for each update.

**Comment by philmmanjaro** [comment]
Did you test the **pamac-dev 4.1.1-2** package yet, which includes that fix. Should be now available on all branches.

**Comment by rasisin** [comment]
Thank you! I installed the package, and now the error messages are gone.
