### ISSUE TITLE
Build warnings

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/pamac#115]
Warnings we should work on:

```
pamac_config.vala:128.3-128.19: warning: method `Pamac.Config.write' never used
		public void write (HashTable<string,Variant> new_conf) {
		^^^^^^^^^^^^^^^^^
libsoup-2.4.vapi:1134.3-1134.12: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
```

... depending if they are caused by pamac.

**Comment by guinux** [comment]
Nothing to  worry about,  "Pamac.Config.write never used" it's just a function which is not used in some binaries but needed in other ones, others are just deprecated syntax in libsoup vala bindings, it's only related to libsoup.
