### ISSUE TITLE
No highlight bar on dropdown menu of tray icon when running Vertex

### ISSUE THREAD

**Issue by aguador** [manjaro/pamac#117]
With the Vertex theme, highlight bars appear for the drop-down menus for icons such as Tomboy notes and Pidgin, but not pamac. This on a system running Manjaro E20 with stalone tray and tested with Vertex-Dark (only) after update to GTK3 3.20. The bar appeared with other themes running under GTK3 3.18. Given that this issue affects pamac only under 3.20, I assume that it is a pamac issue rather than a Vertex issue.

**Comment by philmmanjaro** [comment]
please check **pamac-dev** package once and report if you still have the same issue.

**Comment by aguador** [comment]
Thanks, but as I just posted on the forum, the highlight bar was functioning properly when I fired up this machine tonight. Even though I restarted E and the bars appeared for other menus, pamac apparently needed a system reinit.
