### ISSUE TITLE
Update manager has no 'select none'/'select all' checkbox

### ISSUE THREAD

**Issue by heartofalion** [manjaro/pamac#118]
Recently the Pamac update manager presented me with 344 available packages to update. However since there were some issues with certain packages, I wanted to only update a few.

However, because all packages were checked, I had to uncheck all 344 of them manually and check the few that I wanted to update.

This could have been easily solved by a 'select none'/'select all' checkbox in the updater's GUI.

I hereby request this feature to make scenarios such as the one I'm mentioning easier for users.

Such a feature would be very useful and save a lot of time in certain scenarios.

I guess instead of a checkbox, it could be a button as well.

**Comment by ownadi** [comment]
:+1: 
It would be really helpful feature.

**Comment by philmmanjaro** [comment]
Well, if you uncheck a package you automatically add those to the ignore list. That is why we won't add such a feature at all ...

**Comment by philmmanjaro** [comment]
@guinux: correct me if I'm wrong with this one ...

**Comment by guinux** [comment]
No when you uncheck a package, it's just ignored for the current transaction but it's not saved in the ignore list autommatically.
However, I'm not for a check/uncheck all button because ignoring many updates is still risky for the stability of the system.

**Comment by ownadi** [comment]
@philmmanjaro @guinux sometimes there's need  for quick update just one specific package. This applies especially to AUR repository where full update might lasts long time. Its obvious that ignoring updates at all is not commended, I always do full update asap, but ability to quick uncheck all packages would be great anyway.
