### ISSUE TITLE
Cant run pamac - libalpm problem

### ISSUE THREAD

**Issue by prescott66** [manjaro/pamac#12]
I get this error while trying to run pamac-manager or updater:

pamac-manager: error while loading shared libraries: libalpm.so.8: cannot open shared object file: No such file or directory

**Comment by manjaro** [comment]
Pamac is not yet ready for Pacman 2.0:
<pre>[phil@manjaro ~]$ pacman -Qo /usr/lib/libalpm.so.8
/usr/lib/libalpm.so.8 ist in pacman 4.1.2-8 enthalten</pre>

**Comment by manjaro** [comment]
This is fixed with Pamac 2.1 release
