### ISSUE TITLE
Updater fullscreen broken

### ISSUE THREAD

**Issue by prescott66** [manjaro/pamac#122]
Fullscreen of pamac 4.0 updater looks like this on MATE 1.12. Screen size: 10,1"  Resolution:1024x576
Fullscreen of package manager is displayed correctly...

![screenshot at 2016-05-09 21 35 52](https://cloud.githubusercontent.com/assets/735265/15125880/7cc59d66-162f-11e6-9269-e017ce040ceb.png)

**Comment by philmmanjaro** [comment]
this is window mode or fullscreen?

**Comment by prescott66** [comment]
This is after maximise button clicked

**Comment by prescott66** [comment]
In 4.1 is whole window visible. so it is fixed. thanks
