### ISSUE TITLE
aur update leaves terminal window open.

### ISSUE THREAD

**Issue by pantar85** [manjaro/pamac#124]
as said.

when all the programs have been updated, it shouldn't leave the updating terminal window open, it should go back to the main pamac-upgrader menu.

**Comment by philmmanjaro** [comment]
Hi @pantar85: this is not a bug, it is a feature. If there are any details displayed the window stays open. However we can think about adding an option to autohide details by default.

**Comment by pantar85** [comment]
hey phil, love the new pamac, great work.

> If there are any details displayed the window stays open.

so every aur update is going to leave the terminal open?

i don't mind so much, its just like a loading dialogue. but in my mind a loading dialogue should disapear after its loaded, unless it hasnt loaded.

if its not a bug thats fine. just following the logical steps of what happens, it doesn't strike me as fitting in. could easily be me. cheers

**Comment by guinux** [comment]
fixed with  4c903f3
