### ISSUE TITLE
Pamac 4.0-1 “remove unrequired dependencies” keeps turning off

### ISSUE THREAD

**Issue by heartofalion** [manjaro/pamac#125]
When I go to preferences in Pamac 4.0-1 and turn on "remove unrequired dependecies" and then close the preferences and then open them again, then that option is turned off again.

More people have run into this issue: https://forum.manjaro.org/t/pamac-4-0-1-remove-unrequired-dependencies-keeps-turning-off/599

**Comment by guinux** [comment]
Thanks, fixed with 2282fa5
