### ISSUE TITLE
Pamac v4.1 feedback

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/pamac#126]
Hi all,

Guillaume was working for some time on a new design for **pamac**. Even if there is still some work to do, he wants some feedback on the work he had done so far. That for he proposed a preview version.

It has a new design:

- click on a package name or right click and choose details to view details.
- in dependencies view, click on a dependency to view its details and remove or install it
- you can continue browsing packages while a transaction is running
- progress bar added also in compact mode
- new details view on updater

So tell us what you think about it ...

---

**How to install**

Unstable branch
```
sudo pacman -Sy pamac
```

Any branch
```
sudo pacman -U http://mirror.netzspielplatz.de/manjaro/packages/pool/overlay/pamac-4.1.0-1-$(uname -m).pkg.tar.xz
```

---

**Images**

![pamac-41](https://cloud.githubusercontent.com/assets/5050022/15262730/776da754-1964-11e6-839e-fd9ef7274260.png)
New right click menu

![pamac-41-d](https://cloud.githubusercontent.com/assets/5050022/15262735/814517e4-1964-11e6-8de8-d1eda3184f33.png)
New details view

**Comment by Spatry-CupOfLinux** [comment]
AWESOME STUFF! Thanks Guillaume & Phil!

**Comment by tgharib** [comment]
Good design :thumbsup:

**Comment by guinux** [comment]
Thanks,
note that now only a single click  on package name is needed to view details,
multiple packages selection is still possible, you have to click package in other columns ;)

**Comment by philmmanjaro** [comment]
@guinux: I would keep the double click for details, otherwise users won't get it how to multiselect. Also I'd like to see a small progressbar like thunderbird or firefox does so the user sees some progress. I know we want to go for don't bother the user approach, but a little progressbar will please most of them that some is going on.

**Comment by badbodh** [comment]
if progress-bar is hard to get in, even a text % progress will do. We are pretty much used to "Windows is updating 25% Please don't turn off your computer"

**Comment by badbodh** [comment]
Looks like https://github.com/manjaro/pamac/issues/125 is back in 4.1b1-1 (pamac-dev,testing) , can't "Remove unrequired dependencies"

**Comment by philmmanjaro** [comment]
@badbodh: please check also **4.0** for it ...

**Comment by badbodh** [comment]
i'm in testing, 4.1.0 (default "pamac" package) is okay. Only "pamac-dev" shows this problem. I checked /etc/pamac.conf , `RemoveUnrequiredDeps` is active

**Comment by philmmanjaro** [comment]
@badbodh: I accidentally released v4.1-beta1 as rebuild of v4.0 and in the original v4.1-beta1 this patch was not yet included. **pamac-dev-4.1b1-2** fixes it, as it is the same code as the old **pamac** package. So **v4.0.1** will revert the **v4.1.0** changes and still adds the fix.

**Comment by badbodh** [comment]
> pamac-dev-4.1b1-2 fixes it
Thank you.

**Comment by kouros17** [comment]
I'm on unstable branch and after an update today I have pamac 4.0.1 but normally I should have 4.1 version.
I'm wrong somewhere;

![_2016-05-15_23-40-12](https://cloud.githubusercontent.com/assets/3219560/15276642/c5432d1c-1af6-11e6-8885-bf8a9732289c.png)
![_2016-05-15_23-40-27](https://cloud.githubusercontent.com/assets/3219560/15276644/c8baeb88-1af6-11e6-993d-86aa318a7a36.png)

**Comment by mgundogdu1** [comment]
Finding all needed stuffs one page was so easy to use and handy. In my opinion; for an end users point its a little confusing and needs a little time to learn how to learn details, dependencies etc.
I think all documents should present one page.

**Comment by philmmanjaro** [comment]
Second beta is now online.
@guinux: in the forums users with low screen resolutions claim that the new pamac is to big. Can we somehow lower the default size of **pamac** or add an option to settings for that?

**Comment by philmmanjaro** [comment]
I reduced now the default width and height. What do you guys think?

**Comment by tulliana** [comment]
It must show the percentage of jobs working with Pamac-dev.

as Octopi..
http://i.hizliresim.com/r9L21a.png

and

Pamac window size is too large. It should be a little smaller.
http://i.hizliresim.com/0DVBZV.png

**Comment by MonroOnManjaro** [comment]
The window size of the latest version is much better then the previous 4.0.1-1 I had, and the details pane no longer jumps automatically. 
Thank you for these fixes.

Still, I would like to see the details pane at the bottom of the packages list, as it used to be before ver 4.
Then, one could have seen things in a glance, or not, as one needed.

Now, any additional info requires more clicks. Not good for fluent productive work, IMHO.

**Comment by philmmanjaro** [comment]
@tulliana: please test the latest dev-build and give me your feedback.
@MonroOnManjaro: we do a different approach with this one. Keep the updates and management hidden as possible. The new details view also offers to jump in between dependencies and remove and install these. Sure it is a different workflow as before but we will see how it works.

**Comment by tulliana** [comment]
I tested last works and I liked. Thanks Philip.

**Comment by tulliana** [comment]
![ekran goruntusu_2016-05-18_21-31-37](https://cloud.githubusercontent.com/assets/2324162/15371513/7183b1c4-1d44-11e6-86f2-346dc30a029b.png)

I made a few cosmetic work.

**Comment by mgundogdu1** [comment]
I wonder that you can add cache clean options to pamac for end users, and enable which caches will delete or remai.

**Comment by philmmanjaro** [comment]
v4.1.0-rc1

- reduce default size
- fix single package installer
- fix #133
- update translations

**Comment by LizziAS** [comment]
So i am having trouble with the keys  either with the gpg command or the pacman command to get the keys.  After i run the above command i get:

sudo pacman -U http://mirror.netzspielplatz.de/manjaro/packages/pool/overlay/pamac-dev-4.1rc1-1-$(uname -m).pkg.tar.xz
loading packages...
error: '/var/cache/pacman/pkg/pamac-dev-4.1rc1-1-x86_64.pkg.tar.xz': package missing required signature

**Comment by LizziAS** [comment]
sudo pacman -U http://mirror.netzspielplatz.de/manjaro/packages/pool/overlay/pamac-dev-4.1rc1-1-$(uname -m).pkg.tar.xz
loading packages...
error: '/var/cache/pacman/pkg/pamac-dev-4.1rc1-1-x86_64.pkg.tar.xz': package missing required signature

**Comment by philmmanjaro** [comment]
Try this:

```
wget http://mirror.netzspielplatz.de/manjaro/packages/pool/overlay/pamac-dev-4.1rc1-1-$(uname -m).pkg.tar.xz
wget http://mirror.netzspielplatz.de/manjaro/packages/pool/overlay/pamac-dev-4.1rc1-1-$(uname -m).pkg.tar.xz.sig
sudo pacman -U pamac-dev-4.1rc1-1-$(uname -m).pkg.tar.xz
```

**Comment by LizziAS** [comment]
PERFECTION!  Thanks :)

**Comment by ItachiSan** [comment]
I  am really glad of the updater progress bar in the bottom area, really nice you added it as requested :smile: 
The only little things I would ask to add, as of now, are:
* moving all the options to the native GNOME application menu and replace the menu button with a "sync" one; so the only option of the button is sync repos and for management, informations and else Pamac use the default GNOME 3 style.
* Allow Pamac to remember sizes of windows before closing. The infos can be saved through a config file or a GSetting key, in my opinion.

**Comment by philmmanjaro** [comment]
**v4.1.0** is out now.

**Comment by ryanvade** [comment]
I agree with @ItachiSan in regards to the GNOME application menu entries.  As a suggestion, how about moving the search to a headerbar? Or would that be too GNOMEish?
