### ISSUE TITLE
allow launching updater while manager is running

### ISSUE THREAD

**Issue by M1cha** [manjaro/pamac#128]
it's kinda annoying having to close the manager before being able to update.
They should either be able to run at the same time or get merged into one universal application.

**Comment by guinux** [comment]
If you want to upgrade from the manager, click on "Refresh Databases" in the menu, it also check for updates after refresh :)

**Comment by M1cha** [comment]
in this case you should send a message to the manager to invoke the update when clicking the notification-icon instead of just telling the user that pamac is already running ;)

**Comment by notramo** [comment]
I think, #254 is a better idea.

**Comment by guinux** [comment]
Fixed in v5.0.0
