### ISSUE TITLE
improvement of feature mirror ranking

### ISSUE THREAD

**Issue by oberon2007** [manjaro/pamac#129]
It is awesome that the ranking of mirrors is accessible with pamac through the preferences. However the feature appears to be a little bit too much hidden for beginners while at the same time people are experiencing slow downloads with the default mirrorlist. 
Would it be an option to run pacman-mirrors automatically at first run, or at least trigger a popup notification about that possibility?

**Comment by tele1** [comment]
[Feature request]
+1
For me better will
1.  Ranking for packages from aur, negative points / comments will be a warning for users.
  but for build this pamac need 1 web page for data collection or aur web page need be updated.
  ( It can be build like plugin )
2. Plugin Benchmark for test speed all repositories.

Why plugins ?
Developers are trying to cram as much as possible to "iso" and need free space.

**Comment by guinux** [comment]
Calamares will run pacman-mirrors at post-install:
https://github.com/calamares/calamares-manjaro/commit/4d06049e0ad9bf6fc166f6df81a716e0e59bd4cb
An automation of pacman-mirrors is also implemented, I think it's enough.
