### ISSUE TITLE
Details window during download

### ISSUE THREAD

**Issue by oberon2007** [manjaro/pamac#132]
While package transactions are being processed (after for example you have selected packages to be installed and clicked apply and then commit) you would expect to see the progress displayed. I have heard several people saying that (including reviews on youtube) and I think it is true that this is what you would expect - to see the progress of the action currently happening.
At the moment the details window is set to be hidden by default and you have to click 'Details' for the window to be displayed. I think the other way round would just be more intuitive :wink:

**Comment by philmmanjaro** [comment]
Why can't people not wait? Please package **v4.1-beta2** if you can't wait ;)

**Comment by oberon2007** [comment]
> Why can't people wait? Please package v4.1-beta2 if you can't wait :smile:
Because people don't know that the good stuff is on the way already! :laughing: 
I thought that I had seen something about that somewhere... :wink:
