### ISSUE TITLE
AUR package doesn't stay deselected

### ISSUE THREAD

**Issue by noobpurple** [manjaro/pamac#133]
If I select an AUR package to install and deselect it, it will be selected again if I choose any package from the Repositories. I have to deselect it AGAIN to install only the package selected from the Repositories.

**Comment by guinux** [comment]
I can't reproduce it. Anyone else can ?

**Comment by philmmanjaro** [comment]
which exact version of **pamac** do you have installed @noobpurple. Do you run it on Arch or Manjaro?

**Comment by noobpurple** [comment]
I'm running it on Manjaro. The version number appears to be 4.0-2.

**Comment by noobpurple** [comment]
All of  my packages are up-to-date.

**Comment by noobpurple** [comment]
Oh, here's something. It doesn't happen if I click the "select" box. It only happens if I use the right-click menu for "install" and "deselect".

**Comment by noobpurple** [comment]
In fact, I don't have to use the "deselect" option from the right-click menu. It just re-selects the last unselected AUR package if I use the right-click "install" option.

**Comment by tgharib** [comment]
I can reproduce the bug. Here's a video of it: https://gfycat.com/ImpassionedDesertedGoa

**Comment by philmmanjaro** [comment]
Is this also tested with **v4.1-beta2**?

**Comment by noobpurple** [comment]
I just checked. I can confirm, if you use the right-click menu to deselect and install, it will still re-select the AUR package.

**Comment by tgharib** [comment]
@philmmanjaro I just tested with v4.1-beta2 and it appears the bug is still there.

**Comment by philmmanjaro** [comment]
@tgharib: @guinux is already working on it. Should been fixed with **v4.1**.
