### ISSUE TITLE
[Feature request] improved search

### ISSUE THREAD

**Issue by tele1** [manjaro/pamac#134]
I miss search options from Synaptic
"Search by name"
"Search in description"

because I noticed:
I wrote "fish" to search and I see also:
- fillets-ng
- zsh-history-substring-search
- zsh-syntax-higlighting

**Comment by M1cha** [comment]
also, there should be an option to match the beginning of the package name.
When I search for "linux-" I have to scroll all the way down to l to find the packages starting with "linux-".

**Comment by guinux** [comment]
sort search by relevance is implemented in eb57d65
