### ISSUE TITLE
add keybindings

### ISSUE THREAD

**Issue by ringo32** [manjaro/pamac#137]
add keybindings for pamac, like :+1: 
ctrl-q  quit
ctrl-s search
ctrl-g groups
ctrl-a aur
ctrl-i status

is just example\* keybinding is quite handy mayby handfull :p 

for pamac-tray would be awesome if entrance extra comes to renew repos manualy

**Comment by philmmanjaro** [comment]
@guinux: do we implement some of these already?

**Comment by guinux** [comment]
fixed in 31d8491
