### ISSUE TITLE
Updater :: Hangs when applying updates if there are notices from alpm to show the user

### ISSUE THREAD

**Issue by lots0logs** [manjaro/pamac#138]
### Problem:

Updater hangs after clicking "Apply" whenever there are any notices from alpm that should be displayed to the user. 

### Additional Notes:
When launched from a terminal, the following error is shown after clicking "Apply":
```
** (pamac-updater:12643): CRITICAL **: file /var/tmp/pamac/src/pamac-4.1.0/src/transaction.vala.c: line 11493: unexpected error: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying (g-dbus-error-quark, 4)
```

I checked the system journal to see if there were any errors from pamac-daemon but there were none. I also checked `/var/log/pamac.log` and there's nothing related to the error in there either.

**Comment by philmmanjaro** [comment]
Really odd problem. The details are now displayed in a terminal view inside of the installer. You have to click on **details** to view them. Do you have a package which needed user interaction? Or something to reproduce it?

**Comment by lots0logs** [comment]
Yes, I can view the details in the terminal view. However it doesn't proceed after displaying them. In previous versions Pamac after I clicked apply it would display a popup that had a button labeled "Commit" (if I remember correctly). It doesn't do that now. It just hangs after pressing Apply.

**Comment by philmmanjaro** [comment]
Ok, this might be a regression due the new **terminal view** added. Do you have a exact package set which needed user interaction on update? I think it is not just **AUR** related.

**Comment by guinux** [comment]
If there are no package to install or to remove (and just upgrades), no confirm dialog is shown when you click on the apply button but you should see the process begin in the progressbar (v4.1).
Do you see some lines in /var/log/pacman.log showing you the upgrade proceeded?

**Comment by lots0logs** [comment]
Looks like this is a false alarm. I completely removed pamac and then reinstalled it and its working fine now. I think there must have been some old files from when I was building it locally to test it a few weeks ago :sweat:
