### ISSUE TITLE
Offer option to copy log when build of AUR package fail

### ISSUE THREAD

**Issue by rgaiacs** [manjaro/pamac#139]
![screenshot_2016-06-08_17-12-09](https://cloud.githubusercontent.com/assets/1506457/15901768/9a312f3a-2d9c-11e6-9479-a4ccb8b6b953.png)

Having a button to copy the log will be useful.

**Comment by M1cha** [comment]
I'd prefer support for ctrl-shift to match the usual terminal behavior.
At the moment whenever I press ctrl+shift+c it sends ctrl+c which aborts the process instead of copying the selected text.

**Comment by guinux** [comment]
fixed in v4.3.x
