### ISSUE TITLE
Add option to go back to AUR terminal

### ISSUE THREAD

**Issue by rgaiacs** [manjaro/pamac#140]
After finished to build AUR package I ended up with

![screenshot_2016-06-08_17-12-09](https://cloud.githubusercontent.com/assets/1506457/15901819/de0b42d6-2d9c-11e6-9885-3be5fd12c29a.png)

I can go back to the "normal" screen using the button on the top left corner.

![screenshot_2016-06-08_17-09-40](https://cloud.githubusercontent.com/assets/1506457/15901841/f95da61e-2d9c-11e6-8d5e-cef602c38bb7.png)

But there is no way to back to the terminal output.

**Comment by luzpaz** [comment]
Click the 'Details' button ?

**Comment by guinux** [comment]
Fixed in v4.2.9
