### ISSUE TITLE
Add option to remove /var/lib/pacman/db.lck

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/pamac#142]
I know we had discussed this a lot, however it would be user friendly to offer also the option to remove `/var/lib/pacman/db.lck`. When set we get now an error message on being unable to sync the databases but not yet to remove the `/var/lib/pacman/db.lck` file. Users should know what that might mean, so a warning and a check if **pacman** is running should be added.

**Comment by guinux** [comment]
Implemented in 6bb6de0
