### ISSUE TITLE
Pamac Issue

### ISSUE THREAD

**Issue by pnbalaji** [manjaro/pamac#143]
Check out this video after changing the video resolution to 720p in youtube.

https://youtu.be/-UJWgW2jdQ4

I am having two issues with Pamac and Manjaro.

When I enable the option of "Update packages from AUR" in (check all checkboxes) in Pamac, it is reporting the package FSearch-git as an updatable package and pamac is allowing me to update. However, even after updating the package, Manjaro is reporting this package in the update list. This is issue #1.

Also, after updating the package, the back arrow button at the top left corner is pamac is not working. From the details view, clicking on this button should go to the list view, but it does not work. This is issue #2.

If the Devs of Manjaro can take a look and fix these issues, it would be great.

Thanks,
Balaji.

**Comment by pnbalaji** [comment]
Any updates on this bug?

Thanks,
Balaji.

**Comment by guinux** [comment]
I will see this when I'm back at home (next week).

**Comment by guinux** [comment]
For #1 it's was an error of the maintainer in the PKGBUILD file, it's now fixed,see the comments at:
http://aur.archlinux.org/packages/fsearch-git
For #2 I will fix it.

**Comment by pnbalaji** [comment]
Thanks for addressing both defects. Hats off to Manjaro devs!!
