### ISSUE TITLE
don't show update messages while updating AUR package

### ISSUE THREAD

**Issue by pointhi** [manjaro/pamac#144]
Today, the update messages "flooded" the status window even there was an AUR installation pending.

I would suggest not to show update messages while running AUR scripts.

**Comment by guinux** [comment]
What were exactly the "update messages" ?

**Comment by Strit** [comment]
I believe that pamac just takes the output from yaourt and shows it in the status window. So it would be the same messages as shown in the terminal running yaourt.

These messages needs to be there, to be able to trace errors etc.

**Comment by erikdubois** [comment]
Feature request

I was looking for a fix for the annoying popups from pamac telling me to there were 5 updates then 4 updates then 3 updates ... all these popups were on top of each other.
When you are updating your system via terminal, I suppose pamac is following the progress and gives you popups. It would be be great to be able to silence popups in the pamac icon with right mouse click. for one hour, four hours or a day. The messaging is quite 'persistent' (intruding). I am working on an Antergos I3 so these popups disturb the workflow. I have to take action to continue my work.
