### ISSUE TITLE
Wrong ETA calculation

### ISSUE THREAD

**Issue by prescott66** [manjaro/pamac#146]
Today i discovered strange ETA calculation, while updating fresh installation of Manjaro.
Update size was 326MB, real download speed was only cca 200kB/s and reamining time(ETA) was 40 seconds and after a while grows up to 2 minutes....so far away from real ETA with that speed.

**Comment by philmmanjaro** [comment]
ETA is dynamicly based on the given figures from **libalpm** if I'm not wrong. @guinux, please correct me if needed ...

**Comment by guinux** [comment]
Download speed is calculated everytime data is received. ETA is calculated from the average download speed so it is not precise in the beginning of the download.

**Comment by prescott66** [comment]
strange is, that i had constant download speed of 200kB/s and ETA remains 2 minutes during whole download...

**Comment by guinux** [comment]
It may dues to wrong data from libalpm or a problem in ETA calculation. Let's see there are others reports.

**Comment by robert1826** [comment]
i also confirm this

**Comment by MachmanFive** [comment]
I've been meaning to make precise observations on this for a while now but I always forget and go to sleep while the computer does the updates. What I can say is that even after a few minutes of download pamac still gives an ETA of about 9 minutes, which is a massive underestimation, given that most updates are 700MB+ and I'm sitting on a 1Mbps connection(ie. it actually takes about one hour and a half).
