### ISSUE TITLE
[Feature request] Info / Error if repository is off or not working.

### ISSUE THREAD

**Issue by tele1** [manjaro/pamac#147]
I use Xfce iso , it use in default 
http://h1860261.stratoserver.net/manjaro
I have note about update in red color
but repo is off, not working
(  http://repo.manjaro.org/  <-- red color )

When I seen ....
 why can not download core.db , extra.db  it is not obvious.

Can you use ping or something to check repository before update,
and give more clear error  ( maybe error with GUI ? )
"Sorry  repository is not responding. Please try to choose other repo in settings."

**Comment by philmmanjaro** [comment]
Well, we are not the host and providers of all mirrors. Mirrors might have issues and we don't have always the time to check them. If we find a way to detect this, we might add it also to **pamac**.

**Comment by tele1** [comment]
>  If we find a way to detect this, we might add it also to pamac.

It will best.

I seen problem when it tried download, so
maybe download or read "state" file ?
http://ftp.dei.uc.pt/pub/linux/manjaro/state

example in bash
`#!/bin/bash

timeout 2 curl -Is http://ftp.belnet.be/manjaro/ > /dev/null  ; echo $?
timeout 2 curl -Is http://manjaro.cu.be/ > /dev/null  ; echo $?
timeout 2 curl -Is http://mirror.rise.ph/manjaro/ > /dev/null  ; echo $?
timeout 2 curl -Is http://mirror.ragenetwork.de/manjaro/ > /dev/null  ; echo $?
timeout 2 curl -Is http://ftp.halifax.rwth-aachen.de/manjaro/ > /dev/null  ; echo $?
timeout 2 curl -Is http://ftp.tu-chemnitz.de/pub/linux/manjaro/ > /dev/null  ; echo $?
timeout 2 curl -Is http://mirror.netzspielplatz.de/manjaro//packages > /dev/null  ; echo $?
timeout 2 curl -Is http://mirror.netcologne.de/manjaro/ > /dev/null  ; echo $?
timeout 2 curl -Is http://h1860261.stratoserver.net/manjaro/ > /dev/null  ; echo $?
timeout 2 curl -Is http://repo.rhindon.net/manjaro/ > /dev/null  ; echo $?
timeout 2 curl -Is http://ftp.dei.uc.pt/pub/linux/manjaro/ > /dev/null  ; echo $?
timeout 2 curl -Is http://mirror.datacenter.by/pub/mirrors/manjaro/ > /dev/null  ; echo $?
timeout 2 curl -Is http://ftp.tsukuba.wide.ad.jp/Linux/manjaro/ > /dev/null  ; echo $?
timeout 2 curl -Is http://ftp.riken.jp/Linux/manjaro/ > /dev/null  ; echo $?
timeout 2 curl -Is http://repo.manjaro.org.uk/ > /dev/null  ; echo $?`

gives

`$ ./test
0
0
0
0
0
0
0
0
124
0
0
0
0
0
0
`

- "124" this is error, "0" is ok.  But it is not ideal, I have sometimes "124", maybe it is too fast.
- timeout is for close command after 2 second, because the website may not answer

**Comment by guinux** [comment]
I plan an automation of pacman-mirrors -g.
See #153

**Comment by guinux** [comment]
If the repo is totally offline pacman-mirrors -g will remove it from the mirrorlist.
Automation is implemented in 74d1902
