### ISSUE TITLE
[Feature Request] Support https repositories in pamac-updater

### ISSUE THREAD

**Issue by Strit** [manjaro/pamac#148]
I'd like the ability to update using https repositories defined in /etc/pacman.conf with Pamac.

Currently I get a "could not launch downloader" or something error, when trying to update. Installing new packages work fine.

If I change the repository to use the http version in /etc/pacman.conf it updates without a problem.

**Comment by guinux** [comment]
It's in my TODO list ;)

**Comment by Strit** [comment]
Great. ;)

**Comment by guinux** [comment]
I tried to fix SSL support in my last commit, please try and report.

**Comment by guinux** [comment]
Seems fixed in v4.1.2
