### ISSUE TITLE
Pamac 2.1 is not respecting ignorepkg

### ISSUE THREAD

**Issue by manjaro** [manjaro/pamac#15]
Followed issue got detected by Ayceman: 

Pamac is not respecting ignorepkg for (at least) AUR packages again. I have **flashplayer-standalone** on ignore and it's reading it in settings, but the updater still wants to update.

**Comment by manjaro** [comment]
@Ayceman: please check if you have enabled any ignored packages within pamac settings:

<a href='http://wstaw.org/w/387Z/'><img src='http://wstaw.org/m/2015/01/03/ignore-pkgs_jpg_640x400_crop_q85.jpg'></a>

**Comment by alexandruianu** [comment]
It is certainly there and reading it. I had actually edited the line to remove dropbox from ignored, and flashplayer-standalone is set to ignore visible both there and in the pacman config file. I tried removing and readding from both places.
