### ISSUE TITLE
pamac improvement request.

### ISSUE THREAD

**Issue by ringo32** [manjaro/pamac#151]
Pamac uses Dbus for password... make in pamac-settings if users wanna use pamac-tray without password, then settings set the polkit rules to use pamac-tray. just need confirm with password..

Also Make pamac workable with pacman-key work out if some bad keys as example pamac search for it ? like :  
http://jjacky.com/kalu/kalu-ss3.png

if key issues pamac solves it... is needed i guess?? even some errors is by keys as example... is a returning issue generally.. possible add to pamac-tray as those option is userfriendly?

**Comment by guinux** [comment]
I'm not for giving the possibility to remove or install packages without a password.
Pamac already uses libalpm options to auto import new keys and remove obsolete keys.

**Comment by jshand2015** [comment]
i second the motion.  you do not want to leave the system wide open to anyone do you.  that is a severe privacy breach
