### ISSUE TITLE
[Feature request] Automated cache cleaning

### ISSUE THREAD

**Issue by Photon89** [manjaro/pamac#154]
Add a tab called "Cache" in pamac's settings with the option "Clean cache [tick/untick]" and further options like "Every [week/month/3 months/year/custom...]" or "After every [transaction/update], "Number of packages to keep: [0].

An ASCII mockup:

```
Cache

Automated cache cleaning________________[On/Off]
___Clean every___________________[TIME INTERVAL]
___Clean after___________________________[EVENT]
___Keep number of packages______________[NUMBER]
```

Default settings might be: On, never, update, 1.

See also https://forum.manjaro.org/t/pkgrotate-for-pacman-cache/7605/1 for user case and discussion.

**Comment by guinux** [comment]
Hi all,
I'm the developer of pamac,
what would you think about adding a systemd timer unit to monthly run "paccache -r" in pamac?

**Comment by Photon89** [comment]
Hi, thanks for the reply! I think, just fixing it to a monthly run would upset some users who want more flexibility (switch the cache cleaning off completely, for example, but ideally also control when and what to delete). Maybe have a look at the poll in the thread linked in the report? I don't know how much work is implementing a fully configurable cache cleaning would be, though.

**Comment by guinux** [comment]
see 412d1f9 :)

**Comment by Photon89** [comment]
Thanks a lot for the quick implementation! I cannot test it directly, because I'm afraid of getting conflicts with the standard pamac installation (maybe I should have a VM for such cases...) but from what I understand in the diff logs, it looks great!

**Comment by Photon89** [comment]
I have again received complaints that the cache (and therefore also the / partition) is running full from time to time. Have checked the Pamac settings and realized that there is only a manual cleaning option, but no option to create a recurrent task for it. Would this be possible to implement? Thanks!

**Comment by Photon89** [comment]
Any comments on closing this? Did I miss the automatic cache cleaning being implemented into Pamac? 🙂

**Comment by guinux** [comment]
see 603bbb2
