### ISSUE TITLE
Update tray to support SNI spec

### ISSUE THREAD

**Issue by pdf** [manjaro/pamac#159]
Currently the tray does not work with Plasma.  In the short term, this may be a bug in the plasma xembed proxy, however the current hacks to continue xembed support in Plasma/Unity will not stick around in the long term.

I believe [StatusNotifierItem](https://www.freedesktop.org/wiki/Specifications/StatusNotifierItem/) is supported by most desktops (GNOME Shell being the exception, though they no longer support xembed either, and GtkStatusIcon is deprecated), and AIUI libappindicator supports SNI while providing a fallback to xembed, so just switching to libappindicator from libnotify might be enough to sort this out.

**Comment by guinux** [comment]
implemented in a405052

**Comment by pdf** [comment]
So fast, thx @guinux!

Menu and icon updates appear to work well, however left-click does not open the updater when updates are pending - probably needs another conditional.

**Comment by guinux** [comment]
see c394a74

**Comment by pdf** [comment]
:+1:  working now, thanks @guinux.

**Comment by guinux** [comment]
In Manjaro, the appindicator tray is now splitted in another package named pamac-tray-appindicator.

**Comment by pdf** [comment]
Thanks, appears to work well.
