### ISSUE TITLE
Running zenity in post instalation script fails

### ISSUE THREAD

**Issue by alexandruianu** [manjaro/pamac#16]
Running a zenity popup is to warn of an really important package related notification that you can't really afford to gloss over. This may be used for imminent kernel drop notifications, and is currently used for dropbox2 to tell the user how to disable its unconfigurable selfupdater.

The problem is that when the output is running in the pamac terminal, zenity fails to generate the window, saying that it can't open the display, which means something isn't right with $DISPLAY in pamac.

**Comment by guinux** [comment]
This package doesn't exist anymore.
