### ISSUE TITLE
Since Appindicator was added, it is horrible to build pamac on Archlinux

### ISSUE THREAD

**Issue by FredBezies** [manjaro/pamac#162]
I'm using pamac-aur. I tried to upgrade port from 4.1.1 to 4.1.3. When I tried to build it, I got this error log : 

```
valac -o pamac-tray \
-X -w --pkg=posix -X -DGETTEXT_PACKAGE="pamac" --target-glib=2.38 \
--pkg=gtk+-3.0 \
--pkg=appindicator3-0.1 \
--pkg=libnotify \
common.vala pamac_config.vala \
tray.vala
error: Package `appindicator3-0.1' not found in specified Vala API directories or GObject-Introspection GIR directories
```

To be able to build it again on archlinux, I have to build libappindicator... Why? Is it really needed ? I'm not using KDE at all. So, building libappindicator is really a pain in the bottom :(

Any tip to disable this late requirement ?

**Comment by guinux** [comment]
Should be fixed with 6b1bf5c, see the commit comment for details.

**Comment by FredBezies** [comment]
AUR maintainer applied patch to remove appindicator depend. So, until next pamac is released... :D 

Thanks for the commit.

**Comment by FredBezies** [comment]
4.1.4 is released, but not version number is not updated ?!

**Comment by guinux** [comment]
If you mean the version number displays in About Pamac dialog it's just because I often forget to change it :)

**Comment by FredBezies** [comment]
Yes I meant that. Could be disturbing. 4.1.4 or 4.1.3? Which one is the good one? Well...

**Comment by guinux** [comment]
I understand, sorry for this mistake.

**Comment by philmmanjaro** [comment]
Fixed with https://github.com/manjaro/pamac/commit/e2eb81c9e5123a233a7bd429a832bb90f881c705

**Comment by FredBezies** [comment]
Thanks!
