### ISSUE TITLE
[Enhancement] No root password cancel all pending operations

### ISSUE THREAD

**Issue by jshand2015** [manjaro/pamac#167]
If a person wants to install an application and then decides not to then all current pending operations would be cancelled when root password not entered

**Comment by guinux** [comment]
I don't understand because when you click on cancel button in the authentication window, the pending operations are not erased.

**Comment by jshand2015** [comment]
yes, that is exactly what happens.  the program should then abort any changes you made.  if you want to know more.  just hit back

**Comment by guinux** [comment]
You can decide to not enter your password for many reasons, why it would be better to make pamac forget all current operations in this case ?
