### ISSUE TITLE
dmesg error

### ISSUE THREAD

**Issue by jshand2015** [manjaro/pamac#168]
pamac-daemon[6861]: segfault at 20 ip 00007fb08de46490 sp 00007ffee0f13af8 error 4 in libglib-2.0.so.0.4800.2[7fb08ddc2000+10d000]

**Comment by guinux** [comment]
This doesn't help. A segfault can occur for many reason, what did you try to do when this occured ?

**Comment by jshand2015** [comment]
to be honest i actually have no idea what caused this issue, however it hasn't happened again.  may have been something to do with the cachecleaner timer etc

**Comment by jshand2015** [comment]
i am now using 4.1.4.  please close if resolved in this release
