### ISSUE TITLE
[Feature request] Adjustable systemd timer unit for generate mirrorlist monthly

### ISSUE THREAD

**Issue by ghost** [manjaro/pamac#169]
I want to disable the systemd timer unit to generate mirrorlist monthly in pamac.
It is possible to make this feature adjustable?

**Comment by guinux** [comment]
sudo rm /usr/lib/systemd/system/multi-user.target.wants/pamac-mirrorlist.timer

**Comment by kouros17** [comment]
Thanks a lot!

**Comment by guinux** [comment]
timers are now desactivable via systemctl
