### ISSUE TITLE
Failed to commit transaction: Delta Patch Failed

### ISSUE THREAD

**Issue by Vistaus** [manjaro/pamac#171]
I always get this message when trying to install .delta updates. Both Pacman and Yaourt have no problem with these updates, but pamac does. So I always have to resort to Pacman or Yaourt to install these updates, but of course I want pamac to handle these as well.

**Comment by guinux** [comment]
I must admit I never test pamac with delta updates but it should be handled by libalpm.
Can you give me the mirror you use ?

**Comment by Vistaus** [comment]
I've tried several mirrors over the past few days and they all result in pamac giving this error. Yesterday I used Reflector to maintain a good mirrorlist but this issue still remains. My mirrorlist is as follows:

`################################################################################
################# Arch Linux mirrorlist generated by Reflector #################
################################################################################

# With:       reflector --protocol https --latest 30 --number 20 --sort rate --save /etc/pacman.d/mirrorlist
# When:       2016-09-10 16:45:42 UTC
# From:       https://www.archlinux.org/mirrors/status/json/
# Retrieved:  2016-09-10 16:43:13 UTC
# Last Check: 2016-09-10 16:34:49 UTC

Server = https://arch.jensgutermuth.de/$repo/os/$arch
Server = https://mirror.pseudoform.org/$repo/os/$arch
Server = https://mirrors.niyawe.de/archlinux/$repo/os/$arch
Server = https://mirror.tyborek.pl/arch/$repo/os/$arch
Server = https://mirror.hactar.xyz/$repo/os/$arch
Server = https://mirrors.dotsrc.org/archlinux/$repo/os/$arch
Server = https://archlinux.thaller.ws/$repo/os/$arch
Server = https://fooo.biz/archlinux/$repo/os/$arch
Server = https://mirror.metalgamer.eu/archlinux/$repo/os/$arch
Server = https://mirror.one.com/archlinux/$repo/os/$arch
Server = https://archlinux.mirror.pkern.at/$repo/os/$arch
Server = https://mirror.neuf.no/archlinux/$repo/os/$arch
Server = https://mirror.js-webcoding.de/pub/archlinux/$repo/os/$arch
Server = https://arch.packages.zachlge.org/$repo/os/$arch
Server = https://ftp.sh.cvut.cz/arch/$repo/os/$arch
Server = https://pkg.adfinis-sygroup.ch/archlinux/$repo/os/$arch
Server = https://mirrors.atviras.lt/archlinux/$repo/os/$arch
Server = https://ftp.tuxdroid.org/archlinux/$repo/os/$arch
Server = https://k42.ch/mirror/archlinux/$repo/os/$arch
Server = https://mirror.system.is/arch/$repo/os/$arch`

**Comment by guinux** [comment]
I will wait some days to have updates and try using deltas.

**Comment by mastercoms** [comment]
Do you have xdelta installed?

**Comment by Vistaus** [comment]
Yes:
vistaus@vistaus-arch:~/Apps$ yaourt xdelta
1 community/xdelta3 3.0.11-1 [installed]
    Diff utility which works with binary files
2 aur/xdelta 1.1.4-6 (9) (0.00)
    Binary file delta generator
==> Enter n° of packages to be installed (ex: 1 2 3 or 1-3)
==> -------------------------------------------------------
==> ^C
vistaus@vistaus-arch:~/Apps$ 

But for some reason, the issue seems to be solved now. Maybe it was a bug in Arch rather than in pamac. I'll close this for now.
