### ISSUE TITLE
Issues with managing pamac through systemctl

### ISSUE THREAD

**Issue by v1kn** [manjaro/pamac#172]
`pamac-daemon` keeps autostarting even though I explicitly disabled `pamac.service`, `pamac-cleancache.service`, `pamac-cleancache.timer`, `pamac-mirrorlist.service`, `pamac-mirrorlist.timer`.  The only sure way I found to completely disable `pamac` on boot, is to rename all its services, but it is a dirty solution. 

I observe the behavior on Arch Linux. The timers also keep autostarting in Manjaro Linux vbox guest.

Basic troubleshooting commands outputs can be found here: [reddit thread](https://www.reddit.com/r/archlinux/comments/5230a3/systemctl_pamac_does_not_take_no_for_an_answer/). If linking to 3rd party forum posts is not standard practice, I can paste the commands here, if instructed to do so.

**Comment by lots0logs** [comment]
I can confirm this issue. Its because Pamac installs a desktop file in `/etc/xdg/autostart`

**Comment by guinux** [comment]
Try to also disable NetworkManager-dispatcher.service to not auto refresh databases when an internet connection is up.

**Comment by v1kn** [comment]
Doing this, does ineed disable `pamac.service` on boot. However, both timers are still runing (loaded active waiting)

**Comment by guinux** [comment]
Yes but it's just timers. It doesn't use ressources except when the command is running (once a month) to clean package cache or refresh mirrorlist.
But if you want to disable them see #169

**Comment by v1kn** [comment]
I succesfully deleted the timers. If i understand correctly, if I want them back I can simply symlink them back to muli-user.target wants, correct?  

This concludes this issue then. This was an obscure fix however. I haven't thought about network manager having anything to do with it

**Comment by philmmanjaro** [comment]
@guinux: we might add an UI option for this, what do you think?

**Comment by lots0logs** [comment]
@philmmanjaro @guinux I think we need to let systemd have complete control over whether or not pamac services are run at startup. There shouldn't be anything installed into `/etc/xdg/autostart` nor anything in Network Manager's config. That's too many cooks in the kitchen as the saying goes. It makes it impossible for less experienced users to disable pamac from startup (if they want to do so).

**Comment by guinux** [comment]
You guys simply discovered what many programs do.
First for the file in /etc/xdg/autostart, it is the standard way to autostart a program at session startup. Most DE provide a GUI to manage it, pamac tray icon can be disabled this way.
Then the file in Network Manager's config is to auto refresh databases, it's this one which let pamac-daemon running after boot, it should not, I need to fix it.
For other timer files, as I said, they doesn't have impact on used ressources but yes, if you want to be managable with systemctl command, there are some adjustements to do.

**Comment by guinux** [comment]
I tried a fix  for the remaining pamac-daemon after an auto refresh launched by NetworkManager, see c7f4220

**Comment by lots0logs** [comment]
> First for the file in /etc/xdg/autostart, it is the standard way to autostart a program at session startup.

Indeed that was the case prior to systemd. Now that we have systemd it is the preferred method, at least speaking from the POV of linux distributions (obviously users will have their own preferences).

**Comment by guinux** [comment]
> Indeed that was the case prior to systemd.
No, systemd is made to manage services at boot, not at session startup.

**Comment by lots0logs** [comment]
Is that not what [this](https://wiki.archlinux.org/index.php/Systemd/User) is for? :wink:

**Comment by guinux** [comment]
timers are now desactivable via systemctl
