### ISSUE TITLE
pamac legacy tray missing when using gnome and wayland

### ISSUE THREAD

**Issue by homza** [manjaro/pamac#177]
Pamac tray icon missing, with the latest stable version of Gnome 3 desktop.
I found that Gnome 3 uses the Wayland display manager by default now and the Pamac tray icon launcher does not work with Wayland.
The Pamac tray icon launcher works fine if you select Gnome on X-org display manager from GDM during a new Gnome session.
Jest some feedback...

**Comment by dielsonsales** [comment]
Just updated Gnome to 3.22.1 on Arch Linux and noticed the same issue, also using Wayland.

**Comment by guinux** [comment]
It's choice of Gnome developers to not show at all tray icons in Wayland session (like not show desktop icons). You can try topicon extension or Gnome on Xorg session.

**Comment by dielsonsales** [comment]
I'm using topicons and Dropbox is being shown correctly though.

**Comment by homza** [comment]
I just tried "The Topicon extensions" available available in the AUR gnome-shell-extension-topicons-plus-get as well had no success while using Wayland.
That is not an acceptable solution to a software bug "install something else"...
Pamac tray only works while using Xorg.
I submitted this issue because I think this is going to be a bigger issue for this project as Wayland adaptation becomes more prevalent in the future and I think a developer should look into it.

**Comment by dielsonsales** [comment]
Besides Wayland has become the default for this new version of Gnome, and you have to explicitly change to Xorg if you want; which means a lot more users will be experiencing this bug soon.

**Comment by homza** [comment]
Note: I noticed Gnome notifications show up correctly when there is an update available using pamac-aur 4.1.5-2 and Wayland, just no bottom left tab thing visible.

**Comment by guinux** [comment]
Yes, I tried topicon extension doesn't work on wayland session, it seems tray icon support is totalyy missing on wayland session. But I repeat: it's not a pamac bug, it's a choice from Gnome developers.

**Comment by dielsonsales** [comment]
>it seems tray icon support is totalyy missing on wayland session

But there must be a way to make it work, since Dropbox icon keeps working correctly.

**Comment by homza** [comment]
Hi everyone, "Guinux" is correct, it's not a Pamac bug, I researched this issue a little and found that Wayland introduced some enhanced security features that X-org does not have one in particular is application white-listing so if this application is not white-listed it will not run on Wayland or unless certain parameters are met, as for "Dielsonsales" Dropbox working it's a more popular application than Pamac so someone probably white-listed it.
This is just my thoughts after reading a-bit, most likely something Wayland security related, I could be wrong...

**Comment by homza** [comment]
"Dielsonsales" I found something that works quite well for notifying you of Arch and Aur updates it's a Gnome extension located in the Aur called "gnome-shell-extension-arch-update" after installing restart and it will show up in Gnome weak tool extensions, change the settings to,,
Command to check for updates
/bin/sh -c "/usr/bin/checkupdates ; /usr/bin/yaourt -Qqu -a"
Command to update packages
gnome-terminal -e 'sh -c  "yaourt -Syu --aur ; echo Done - Press enter to exit; read" '
This is a temporary working alternative for Arch Linux users having issues being notified of updates via Pamac-aur with Wayland  and Gnome...
