### ISSUE TITLE
[UI Feature Request] on mouse hover put package description in tooltip if window size truncates it

### ISSUE THREAD

**Issue by luzpaz** [manjaro/pamac#178]
![screenshot_2016-10-15_07-34-52](https://cloud.githubusercontent.com/assets/4140247/19409791/0da42de2-92aa-11e6-940d-2adfe923100d.png)
(FYI I know this is a first world problem but what the heck might as well ask)
Pacman window by default opens pretty narrowly (at least for me) which obscures the package descriptions. Instead of each time of widening the window would it be possible to hover over the description and for it to display in a tooltip ?

**Comment by guinux** [comment]
It's an idea. I add it in my todo list :)

**Comment by luzpaz** [comment]
Awesome! looking forward to testing this. Thanks @guinux
