### ISSUE TITLE
[Feature request] Search function improvement

### ISSUE THREAD

**Issue by petsam** [manjaro/pamac#181]
### Add a feature to "transfer" the filter text to the search box, when it is selected.

This can also help for easy filter refinement and also a "reset filter" possibility.
- It happens when looking for several packages, to create several filters. If you want to refine a filter entry (other than the last one entered) you have to re-type the (similar) filter again with some variation, trying to overrun the time delay for filter application. 
- This can minimize the database calls due to mistyping errors. 
  So instead of reading the filter entry list, the code can read the search box.
  There is an [old forum topic](https://forum.manjaro.org/t/after-searching-in-pamac-how-do-you-get-back-to-the-full-package-list/4071) about it, so it might not be possible to code this. If so, just close the issue.

Regards.

**Comment by guinux** [comment]
I must admit I don't really understand what you want. Do you hace an example?

**Comment by petsam** [comment]
[A video about the suggestion ](https://mega.nz/#!gd4UAbbC!yHeuHBLvrvfZym1JwqBLgX_HO8Lbw0IvfWQ5hJWnVSo). When clicking on a filter I say the filter texts appears/replaces the filtering text box text.
[A video about the issue with different reaction on AUR section](https://mega.nz/#!sQY0gBgS!q-Rn7UW8f_y3HXstp2CPIiJEao24Z8F_jrxNNd5ojyU) 
I hope they help understanding.

**Comment by guinux** [comment]
I understand now, it's a good idea. And the "null" search must be fixed. Thx
