### ISSUE TITLE
[4.1.6-1] Main window blocked when conflicting packages errors occured

### ISSUE THREAD

**Issue by petsam** [manjaro/pamac#182]
I tried to install arc-gtk-theme having already arc-themes-maia installed. On Apply, after checking for conflincting packages, the main window was stuck and un-clickable. I could only move it with Alt-drag.
The only option was to kill it from Task manager.
After a short investigation and after I worked arround with proper "first uninstall and then install" conflicting packages I found out:
- There was an invisible window with full screen height that I could move by the workspaces panel applet.
- There were many error processes produced by pamac (in Task manager tree view)
- After a second attempt the task manager itself hag up as well. I had to use htop to close both apps.

I have done a recent update.

**Comment by philmmanjaro** [comment]
Which DE was used. Normally it is a separate window which informs you about the conflict.

**Comment by petsam** [comment]
XFCE. As I wrote, I realized the conflict announce window only on the workspaces panel app. In fact I moved it to the next workspace but it was still invisible. After I went back to the pamac workspace, I noticed the invisible window followed that as well. 
Strange behavior, I can tell, though that's it!!
