### ISSUE TITLE
custom Path variable, where to put it?

### ISSUE THREAD

**Issue by gcoda** [manjaro/pamac#186]
I was trying to build ring-daemon, it failed with pamac, pod2man not found
i got custom path variable (/usr/bin/core_perl) added in my default shell but pamac do not use my default shell, what shall i do about it?

**Comment by tele1** [comment]
I'm not developer, but I think you're going the wrong way.
- Wrong way is create custom path /usr/bin/core_perl  for  apps.

You want copy  app and put in other place for others apps ? 
- Good way is when all apps use the same app (dependencies) in one place.

How install app in place where I want ?
- Read build files for app, README , ask developers, check
`configure --help`
`cmake --help`
...
 example:
Read below
http://pclinuxoshelp.com/index.php/Installing_Software_without_Synaptic`
cmake .. -DCMAKE_INSTALL_PREFIX=/your/path/when/you/want/install/all/files `
This is 1 example
For ./configure you have also 
```
        --prefix=%{_prefix} \\\
	--exec-prefix=%{_exec_prefix} \\\
	--bindir=%{_bindir} \\\
	--sbindir=%{_sbindir} \\\
	--sysconfdir=%{_sysconfdir} \\\
	--datadir=%{_datadir} \\\
	--includedir=%{_includedir} \\\
	--libdir=%{_libdir} \\\
	--libexecdir=%{_libexecdir} \\\
	--localstatedir=%{_localstatedir} \\\
	--sharedstatedir=%{_sharedstatedir} \\\
	--mandir=%{_mandir} \\\
	--infodir=%{_infodir}
```
%{_ ... } --> this is macro, this is path ( for example /usr/bin )
and are used probably only in rpm, you need add own paths if you need.

**Comment by tele1** [comment]
Im not developer, but try to better explain.
```
$ locate pod2man
/usr/bin/core_perl/pod2man
$ pacman -Qo /usr/bin/core_perl/pod2man
/usr/bin/core_perl/pod2man belongs to perl 5.24.0-2
```
- "added in my default shell but pamac do not use my default shell," what this mean ?

**Comment by gcoda** [comment]
I am using fish shell.and to build `ring-daemon` with `yaourt` i needed `perl` and `pod2man` in `$PATH`. 
but, when pamac tried to update `ring-daemon` it started yaourt

**Comment by gcoda** [comment]
I am using fish-shell. iy set as default for user, `cat /etc/passwd | grep (whoami)` returns `....:/usr/bin/fish`
In my user config i got `/usr/bin/core_perl` added to $PATH environment variable.
When i am building `rind-daemon` with `yaourt` form terminal it works fine.
But when pamac updated AUR packages, yaourt it failed, it was started in bash or even sh, without my custom env variables.

**Comment by guinux** [comment]
Please try again with v4.2.9, I tried to fix it.
