### ISSUE TITLE
please catch ctrl+c and ask if user really want to abort

### ISSUE THREAD

**Issue by luzpaz** [manjaro/pamac#187]
.... because ctrl+c is also used to copy text in to the buffer. For someone migrating from OSX an used to pushing the apple+c button which translates to ctrl+c in linux makes it very difficult to use pamac. This is because the ctrl+c sequence will abort the pamac build.

**Comment by guinux** [comment]
Fixed in v4.2.9, ctrl+c now copy selected text to the clipboard.
