### ISSUE TITLE
Uninstalling a package warns for Optional depends as mandatory

### ISSUE THREAD

**Issue by petsam** [manjaro/pamac#189]
When I uninstall a package (my case was php56 from AUR) gives a warning for broking dependencies. 
I checked them and realized they were all Optional depends.
It would be better information if the dependencies warning separated the Mandatory and the Optional.

**Comment by guinux** [comment]
The mandatory dependencies are displayed in the transaction summary as "to remove".
The warning window only display optional ones as "foo optionally requires bar".
