### ISSUE TITLE
[Freeze] when triyng to install playforlinux

### ISSUE THREAD

**Issue by luzpaz** [manjaro/pamac#191]
Manjaro 16.10
Pamac 4.1.6-2

Steps to reproduce:  
1) Open Pamac  
2) enter "playforlinux"  
3) check box to install  
4) The following warnings will come up: http://i.imgur.com/VfvBL9k.png  
5) Press 'Close'  
Result: Freeze. Must SIGKILL pamac to close.

**Comment by philmmanjaro** [comment]
Please test if [v4.1.7](https://github.com/manjaro/pamac/releases/tag/v4.1.7) still has the same issue. Available in **testing** or **unstable** branch.

**Comment by luzpaz** [comment]
@philmmanjaro how do i download 4.1.7 ? via pamac ?

**Comment by philmmanjaro** [comment]
`sudo pacman -U http://repo.manjaro.org.uk/pool/overlay/pamac-4.1.7-1-$(uname -m).pkg.tar.xz`

**Comment by luzpaz** [comment]
@philmmanjaro works in 4.1.7 :) 
Thanks!
