### ISSUE TITLE
Pamac fails to install split AUR packages

### ISSUE THREAD

**Issue by MaycneSonahoz** [manjaro/pamac#192]
I file this issue following a discussion started on the forum:
https://forum.manjaro.org/t/aur-installing-error/13139

The topic is about Pamac failing to install the **cinnamon-sound-effects** package from AUR. A workaround is to use directly yaourt, since it doesn't have a problem installing this package.
I found this topic when having myself an issue while trying to install **vivacious-colors-icon-theme**, with the same workaround working. But knowing Pamac (might) use yaourt for AUR, if found this weird, so i dug a bit.

Long story short:
- both packages are actually split packages
- Pacman can't search AUR, so you need to either use yaourt, or pass it the package downloaded from AUR
- Pacman needs the base package in order to install a split package
- trying to download a usual package from AUR rather than the required base package does not fail, but the downloaded package in unusable

The following is a copy of post 8, in which i describe my findings:

I checked a bit the history log from pamac to see how it installs AUR packages, and instead of yaourt commands, i saw commands like

    pacman -U package-name.pkg.tar.xz

so my guess is that it builds the package first, then pass it to pacman.

I went and tried to build such package as described in Arch wiki. I tried with **vivacious-colors-icon-theme**, because that's the one i was interested in.

    curl -L -O https://aur.archlinux.org/cgit/aur.git/snapshot/vivacious-colors-icon-theme.tar.gz
This downloads a corrupted archive. You need to download the base package instead.

    curl -L -O https://aur.archlinux.org/cgit/aur.git/snapshot/vivacious-colors.tar.gz
    tar -xvf vivacious-colors.tar.gz
    cd vivacious-colors
    makepkg -s
This builds all packages from the package base. In this case:
- vivacious-colors-icon-theme-1.4-1-any.pkg.tar.xz
- vivacious-colors-folder-addon-1.4-1-any.pkg.tar.xz

Then you can install your package with pacman.

    pacman -U vivacious-colors-icon-theme-1.4-1-any.pkg.tar.xz

If that helps.

**Comment by philmmanjaro** [comment]
**pamac** uses **yaourt** directly and only sends cmds to **yaourt** and displays the results in a terminal.

**Comment by MaycneSonahoz** [comment]
Does it call yaourt right away, or does it try with pacman first?
When i tested, the displayed output was the same as when i called pacman. While yaourt did work.

**Comment by philmmanjaro** [comment]
AUR is deactivated by default. You have to activate that support.

**Comment by philmmanjaro** [comment]
However it has some issues with this particular package:
```
pkgbase=vivacious-colors
pkgname=("$pkgbase-icon-theme" "$pkgbase-folder-addon")
```
It errors out not finding **vivacious-colors**, which all points to **pkgbase**.

**Comment by MaycneSonahoz** [comment]
Do you ask for the target package or the base package?
- base package: **yaourt -S vivacious-colors** will fail saying it can't find the package.
- target package: **yaourt -S vivacious-colors-icon-theme** will succeed (and will also install vivacious-colors-folder-addon)

**Comment by philmmanjaro** [comment]
Seems **pkgbase**:

https://github.com/manjaro/pamac/blob/master/src/transaction.vala#L628
https://github.com/manjaro/pamac/blob/master/src/transaction.vala#L942

**Comment by lots0logs** [comment]
@philmmanjaro Just FYI..this is a known issue in yaourt. Sorry I don't have time to grab the link but you can find it on their github issues list.

**Comment by guinux** [comment]
I see the problem, it's because all pkgnames are different from the pkgbase.
I will fix it ASAP.
