### ISSUE TITLE
[Feature] Ability to automatically append -j4 to 'make' 

### ISSUE THREAD

**Issue by luzpaz** [manjaro/pamac#193]
This feature request would help me to remove an extra step of editing PKGBUILD
`==> Edit PKGBUILD ? [Y/n] ("A" to abort)`
so that I can tell `make` to use all my cpu cores `make -j4` when building to expedite the process.  

Is it possible to do this automagically ?

**Comment by guinux** [comment]
Pamac uses yaourt which calls makepkg to build packages.
You can do it bu editing /etc/makepkg.conf file, see:
https://wiki.archlinux.org/index.php/Makepkg#MAKEFLAGS

**Comment by luzpaz** [comment]
For posterity: 
Add to your `~/.bashrc` 
`export MAKEFLAGS="-j$(nproc)"
then run `source ~/.bashrc`
to check the flag you can run: `echo $MAKEFLAGS`
should output `-j` and the number of cores you have. So for me I see `-j4`
