### ISSUE TITLE
Left sidebar cannot be resized. It looks awful when maximized.

### ISSUE THREAD

**Issue by jknvv13** [manjaro/pamac#195]
![image](https://cloud.githubusercontent.com/assets/4403750/21724029/fdd3d942-d432-11e6-96e9-fef3b5ec6337.png)
See attached screenshot. You'll notice it.

**Comment by guinux** [comment]
Can you test if v4.1.8 fix this issue?

**Comment by philmmanjaro** [comment]
Fixed in **v4.1.8**.
