### ISSUE TITLE
[Feature] Ability to click on 'Packager' field which would be a mailto:// link 

### ISSUE THREAD

**Issue by luzpaz** [manjaro/pamac#198]
![image](https://cloud.githubusercontent.com/assets/4140247/21897626/326da136-d8b8-11e6-9043-bd717d3e5813.png)
I'd like to be able to click on 'Packager' which will trigger my email client to load. I'm asking for this because community packages are different then AUR packages in that they don't have a thread for each package for people to post about. 
Thanks

**Comment by luzpaz** [comment]
I realized through this recent experience that maintainers probably wouldn't appreciate direct email about fixing or feature requests. So I opened #200 as an alternative Feature Request. 
ref: https://github.com/manjaro/packages-community/issues/249

**Comment by guinux** [comment]
Fixed in V4.2.9
