### ISSUE TITLE
No pamac-tray icon with wayland in Gnome

### ISSUE THREAD

**Issue by somepaulo** [manjaro/pamac#199]
Hello!
I've seen issue #177, but the problem still persists. The pamac-tray icon is not showing up in the tray under wayland. Regular Gnome notifications work fine though, so does the daemon.
I noticed the tray actually appears when an update becomes available, so there is an action fired to display/update the icon. But when I move the mouse to the tray it disappears. If I have other legacy icons, the tray opens, but the pamac icon is not displayed.
The top-icons shell extension doesn't show the icon either.
Any news on making wayland show the icon?
Cheers!

**Comment by Th3Z0ne** [comment]
Hello - this problem is still a thing as of today; Under wayland everything works great except that the pamac-tray icon is not showing. Others that also reside in the legacy tray (or top icon plus) are showing just as expected.
