### ISSUE TITLE
guinux, please re institute --asroot option

### ISSUE THREAD

**Issue by anexation** [manjaro/pamac#20]
guinux, please re institute --asroot option in makepkg as i use this almost everyday and its very annoying a genius over at arch took this out.

https://gist.github.com/dalu/6cdda7e0376f602f97de

**Comment by anexation** [comment]
Dirty solution for the makepkg asroot problem

Background: The maintainers of the makepkg utility used to create Arch packages have, in all their infinite wisdom to protect the lesser beings, removed the asroot option and the possibility to build packages as user root.

My take: Arch started out great because it worked like Slackware: KISS and the ability to shoot yourself in the foot.

Temporary, somewhat ugly fix

We can edit /usr/bin/makepkg of course :-)

Add asroot to OPT_LONG (line 3366). Just search for "OPT_LONG".

OPT_LONG=('allsource' 'check' 'clean' 'cleanbuild' 'config:' 'force' 'geninteg'
          'help' 'holdver' 'ignorearch' 'install' 'key:' 'log' 'noarchive' 'nobuild'
          'nocolor' 'nocheck' 'nodeps' 'noextract' 'noprepare' 'nosign' 'pkg:' 'repackage'
          'rmdeps' 'sign' 'skipchecksums' 'skipinteg' 'skippgpcheck' 'source' 'syncdeps'
          'verifysource' 'version' 'asroot')
Remove EUID check (line 3577). Just search for "EUID".

if (( ! INFAKEROOT )); then
    if (( EUID == 0 )); then
        #error "$(gettext "Running %s as root is not allowed as it can cause permanent,\n\
#catastrophic damage to your system.")" "makepkg"
        #exit 1 # $E_USER_ABORT
        plain "$(gettext "Running as root restored by Orc ;)")"
    fi

**Comment by manjaro** [comment]
Lane, this has nothing to do with pamac. We have to think if we patch our pacman cos of that. Please discuss this in our internal development forum.
