### ISSUE TITLE
[4.1.6] Corrupted database may cause a denial of service

### ISSUE THREAD

**Issue by marmistrz** [manjaro/pamac#202]
I installed Manjaro 16.10.3 on a laptop. The core.db database was corrupt. Pamac updater was trying to handle that, creating hundreds of processes: (output from `ps  ax`)
```
6300 ? Ss 0:00 echo -n Error: could not open file /var/lib/pacman/sync/core.db: Unrecognized archive format
```
After a while, another ps yielded the same processes shown as defunct. 

As a result of this repeating multiple times, the fork limit has been exceeded, which caused a denial of service.

**Comment by guinux** [comment]
This is fixed in v4.2.0
