### ISSUE TITLE
Nicer window titles

### ISSUE THREAD

**Issue by prescott66** [manjaro/pamac#203]
Just wondering, if can be made window title of package manager/updater nicer and translatable.
Now it is "pamac-manager" or "pamac-updater" as you can see on your monitor or this screenshots
![snimka obrazovky z 2017-02-08 22-22-00](https://cloud.githubusercontent.com/assets/735265/22758049/477ef110-ee4d-11e6-8750-268d92bf16c1.png)
![updater](https://cloud.githubusercontent.com/assets/735265/22758246/2974fc4a-ee4e-11e6-98ca-9ca62a43f4d6.png)

It would be perfect to have translatable window titles  as "Package Manager" and "Software updater".
BTW when system is up-to-date, window title is translated as "Your system is up to date". I think it should be as "System updater" and string "Your system is up to date" should be only as label in pamac updater window
![translated](https://cloud.githubusercontent.com/assets/735265/22758250/2df0bc1e-ee4e-11e6-9bab-b4dfbb153d37.png)

**Comment by guinux** [comment]
Fixed in V4.2.9 for pamac-manager, I won't fix it for pamac-updater.
