### ISSUE TITLE
Transaction validation window hasn't scrollbar

### ISSUE THREAD

**Issue by Huluti** [manjaro/pamac#204]
The transaction validation window  goes beyond the screen when there is too much information. A scrollbar should be added.

**Comment by guinux** [comment]
Strange because it has one, do you have a screenshot ?

**Comment by Huluti** [comment]
No, I haven't ... It was the first time I've so many informations on the window...

**Comment by Huluti** [comment]
Here's a screenshot from our forum: https://forum.manjaro.org/t/stable-update-2017-02-17-kernels-plasma5-kde-frameworks-apps-libreoffice-mozilla/17792/14?u=huluti

**Comment by guinux** [comment]
Ok, it's the warnings dialog. I will add a scollbar to it.

**Comment by guinux** [comment]
Fixed in V4.2.9
