### ISSUE TITLE
Details in direct package installer looks odd now

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/pamac#208]
@guinux: with the new way only displaying one line in the details view of the direct package installer text scrolling looks odd. It was better to display more than one line at once, even when the window enlarges itself.

**Comment by guinux** [comment]
I don't see what is the difference now, do you have a screenshot?

**Comment by philmmanjaro** [comment]
The difference is now, that it shows only one line in the terminal details view. With stable version we had displayed at least 5 rows or so.
