### ISSUE TITLE
Remove all packages that depend on the target package.

### ISSUE THREAD

**Issue by notramo** [manjaro/pamac#213]
That would be good if there was an option for remove all target packages, as well as all packages that depend on one or more target packages. This would be equivalent to pacman's '--cascade' option. 
I replaced the mate group with mate-gtk3 on my system. This was easy with pacman --cascade, but I couldn't found any option to it in Pamac.

**Comment by guinux** [comment]
This option is enabled by default in pamac. When you want to remove a package, you can see all the packages that depend one it (that must be removed also) in the transaction summary.
