### ISSUE TITLE
Pamac v4.3 crashes on Gnome 3.20

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/pamac#218]
A [user just posted a crash](https://forum.manjaro.org/t/pamac-v4-3-crash-testing-branch/18883) of **pamac** in combination of **Gnome v3.20**:
```
Gtk-Message: Failed to load module "$GTK3_MODULES"
pamac-manager: symbol lookup error: /usr/lib/libpamac.so: undefined symbol: gtk_scrolled_window_set_propagate_natural_height
```
Can't reproduce it on my XFCE installation.

**Comment by guinux** [comment]
Yes, this function was introduced in gtk 3.22

2017-03-06 7:02 GMT+01:00 Philip Müller <notifications@github.com>:

**Comment by philmmanjaro** [comment]
Ok, I've highered now the minimum requirements in our PKGBUILD.
