### ISSUE TITLE
AUR routine finds double targets in cache

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/pamac#219]
Seems with the new AUR routine **pacman -U** [finds double targets](https://forum.manjaro.org/t/testing-update-2017-03-05-msm-calamares-kdeveloper-mesa/18844/2) in cache. Maybe we should put the AUR packages in a different cache/tmp folder and move them only after installation to pacman cache ...

<img src="https://forum.manjaro.org/uploads/default/optimized/2X/1/18f4f15b84f6a24b77167a908270cc9b4c259b72_1_690x464.png">

**Comment by guinux** [comment]
fixed in 9ac8dc8
