### ISSUE TITLE
No sudo pwd caching before build

### ISSUE THREAD

**Issue by seafox** [manjaro/pamac#220]
Looks like (at least with pamac-aur 4.2.11-1) sudo pwd is still not asked and cached prior to starting installation of AUR packages... That is _huge_ usability issue, one single reason the **pacaur helper outshines** all the current pamac efforts, even it's pure console tool. Additionally, it makes futher pamac automation like executing a custom script/command after successful installation impossible...

**Comment by guinux** [comment]
The password is asking at least before installing the package (after the
build). It may be not asked only because it was previously asked by another
task in the same pamac session.

2017-03-06 9:57 GMT+01:00 seafox <notifications@github.com>:

**Comment by seafox** [comment]
Exactly. So the question is can it be cached the pacaur way to have the usability benefits on prolonged workouts?
