### ISSUE TITLE
Can't build Signal

### ISSUE THREAD

**Issue by seafox** [manjaro/pamac#221]
Looks like (at least with pamac-aur 4.2.11-1) there is a problem with building `signal` desktop from AUR, while pacaur does the job lightly! That's just an example and it's probably just a consequence of more serious issue with the current implementation somewhere.

**Comment by guinux** [comment]
I have no problem to build signal, what is your error ?

**Comment by seafox** [comment]
![image](https://cloud.githubusercontent.com/assets/9025690/23631424/1b5df764-02c7-11e7-904c-2acee0df60c4.png)

**Comment by guinux** [comment]
This seems to have nothing to do with pamac, check if your nwjs-bin is up-to-date.

**Comment by seafox** [comment]
Sure it is:
$ pacaur -Qi nwjs-bin 
Name            : nwjs-bin
Version         : 0.20.3-1

**Comment by guinux** [comment]
Does building signal 0.32 fail ?

**Comment by seafox** [comment]
Yes, it does [Arch Plasma pamac-aur 4.3.0-1]
![image](https://cloud.githubusercontent.com/assets/9025690/23790236/f6d25314-0586-11e7-9e57-d2eb63cc47fc.png)

**Comment by guinux** [comment]
So if you say the build fails with pamac but works with pacaur I must admit I have no explanation.
For sure the build function of this package is special but it's handle by makepkg so it should behave the same with pamac or pacaur.

**Comment by seafox** [comment]
I don't know, but something with **pamac** internals is worse than with current **yaourt** or **pacaur** (see pics below accordingly, yaourt finishes with warnigs, pacaur completely in green). Not good at all!
![image](https://cloud.githubusercontent.com/assets/9025690/23826438/b0ce32b0-06a4-11e7-8101-52348d770ca5.png)
![image](https://cloud.githubusercontent.com/assets/9025690/23826460/4f89038a-06a5-11e7-97c1-52c3270159eb.png)

**Comment by seafox** [comment]
pamac-aur 4.3.0-1 still fails to build after updated nwjs-bin 0.21.1-1 and signal 0.33.0-3

![image](https://cloud.githubusercontent.com/assets/9025690/23830681/0f8f2cc2-0719-11e7-9ff9-4a15a46c05b6.png)

**Comment by philmmanjaro** [comment]
**pamac-aur** is depreciated. Please use **pamac**. Latest version is **v4.3.1**.

**Comment by seafox** [comment]
Well, it isn't marked in AUR as depreciated. As I'm on Arch I have no immediately available Manjaro repo just for `pamac`, why that even should be the case?
Are you saying pamac became _excusively_ Manjaro tool?
As I understood the code should work irrespectively of the repositories, be it AUR or Manjaro, am I wrong on that assumption? Does 4.3.1 fixes the `signal` building problem described above up to v4.3.0 incl.?

**Comment by guinux** [comment]
No you're right. Pamac works with Arch as well as with Manjaro. Pamac-aur is the name of the package in AUR. I don't think v4.3.1 will fix this issue.

**Comment by guinux** [comment]
It seems the problem is related to a text encoding error.
@seafox: It's maybe a locale environment variable which is not caught the same way by pacaur, yaourt and pamac on your system.

**Comment by seafox** [comment]
@guinux Which one var? What vars pamac relies on?

**Comment by guinux** [comment]
It's not related to pamac but to makepkg.
I made tests and I discover that trying to manually build signal with "LC_ALL=C makepkg" fails as pamac.
So the error is between the signal code and your locale setting. Can you run "locale" in a term and give the output?

**Comment by seafox** [comment]
LC_ALL=en_US.UTF-8 (from $ locale)

**Comment by seafox** [comment]
just great, now 4.3.1.-1 is infinite loop with the routine system update:

![image](https://cloud.githubusercontent.com/assets/9025690/23996623/c203ad02-0a56-11e7-8208-3f856ef6786e.png)

**Comment by guinux** [comment]
Repos updates was succesful, only aur update(s) left undone. If this aur update was not signal, please open another issue with the aur updates names.

**Comment by seafox** [comment]
He-he, looks like the next in queue after qt5-webengine was pamac-trayindicator:

![image](https://cloud.githubusercontent.com/assets/9025690/24020368/88c6146e-0aa4-11e7-8603-71fb85ea9b33.png)

**Comment by guinux** [comment]
Of course it's not normal.
I found that it's a conflict with the running pamac tray icon when there are repos and AUR updates, it has nothing to do with which packages are outdated.
I have will fix that.

**Comment by guinux** [comment]
For the signal problem, I make many tests in both Manjaro and Arch systems and I can't reproduce the fail you have in building signal.

**Comment by seafox** [comment]
OK, I'll close as this works on another Arch machine. Still exact the same error on v38-1
