### ISSUE TITLE
AUR Install not fully automated

### ISSUE THREAD

**Issue by Wolfereign** [manjaro/pamac#222]
- When installing packages from AUR you do not get prompted for your password when you start the installation.  Instead you have to wait in the details screen to type it in the terminal.
- When installing AUR packages that have never been built on the system before the detail screen/terminal opens the build script (this happens right before it prompt for sudo password) and then completely stops.  You have to manually quit out of vi (:q) in order for the process to continue. I noticed this when installing google chrome, lxd, and sublime text dev from the AUR

Pamac has been great with the exception of these two issues. For a GUI application all user action should only be at the very beginning when clicking apply unless there is an error.

**Comment by Wolfereign** [comment]
When you run pacaur or yaourt manually it asks if you want to view the scripts and the build file. if you say yes it opens those files in vi. Pamac is saying yes to those prompts which interrupts the installation process. The weird thing is that this only happens to new packages from the AUR and not ones you uninstall and reinstall from your system. Hope that makes more sense.

**Comment by philmmanjaro** [comment]
@Wolfereign: which exact version of **pamac** you're talking about? **v4.2** used **yaourt** and with **v4.3** we are using our internal function. Is it the later you're claiming?

**Comment by Wolfereign** [comment]
Ah i was using the wrong version in the AUR (pamac-pacaur 4.2.0-1 https://aur.archlinux.org/packages/pamac-pacaur/). Switched to pamac-aur 4.3.0-1 (https://aur.archlinux.org/packages/pamac-aur/) and that resolved my second issue. 

The password inconsistency mentioned in the first post still exists.

**Comment by philmmanjaro** [comment]
For **yaourt** you can set it in the config not to get prompted for editing the files.

**Comment by Wolfereign** [comment]
I did some more testing with version 4.3 under manjaro and it has fixed the terminal password request as well. Sorry for the ticket on a old version.
