### ISSUE TITLE
[Behaviour Query] Multiple AUR Package Install

### ISSUE THREAD

**Issue by pantar85** [manjaro/pamac#223]
Hey, thanks for work, excellent program.

just a quick query.

installing multiple packages from aur.

i will be asked for root password seperatly for each time pamac installs an aur package. (if root pw is needed)

is this intended behaviour?

the behaviour im expecting is to select  the apps i want to install then enter the password once, then it goes to work. not once for each aur install.

**Comment by philmmanjaro** [comment]
Do you claim this behaviour for **v4.3** release?
