### ISSUE TITLE
[Usability Request] Intuitive modes switching and tray menu changes

### ISSUE THREAD

**Issue by seafox** [manjaro/pamac#226]
Now tray icon menu has only 3 items: run Update Manager | Package Manager | Quit. Also, you can't have both managers open at the same time. Moreover, you have no intuitive and friendly way to switch between the two modes. So the 2 suggestions here:
    a). Make tray menu items as Show Manager (should be default of left click) | Refresh Databases | Quit
    b). Within the apps main window big and easy button with dynamic caption stating Updates | Packages, depending on the current state of pamac main app view mode. Sure, the switch button should be disabled when either no updates avail (in Packages mode) or updates are in process (in Updates mode).

**Comment by tabepic** [comment]
I think this is somewhat invalidated since version 5 combined the two managers.

**Comment by guinux** [comment]
Yes
