### ISSUE TITLE
[Bug] Random hangs when updating

### ISSUE THREAD

**Issue by fyvfy** [manjaro/pamac#233]
Steps to reproduce:
1. Click "Apply" button in pamac update manager. Pamac begin doing usual magic.
2. Sometimes it hangs at "Preparing..." and moving progressbar forever.
latest example:
![pamac01](https://cloud.githubusercontent.com/assets/16356502/24311494/7b6ec0ee-10e5-11e7-83f9-98b164ba82fe.png)
and "details" page:
![pamac02](https://cloud.githubusercontent.com/assets/16356502/24311572/d2a59d38-10e5-11e7-96cd-5b5eed8ce49e.png)

Some info:
* I don't know the exact time when i first met this bug. I think it was after the New Year.
* This happens when there are updates from official arch repositories **and** from AUR.
* I can close update manager, open it again and restart update - this time it completes successfully (because packages from official repos was installed before hang and there are only AUR updates)
* Arch, Cinnamon. Don't know about other DEs.

**Comment by guinux** [comment]
fixed in v4.3.3
