### ISSUE TITLE
Translation error German

### ISSUE THREAD

**Issue by amilopowers** [manjaro/pamac#234]
Pacman says in German: "Aufrischen von Antergos" but it should be "Auffrischen von Antergos" (the word "auffrischen" has two f.

I couldn't figure out how to fix it myself on transifex. That's why I post this here.

**Comment by amilopowers** [comment]
Ah yes that's the "updating antergos" string.

**Comment by philmmanjaro** [comment]
06fdcdc7bd792ba865591bd9174d285f79ba79ff

**Comment by amilopowers** [comment]
You are welcome.
