### ISSUE TITLE
Request libappindicator-gtk3 support for StatusNotifierItem (KDE5, Pantheon, Enlightenment, Unity). (pamac-tray)

### ISSUE THREAD

**Issue by anexation** [manjaro/pamac#24]
Example's can be found at the Firefox and Thunderbid FireTray project

https://github.com/foudfou/FireTray

**Comment by manjaro** [comment]
I will look into it when I'm home:
<pre>git fetch https://codereview.qt-project.org/qt/qtbase refs/changes/80/103280/4 && git format-patch -1 --stdout FETCH_HEAD</pre>

**Comment by lestcape** [comment]
Also the indicators could be supported in cinnamon : https://github.com/linuxmint/Cinnamon/pull/4298

**Comment by guinux** [comment]
implemented in a405052
