### ISSUE TITLE
Invalid or corrupted package 

### ISSUE THREAD

**Issue by polarathene** [manjaro/pamac#240]
Updated the manjaro package that then provides all the new package updates to apply. I press the `Apply1 button and get a `Failed to prepare transaction` dialog window with text content `Invalid or corrupted package`. I'm guessing that message is output from pacman? Is there a way to identify the package(s) or at least improve UX by suggesting(or via a button to trigger a script) what the user can do to handle this error?

A casual user may be frustrated why they cannot update and how to figure out to resolve it. There is plenty of google results and some terminal commands one can try, though all I had to do was exit pamac process(just killed it via systray) and then run a new instance of the updater and it was happy this time around..

**Comment by guinux** [comment]
You're right the message is not explicit. I will improve it. Anyway you always have detailed output on details terminal.

**Comment by guinux** [comment]
Fixed
