### ISSUE TITLE
request for temporary workaround: StartupNotify=false

### ISSUE THREAD

**Issue by oberon2007** [manjaro/pamac#242]
Currently the Manjaro-Deepin like other Arch-based editions face the problem that apparently **pamac**'s ``startup notification completed`` is not being respected because the application doesn't actually open an independent window as described in more detail [here](https://github.com/linuxdeepin/developer-center/issues/250)
If there's no immediate need for **pamac** to use ``StartupNotify=true``, would it maybe be an option for you to temporarily change the line in **pamac-tray.desktop**?
Like this I would be able to finally release **Manjaro-Deepin 17.0.1** without this quite annoying bug.
Thanks a lot
@philmmanjaro @guinux

**Comment by joksik** [comment]
maybe octopi also because there also is the same bug

**Comment by oberon2007** [comment]
Thanks a lot!

**Comment by oberon2007** [comment]
@philmmanjaro in order to get this fix packages and preferrably to stable branch quickly for Deepin, what's the best procedure? Would you like to release a new version or do we patch **v4.3.3** I don't know if there might be any conserns about other changes since the release... ...

**Comment by philmmanjaro** [comment]
I think you figured that one out already by your own :smile:

**Comment by oberon2007** [comment]
Yeah, only I just realize that **pamac-tray.desktop** is not even included in the **pamac** package :stuck_out_tongue_closed_eyes: So is **pamac-manager.desktop** we need to edit??

**Comment by oberon2007** [comment]
Ah. Forget that! It's in /etc/xdg/autostart of course ... :wink:
