### ISSUE TITLE
Wrong translation for Korean

### ISSUE THREAD

**Issue by ideaman924** [manjaro/pamac#245]
When I finish updating my system, this comes up:
"당신의 시스템은 너무 오래되었습니다." (Korean)
In English, this means "Your system is too old."

What I think you guys meant to say was:
"당신의 시스템은 최신 상태입니다."
"Your system is up-to-date."

**Comment by philmmanjaro** [comment]
**Korean** is not yet fully translated. Maybe you wanna [help](https://www.transifex.com/manjarolinux/manjaro-pamac/language/ko/).
