### ISSUE TITLE
pamac breaks db.lck for all tools that are not pacman

### ISSUE THREAD

**Issue by pdf** [manjaro/pamac#246]
pamac appears to make the presumption that pacman is the only other valid package management tool, and explicitly [checks](https://github.com/manjaro/pamac/blob/e7a162e9c0a13e965090066127060cd286c2e891/src/daemon.vala#L229) whether pacman is running before arbitrarily deleting db.lck when found to already exist, essentially pulling the lock out from under applications that think they own it.  This results interruption of operation for other tools, with messages like:
```
warning: lock file missing /var/lib/pacman/db.lck
```

Instead pamac should always try to open the file with `O_EXCL`, and use the return value to determine whether _any_ application holds an exclusive handle on the file.  I presume Glib has a more sane file open operation than `new_for_path` that will support this.

EDIT: Looks like you might have to move to [Posix.open](https://valadoc.org/posix/Posix.open.html) to make it work correctly.

**Comment by guinux** [comment]
With what tool do you experienced this error ?

**Comment by pdf** [comment]
pacaur, as an example, but it will affect anything that doesn't spawn a process called `pacman`

**Comment by guinux** [comment]
I need more details because pacaur (and all other tools I know) spawn a process called `pacman`

**Comment by pdf** [comment]
Try powerpill then - it looks like I've got pacaur delegated to use that instead of pacman (I had forgotten).

Was my original description clear enough about what the issue is?  Even if many tools do shell out to pacman, they absolutely don't have to (take pamac, as an example), and the way pamac is handling this is clearly a huge hack.  You simply can't just go around deleting lock files you don't own without checking whether they're locked - that's how things get really broken.

I don't have experience or a dev environment for writing vala or I'd fix it myself in a PR, but fixing this is really just a matter of deleting a bunch of unnecessary code and replacing the lockfile open calls with a method that supports passing O_EXCL.

**Comment by guinux** [comment]
Firtst know that for standard operations the lock file is handled by alpm so it's safe.
For the beginner, I add a function to erase a no more need lock file in the rare something went wrong with pacman, pamac or any other tool.
I naively thought pamac was the only tool which doesn't call pacman but in fact powerpill does.
I have to fix that.

**Comment by pdf** [comment]
No problem - I can understand the reasoning, and you can still kill a dangling lock if you find one, just needs to be opened in the right way to make sure that it's really not in use.

**Comment by guinux** [comment]
With  fa9670a now pamac removes the lockfile only if it's older than the boot time so I think it's safe now :)

**Comment by pdf** [comment]
That's probably safe enough, if a little unorthodox.

**Comment by mr-blobbyyy** [comment]
Um...unintended consequence after a reboot? 😕 

> $ sudo pacman -Syyu
> :: Synchronizing package databases...
> error: failed to update antergos (unable to lock database)
> error: failed to update core (unable to lock database)
> error: failed to update extra (unable to lock database)
> error: failed to update community (unable to lock database)
> error: failed to update multilib (unable to lock database)
> error: failed to synchronize any databases
> error: failed to init transaction (unable to lock database)
> error: could not lock database: File exists
>   if you're sure a package manager is not already
>   running, you can remove /var/lib/pacman/db.lck

`pamac-daemon` is still running under root. Advice?

**Comment by killajoe** [comment]
https://picload.org/image/riradopi/pamac-daemon.png

**Comment by guinux** [comment]
Pamac auto syncs databases at session startup. Maybe the operation is not yet finished when you try ti run pacman.

**Comment by mr-blobbyyy** [comment]
> Pamac auto syncs databases at session startup. Maybe the operation is not yet finished when you try ti run pacman.

Possibly for me, the first thing I do is connect via vpn but I think I waited at least a few minutes after connecting before doing a pacman update manually. It might be hanging for some reason on my end.

**Comment by pdf** [comment]
@guinux is it possible that pamac will create the lockfile, but doesn't clean up after itself in some scenarios?  I believe earlier today I closed it while it was refreshing, and now I have a dangling lock:

```
$ stat /var/lib/pacman/db.lck 
  File: /var/lib/pacman/db.lck
  Size: 0               Blocks: 0          IO Block: 4096   regular empty file
Device: 805h/2053d      Inode: 524525      Links: 1
Access: (0000/----------)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2017-05-23 12:49:46.866635928 +1000
Modify: 2017-05-23 12:49:46.866635928 +1000
Change: 2017-05-23 12:49:46.866635928 +1000
 Birth: -
$ lsof /var/lib/pacman/db.lck
$ fuser /var/lib/pacman/db.lck
$ uptime
 13:56:32 up 11 days, 17:59,  3 users,  load average: 0.18, 0.26, 0.21
$ ps wwuax |egrep '(pamac|pacman|pacaur|powerpill)'
user     29841  0.0  0.1 461584 30648 ?        Sl   May21   1:16 /usr/bin/pamac-tray-appindicator
```

**Comment by mr-blobbyyy** [comment]
my hunch would be another mesa issue...pamac starts and then chokes on the tray icon.

**Comment by philmmanjaro** [comment]
Was https://github.com/manjaro/pamac/commit/f772be911c9814ece22a1a0d1710f8e6e12adcdc applied?

**Comment by guinux** [comment]
v4.3.6 should fix it
