### ISSUE TITLE
Pamac has removed dependencies of another package

### ISSUE THREAD

**Issue by cawa-93** [manjaro/pamac#247]
https://bbs.archlinux.org/viewtopic.php?id=225652

Could you clarify the question:
1. Why did the pamak remove the dependencies of another package?
2. How do I configure the pamak so that it does not delete dependencies belonging to another package?

**Comment by philmmanjaro** [comment]
Check your settings if you have somehow enabled to uninstall unneeded dependencies ...

**Comment by Strit** [comment]
Plus. Those dependencies was marked as optional. So the package does not need them, but they could provide extra features.

As far as I know, Pamac removes all dependencies that are not specificly needed by other packages when you have the "remove unneeded dependencies" enabled.

**Comment by cawa-93** [comment]
I have a question.
Suppose I have a `Package1`. It has an optional dependency `Package2`, and `Package2` has been installed.

Then I install the `Package3`. Which necessarily depends on the `Package2`.
And delete the `Package3`.

How in this situation will pamac behave with `Packet2`? Will it be marked for deletion, since it is not mandatory for `Package1`?

**Comment by Strit** [comment]
Yes. It would be deleted by Pamac, unless you mark it as explicitly installed, since it is no longer required by any package. But only if you enabled the "remove unneeded dependencies".

**Comment by guinux** [comment]
I close it because an answer is given and this behaviour is due to alpm not pamac.
