### ISSUE TITLE
won't install AUR packages without Manjaro packages

### ISSUE THREAD

**Issue by nhazadian** [manjaro/pamac#249]
Start with the assumption that some Manjaro, and some AUR, package updates are pending.  If the Manjaro packages are all unchecked before hitting Apply, then the AUR packages will not be installed.  A warning pops up listing the unchecked Manjaro packages.  After this is closed, nothing happens, and there is no explanation.  All checked packages should be installed, even if there happen to be none from Manjaro.

**Comment by polarathene** [comment]
Duplicate issue of https://github.com/manjaro/pamac/issues/236

**Comment by guinux** [comment]
Fixed
