### ISSUE TITLE
Does not prompt to edit build file (PKGBUILD)

### ISSUE THREAD

**Issue by siment** [manjaro/pamac#251]
Hi,

I am not experienced with Pamac so I am not confident that this is the right channel to post this on, or if this is even a bug.

The issue is that Pamac does not prompt to edit PKGBUILD file anymore. I do not have `NoConfirmBuild` enabled in `/etc/pamac.conf`.

Using `yaourt $packageName` directly correctly prompts me to edit PKGBUILD file. Am I missing something here?

I am using Pamac 4.3.4.

**Comment by polarathene** [comment]
Duplicate issue of https://github.com/manjaro/pamac/issues/229
