### ISSUE TITLE
Why is the mirror setting removed from pamac?

### ISSUE THREAD

**Issue by JulianLai** [manjaro/pamac#258]

**Comment by philmmanjaro** [comment]
Be more specific on which OS you're using **Pamac** and describe your issue in more detail.

**Comment by JulianLai** [comment]
OS: antergos
I remembered that I could refresh the mirrorlist to get a faster mirror with pamac, but I can't do it anymore.

**Comment by guinux** [comment]
Now pamac checks for pacman-mirrors package to show the mirrors settings.
This package is specific to Manjaro.

**Comment by JulianLai** [comment]
That is a bad news...

**Comment by philmmanjaro** [comment]
**pacman-mirrors** is a specific package only working for Manjaro. It replaces the mirrorlist completely. However we may think about adding the old feature back for pure Arch-based distros by adding a compile switch.

**Comment by philmmanjaro** [comment]
Archbased distros should revert https://github.com/manjaro/pamac/commit/7c2aa35931cf91eb3a7df29f60c565722ff2d130 to have the function working again.

**Comment by philmmanjaro** [comment]
@guinux: can you check my current code changes in master. I'm currently getting compile errors in regard of Transaction. Seems my vala knowledge is a little rusty ;)

**Comment by philmmanjaro** [comment]
@JulianLai: try if following [patch](https://github.com/manjaro/pamac/compare/v4.3.6...6d3a9d4.patch) might work on top of **v4.3.6** for you ...
@guinux: maybe you can optimize my work :smile:

**Comment by guinux** [comment]
There is no official way to automatically filter mirrors by country and/or rank them in ArchLinux.
The mirror setting was present in pamac but it was an error, in Archlinux it did nothing except refresh your current databases.
There no reason to make the tab appears in Archlinux except if we add support for another tool like reflector.

**Comment by JulianLai** [comment]
@guinux `if we add support for another tool like reflector`
It sounds like a good idea!
