### ISSUE TITLE
 Pamac fails to parse min and max version in depends

### ISSUE THREAD

**Issue by Photon89** [manjaro/pamac#263]
I stumbled upon the following problem: perl-gtk2-notify has been updated and the maintainer has introduced version checks for the perl dependency: https://aur.archlinux.org/cgit/aur.git/commit/?h=perl-gtk2-notify&id=f8313183f7ba16d058a7d8457f6c5233d370ed93 I ran the update with yaourt and everything worked out fine, but the Pamac AUR implementation fails with

`Unable to satisfy dependency: perl<`

**Comment by guinux** [comment]
The package is now updated to v0.05-19 without those weird depends.
