### ISSUE TITLE
package installer doesnt work

### ISSUE THREAD

**Issue by davidbepo** [manjaro/pamac#267]
when i open a downloaded package sometimes the installer doesnt load and when it does
![captura de pantalla de 2017-07-30 00-39-31](https://user-images.githubusercontent.com/18667173/28749206-bf2ec3cc-74bf-11e7-9660-21e0ecf6e4e8.png)
and stays like that forever
also no close button

**Comment by philmmanjaro** [comment]
Did pressed **details** to see what is going on?

**Comment by philmmanjaro** [comment]
@guinux: seems **pamac-install** somehow stuck at preparations for ages with **v4.9.0** release. Can you check it once?

**Comment by davidbepo** [comment]
yes i pressed details
![captura de pantalla de 2017-07-30 15-49-06](https://user-images.githubusercontent.com/18667173/28754070-a7ad2b56-753e-11e7-9b6f-fb1376d742c1.png)
it says the same

**Comment by davidbepo** [comment]
verified fiexed in 4.9.1, thanks
