### ISSUE TITLE
pamac not showing most updated version of package

### ISSUE THREAD

**Issue by luzpaz** [manjaro/pamac#268]
I'm installing GitKraken from AUR 
The version on AUR is 2.7.0-2
![image](https://user-images.githubusercontent.com/4140247/28824814-d4feb080-7691-11e7-8ec0-48246ba87994.png)

yaourt also shows 2.7.0-2
```
$ yaourt gitkraken
1 aur/gitkraken 2.7.0-2 [installed: 2.7.0-1] (159) (9.96)
    The intuitive, fast, and beautiful cross-platform Git client.
==> Enter n° of packages to be installed (ex: 1 2 3 or 1-3)
```
I've refreshed the databases of pamac but it still shows 2.7.0-1
Any ideas? 
![image](https://user-images.githubusercontent.com/4140247/28824792-c08898f0-7691-11e7-9ac3-4f4f7889b2c6.png)

**Comment by guinux** [comment]
Yes it shows the installed version but the updater should detect the update

**Comment by luzpaz** [comment]
@guinux That's the point that the updater isn't detecting the update. Can you confirm?

**Comment by philmmanjaro** [comment]
@luzpaz: your package is shown as repository package and not one in AUR. Please check also in the AUR tab.

**Comment by luzpaz** [comment]
@philmmanjaro  

AUR tab: 
![image](https://user-images.githubusercontent.com/4140247/28921341-9243c1a2-7823-11e7-945f-6a7442d21f2d.png)

Inside pamac GitKraken page:  
![image](https://user-images.githubusercontent.com/4140247/28921366-b4219d8a-7823-11e7-8c57-9ef639377110.png)

**Comment by luzpaz** [comment]
am i the only one experiencing this issue?

**Comment by luzpaz** [comment]
![image](https://user-images.githubusercontent.com/4140247/29184001-ba57b144-7dd2-11e7-8b4f-c971b853e0a7.png)

**Comment by luzpaz** [comment]
I found the problem. I didn't have `Preferences > AUR > Enable AUR Support > Check for update` checked
![image](https://user-images.githubusercontent.com/4140247/29192598-f99b77ec-7def-11e7-9133-f593f7053f72.png)
That's kind of non-intuitive.

**Comment by lisamccoy** [comment]
AUR support is always disabled by our default graphical package managers.

**Comment by luzpaz** [comment]
IMO that box should be checked by default if someone chooses to search AUR as well. So in other words it would only be enabled if user chooses to also search AUR
