### ISSUE TITLE
Don't Download Files Databases Before Installing Updates

### ISSUE THREAD

**Issue by lots0logs** [manjaro/pamac#272]
Currently Pamac automatically refreshes the databases when you click install updates. Often times refreshing is unnecessary because it was just refreshed prior to showing the available updates. However, I know that depending on the user's settings there will be times when the refresh is necessary. I think it would better if the `*.files` databases for each repo were not downloaded when performing a refresh prior to installing updates. The `*.files` databases are much larger than the normal databases and so it delays the whole process quite a bit.

**Comment by guinux** [comment]
Fixed in v5.1

**Comment by lots0logs** [comment]
@guinux This does not appear to be fixed in 5.1. Its still downloading files databases before installing updates.

**Comment by guinux** [comment]
You're right I had to revert it back to fix some issues. Now files databases are downloaded by pamac-tray in background in /tmp and then copied before being refreshed when installing updates. This way in most cases databases are up-to-date so they are not downloaded before installing updates.
