### ISSUE TITLE
Unable to lock database

### ISSUE THREAD

**Issue by kouros17** [manjaro/pamac#275]
With **pamac-5.0.0-2** I get the known `"unable to lock database"` issue  in every update, even if I try to delete the database lock file with `"sudo rm /var/lib/pacman/db.lck"` command. 
I have to use the terminal to do the updates.

**Comment by Ste74** [comment]
I can confirm , but in my case no action need only ignore the message and wait the rechecking of repo's db , after this pamac work fine..

**Comment by guinux** [comment]
Yes I found that the problem is my last commit. Pamac-5.0.0-1 doesn't have this problem.

**Comment by lots0logs** [comment]
@guinux I think it would make sense to only refresh the files databases on a set schedule instead of doing it every time the repo databases are refreshed. The files databases are not required so its okay if they aren't updated but once or twice a day IMO.

**Comment by philmmanjaro** [comment]
OK, I'll revert that patch now I added to revision 2. Will wait then for a new fix.

**Comment by kouros17** [comment]
With **5.0.0-3** I can do the updates without issues but it seems it returned another issue I had in pamac **4.9**:
Pamac notifier doesn’t change the color to red from white when it has updates.

**Comment by philmmanjaro** [comment]
@kouros17: I assume you didn't reboot your system or restarted the deamon. Seems to be normal when **pamac** got updated that the tray icon doesn't get refreshed as those are now one application.

**Comment by kouros17** [comment]
I have not changed anything on my system.
I am on the unstable branch and I have the opportunity to test it daily. 
Neither the today's updates changed  the colour. 
I have never had this issue only in **4.9** and now in **5.0.0-3**.

**Comment by kouros17** [comment]
In today's updates it worked normally. :)

**Comment by guinux** [comment]
Should be fixed with v5.1.0
