### ISSUE TITLE
pamac doesn't update status of installed packages just after install their as dependencies

### ISSUE THREAD

**Issue by piomiq** [manjaro/pamac#278]
Recently I installed "strigi" (from AUR) and its dependency was "boost". I commit its installation and got installed "strigi". Great. Only I wanted to check if pamac really cleaned not yet necessary dependency and found that boost wasn't checked on list in option: "Search". OK. To be 100% sure I checked this also in octopi. Unfortunately turned out that boost is installed, and just after this check also pamac shown that boost is installed.
It seems that something wasn't refreshed after installation dependencies.

**Comment by guinux** [comment]
should be fixed with 6.0.2
