### ISSUE TITLE
[Feature Request] Pamac tray icon hover update info

### ISSUE THREAD

**Issue by ceyhunnabiyev** [manjaro/pamac#280]
it would be nice to add Pamac tray icon hover update info (how many updates available, how many AUR package updates available and etc.) feature.

**Comment by guinux** [comment]
Pamac tray icon tooltip ( shown when your mouse is on the icon) already gives number of available updates.

**Comment by ceyhunnabiyev** [comment]
In Gnome? I don't see any tooltip on pamac icon.

**Comment by guinux** [comment]
You're right, I tested and gnome doesn't seems to show tooltip but it's a gnome choice.
Know that gnome 3.26 will drop tray icon support (top icon extension would continue to work).

**Comment by ceyhunnabiyev** [comment]
Yes, I have heard about that. Thank you for info..
