### ISSUE TITLE
Mirrorlist and database

### ISSUE THREAD

**Issue by fhdk** [manjaro/pamac#284]
Would it be possible to coordinate so pamac and pacman-mirrors is using the same mirrorlist and database?

It would minimze issues like this one
https://forum.manjaro.org/t/pamac-is-nuts-showing-non-existing-updates-since-days/30713?u=fhdk

**Comment by guinux** [comment]
As I said in the forum thread it's already the case.
"Official Repositories" tab in Pamac is no more than a graphical interface of pacman-mirrors.
