### ISSUE TITLE
I can not move the window with the mouse

### ISSUE THREAD

**Issue by kouros17** [manjaro/pamac#289]
I can not move the window to the desktop with the mouse (pamac 6.0.0-1, gnome-shell)

**Comment by ThanosApostolou** [comment]
I can verify it too in KDE and MATE. Window can be moved by clicking and dragging on some button like "Categories" or even buttons like "minimize", but not on the empty space in between.

**Comment by Huluti** [comment]
@guinux has fixed it in 72259da0b7a5883099877583badaa6c96d9aa5e5 ;)
