### ISSUE TITLE
Pamac strips "+" from package names and finds wrong updates

### ISSUE THREAD

**Issue by cyrylas** [manjaro/pamac#29]
There are aur packages named "mysql-connector-c++" (1.1.5-2) and  "mysql-connector-c" (6.1.5-1).
Install first one.

Now pamac will start informing you about new version of mysql-connector-c, but this package is not even installed.

I think pamac assumes  "mysql-connector-c++" == "mysql-connector-c" and tells about new version, because 6.1.5 > 1.1.5.

**Comment by manjaro** [comment]
This is related to #26 and is already fixed. Please test pamac 2.1.1.
