### ISSUE TITLE
[Feature Request] Please return the ability to double click on a package which triggers the UI to show it's details (instead of this new single click)

### ISSUE THREAD

**Issue by luzpaz** [manjaro/pamac#290]
In pamac <=5.x the UI required a double click to view the package info. In 6.0 simply clicking on the package will trigger this which makes the UI very delicate. It is not always preferable and can be time-consuming and irksome if a package was chosen accidentally. For example, say one to unintentionally clicking on the wrong package, they now need back-out to the main view again by finding that back arrow at the top left of the page. 

Is it possible to add at least the option in the settings ('double mouse click triggers view menu' or something?) to let the user decide this behavior?

**Comment by guinux** [comment]
Yes, maybe it needs some time to be used to this new behaviour.
I changed it because it how new app works now, I will wait for more feedback.
Just know that clicking on version, repo or size doesn't show details.

**Comment by kewlfft** [comment]
related to double click as well and I write it here: double click on pamac tray notifier never returns any result in the window. Single click works fine. It took me some time to understand what was wrong.

**Comment by guinux** [comment]
> the fact the window can't be moved

It's fixed by 72259da

**Comment by kewlfft** [comment]
thanks for the fix I had not see it, great

**Comment by kewlfft** [comment]
what about the double-click on the tray notifier? We should not double click on it or is there something that can be done to avoid this behaviour?

**Comment by guinux** [comment]
Common usage of tray icon is a single click

**Comment by philmmanjaro** [comment]
@guinux: people ask for double-click to show package details. Now it is a left-single click or right-choose-details click. They are used to simply click it once to mark the line and then scroll or do the next step.

**Comment by guinux** [comment]
fixed with e86ac4c
