### ISSUE TITLE
installed apps dont show it's repo in categories tab

### ISSUE THREAD

**Issue by davidbepo** [manjaro/pamac#291]
![captura de pantalla de 2017-09-16 16-44-01](https://user-images.githubusercontent.com/18667173/30513131-4792558a-9afe-11e7-8a1f-21bc9ba03191.png)
however it works in search tab
![captura de pantalla de 2017-09-16 16-45-13](https://user-images.githubusercontent.com/18667173/30513152-7971a3da-9afe-11e7-8a2c-cbeb166a788a.png)
other tabs also work correctly

**Comment by davidbepo** [comment]
offtopic: the new GUI is very cool kudos to the developers :)

**Comment by guinux** [comment]
Well seen !

**Comment by davidbepo** [comment]
fixed in 10 minutes!
this must be some kind of record :)
