### ISSUE TITLE
[Feature Request]  Merge Groups and Repositories tab

### ISSUE THREAD

**Issue by bartkmq** [manjaro/pamac#292]
![screenshot from 2017-09-16 19-13-20](https://user-images.githubusercontent.com/25273823/30514345-2dc573b6-9b13-11e7-9561-e59edd814537.png)
Looking at the screenshot I feel like the top of pamac is getting a bit overcrowded with buttons (even more so if #281 is would be implemented).
It makes sense to merge the Repositories into the left sidebar of the Groups tab to reduce this. Too visual set the repositories core, extra ... apart from the real groups base, base-devel, ... and horizontal spacer could be used.

Later on, snap and flatpak groups could be added to the sidebar of the groups tab in the same way.

**Comment by kewlfft** [comment]
I agree what used to be streamlined and simple is getting crowded. Anything that can merge, differenciate or organize buttons would be welcome from my point of view.
