### ISSUE TITLE
 [Feature Request] Add more columns and column management

### ISSUE THREAD

**Issue by bartkmq** [manjaro/pamac#295]
1) Some columns that would be useful are:
- Build date
- License
- UI-Toolkit [gtk2, gtk3, qt, electron, ncurses, ..., none] and UI-type [GUI, TUI, CLI]
 -> useful if you're looking for a GUI but your query return to many python-* or <package>-i18n-* entries
 -> could be heuristically calculated based on package requirements
 -> if that's too complicated or error-prone instead just use [yes, no]
- Install Reason 
2) Make it possible to hide/show columns in the right click menu of the columns.

**Comment by guinux** [comment]
More columns would make the view too complicated, there is the details view for all infos.
