### ISSUE TITLE
Location of install, remove, reinstall buttons 

### ISSUE THREAD

**Issue by ceyhunnabiyev** [manjaro/pamac#300]
I think, Location of install, remove, reinstall buttons  was better in old versions (on the top-right side). Placing between other items is not user-friendly and doesn't look cool, because they are urgent buttons, have to be separately viewed:

![screenshot-20170917130243-753x359](https://user-images.githubusercontent.com/5506156/30519792-9c0ae3a0-9baf-11e7-8f59-08e7e1cc74cc.png)

**Comment by guinux** [comment]
I must admit that with your theme, buttons are not well visible. With other themes, buttons have borders which makes them more visible.

**Comment by ceyhunnabiyev** [comment]
@guinux , That is popular Adapta theme, it would be nice to locate buttons on  top-right side, I think. Every theme has own style.

**Comment by philmmanjaro** [comment]
We have to check that, since with the upcoming **v17.1** release we use that theme.

**Comment by guinux** [comment]
fixed with 42e151a
