### ISSUE TITLE
Pamac 6.0.1-1 Preferences > Cache > Number of versions of each package to keep in cache, can't be changed

### ISSUE THREAD

**Issue by T-W-S** [manjaro/pamac#306]
Thanks for all your work.

It seems that I am not able to change the “Number of versions of each package to keep in cache”.
I’ve tried to change it to 2, closed the window and when I reopen it it’s back to 3, the same applies when I go up e.g. to 4 it falls back to 3 when I revisit it.

Thanks.

**Comment by kouros17** [comment]
I confirm it.

**Comment by davidbepo** [comment]
this also happens on previous versions

**Comment by guinux** [comment]
fixed
