### ISSUE TITLE
Default window size of Pamac won't work on netbooks

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/pamac#307]
User banjo reported the following:

Pamac v6.0.1 GUI resolution is too big for my netbook. With Adwaita-theme I can’t even see the maximize button.

**Comment by guinux** [comment]
What's his screen resolution ?

**Comment by philmmanjaro** [comment]
1024x600 or 1366 x 768 is common. Having 800 x 480 would be odd and only used on 32bit machines.

**Comment by banjojo** [comment]
It's a standard 10" netbook having 1024 x 600.

**Comment by darcn181** [comment]
I have that problem too, my netbook has a 1024x600 resolution and i use sometimes my external monitor which is 1366x768, in the external monitor its ok but in the netbooks monitor i cant even see the settings icons, the previous versions of pamac worked well with the netbooks resolution at the point that i could maximize the window.
![captura de pantalla_2017-09-21_18-30-00](https://user-images.githubusercontent.com/28988467/30721795-bc9fe652-9efb-11e7-8e1c-44609f91e63e.png)

**Comment by guinux** [comment]
fixed with 9d138d0
