### ISSUE TITLE
Cannot click in package list

### ISSUE THREAD

**Issue by kozec** [manjaro/pamac#308]
Pamac v6.0.1-1 on fully-updated Manjaro.

Clicking anywhere instantly shows information about clicked package, making it impossible to give package list focus and use keyboard for navigation.

**Comment by guinux** [comment]
If you click on version, repo or size you can select the package.

**Comment by kozec** [comment]
That's rather clunky, especially on small laptop where those columns are not even visible (in fact, entire right part of window is offscreen...)

What's the point of such surprising behavior?

**Comment by guinux** [comment]
What's your screen resolution ?

**Comment by kozec** [comment]
1920x1080. But nevermind screen size, I can't really imagine why should _clicking_ on list just take me somewhere else without ant prior indication. Is this behavior indented? Why?

**Comment by philmmanjaro** [comment]
So you expect to double-click in a list if there is an option?

**Comment by philmmanjaro** [comment]
Same as request: https://github.com/manjaro/pamac/issues/290

**Comment by philmmanjaro** [comment]
Clicking on version, repo or size doesn't show details.

**Comment by guinux** [comment]
fixed with e86ac4c

**Comment by kozec** [comment]
Thank you very much :)
