### ISSUE TITLE
AUR update overrides official repository update

### ISSUE THREAD

**Issue by Bleuzen** [manjaro/pamac#310]
Hi, I'm using Pamac 6.0.1-1 on KDE with enabled AUR support and I get an update displayed: dropbox
Dropbox is in the manjaro repos, so I don't want to install the AUR version.
But Pamac displays it as update, because the version in the AUR is newer than the version in the manjaro repos.

It should hold back updates from the AUR, if there are official packages from manjaro in my opinion..

**Comment by philmmanjaro** [comment]
Hmm, I thought we used our binary files if available on our end and skip AUR. @guinux ?!?

**Comment by guinux** [comment]
No it's true, if an AUR update is newer it will be proposed but I can disable this if you want.

**Comment by philmmanjaro** [comment]
Make it an AUR option and disable it by default.

**Comment by guinux** [comment]
fixed pamac doesn't propose update from AUR is package is in repos
