### ISSUE TITLE
Broken tray icon in Gnome Shell

### ISSUE THREAD

**Issue by prescott66** [manjaro/pamac#314]
As you can see on screenshot, icon is broken in Gnome Shell 3.24.2
Pamac version: 6.0.2-1

![screenshot](https://user-images.githubusercontent.com/735265/30786420-7c15ae10-a175-11e7-9fe5-9b7f7a792005.png)

**Comment by Th3Z0ne** [comment]
That more seems like a problem with the extension (top icon plus?) that you are using. Check the icon size in its setting and probably increase it.

**Comment by prescott66** [comment]
I cant...i have reinstalled laest manjaro gnome and there is no pamac icon

**Comment by guinux** [comment]
It's a gnome issue, not a pamac one.
