### ISSUE TITLE
User should not have to wait to see "Transaction Summary" dialog box

### ISSUE THREAD

**Issue by KSXGitHub** [manjaro/pamac#316]
### Current behavior

Currently, when I want to install/upgrade both official packages and AUR packages, pamac would:
  * Show one dialog box asking to commit installing official packages
  * Install/upgrade official packages, **takes time** → _User must wait this process to complete in order to commit AUR installation_
  * Show another dialog box asking to commit building AUR packages →  _After this, user can leave the system does its job_

### Expected behavior

Ideally, user should not have to wait just to click the second "Commit" button. User should be able to commit both groups right after clicking "Apply" → pamac should:
  * Show one dialog box to commit the two groups.
  * Install/upgrade official packages followed by AUR packages → Instead of waiting, user can now leave pamac does its things and do other things.

### Image: A "commit" dialog box

![A "commit" dialog box](https://user-images.githubusercontent.com/11488886/30857630-a767e200-a2e6-11e7-86a9-fe9fdaab0f1d.png)

**Comment by guinux** [comment]
It should be already implemented, you should have only one dialog box.
Do you have an example ?

**Comment by KSXGitHub** [comment]
@guinux Yes, it's only one dialog box now. However, when upgrade packages, the dialog box does not appear instantly because of "refresh" process.

**Comment by guinux** [comment]
Now with 04535a1 it should like this:
 - click on Apply
 - enter the password
- wait for refresh dbs
- one confirmation dialog only if package to install or to build

I can't do better and it's the same behaviour as when using pacman.
