### ISSUE TITLE
Warning dialog boxes should not block packages' installing process

### ISSUE THREAD

**Issue by KSXGitHub** [manjaro/pamac#317]
Occasionally, dialog boxes may show up near the end of installing a group of packages (group is either official packages or AUR packages) just to show warning (e.g. local packages' versions are newer than that of official repos) but *block* the completion of current installing process as well as next installing process.

Since user cannot cancel packages' installing process via warning box, blocking process would make little sense.

### Image: A warning dialog box

![A warning dialog box](https://user-images.githubusercontent.com/11488886/30857816-5c6fc960-a2e7-11e7-82b9-c91f9a955a79.png)

**Comment by guinux** [comment]
Fixed with  dd03f3f
