### ISSUE TITLE
Request user triggered convenience actions

### ISSUE THREAD

**Issue by alexandruianu** [manjaro/pamac#32]
A couple of things that would really make using the gtk Manjaro package management system more convenient prior to the 0.9.0 release would be a remove lock file on demand button (next to the options button on the right), and an action in preferences (official repo tab) to rank mirrors immediately.

**Comment by philmmanjaro** [comment]
See also #6

**Comment by guinux** [comment]
You already can rank mirrors in preferences, what do you mind by immedialtely ?
I'm not for a remove lock file button, it's a dangerous action, I prefer let advanced users do it in a terminal. I also prefer debugging pamac to not have this situation.

**Comment by alexandruianu** [comment]
Immediately means that at the press of a button, "pacman-mirrors -g" runs.
![screenshot_2015-03-04_18-02-01](https://cloud.githubusercontent.com/assets/8630254/6487286/e63e01d4-c298-11e4-94e5-72a58c1f4555.png)

**Comment by guinux** [comment]
fixed in v2.4.0
