### ISSUE TITLE
gksu pamac-manager results in a crash 

### ISSUE THREAD

**Issue by icf20** [manjaro/pamac#325]
```
gksu pamac-manager                                                                                                                                                                              

(pamac-manager:22383): GLib-GIO-CRITICAL **: g_dbus_proxy_new_sync: assertion 'G_IS_DBUS_CONNECTION (connection)' failed
XDG_RUNTIME_DIR (/run/user/1000) is not owned by us (uid 0), but by uid 1000! (This could e g happen if you try to connect to a non-root PulseAudio as a root user, over the native protocol. Don't do that.)

** (pamac-manager:22383): CRITICAL **: file /pkg/src/pamac-6.0.1/src/transaction.vala.c: line 18683: unexpected error: Error al lanzar («spawn») el comando «dbus-launch --autolaunch=a325d24cb33748ab90315c7f23c9176f --binary-syntax --close-stderr»: El proceso hijo terminó con el código 1 (g-spawn-exit-error-quark, 1)

** (pamac-manager:22383): CRITICAL **: pamac_user_daemon_get_repos_names: assertion 'self != NULL' failed

```

hello, here is what i get in the terminal when i try to launch, if i launch with no gksu there is no crash

**Comment by philmmanjaro** [comment]
Why do you want to use **gksu** with it? Not needed. You need **polkit** daemon and client running and it is all OK.

**Comment by icf20** [comment]
> Why do you want to use gksu with it? Not needed. You need polkit daemon and client running and it is all OK.

polkit dialog window fail to show up on bspwm after clicking accept but it show up if is started with gksu from rofi

**Comment by guinux** [comment]
As it has been said before, pamac needs that polkit authentication agent is running. With bspwm it's seems it's not autostarted.
https://wiki.archlinux.org/index.php/Polkit#Authentication_agents
