### ISSUE TITLE
Can't remove items from ignorelist in Pamac.

### ISSUE THREAD

**Issue by jacobcantele** [manjaro/pamac#327]
I accidentally added linux-firmware to my ignorelist. When I click the minus sign in Pamac, I'm unable to delete it. If I add a different package to the ignore list, and then try to remove it, that package gets changed to linux-firmware.

![screenshot from 2017-10-02 11-04-01](https://user-images.githubusercontent.com/10467486/31087717-b2396ef2-a763-11e7-9456-9747320a71af.png)

**Comment by guinux** [comment]
I can't reproduce it. What's your pamac version ?

**Comment by jacobcantele** [comment]
6.0.2-3

**Comment by philmmanjaro** [comment]
**v6.0.3-1** got deployed to all branches by now. Please test.
