### ISSUE TITLE
[Enhancement] Add option to use --noconfirm with yaourt

### ISSUE THREAD

**Issue by lots0logs** [manjaro/pamac#33]
First, let me just say that you guys gave done a really great job with Pamac! :+1:  I would love to see an option added for the use of  `--noconfirm`  when building AUR packages. Should a build attempt fail, the user could then be given the option to try again without `--noconfirm` so they can take care of whatever has caused the failure in the PKGBUILD. What do you guys think about this?

**Comment by rockiger** [comment]
+1

**Comment by smcdougall** [comment]
I think it used to behave this way in a previous version.  I would love to see this feature come back.  It gets a little tedious going N,N,Y on every update when you've got a few queued up.

**Comment by guinux** [comment]
fixed in v2.4.0
