### ISSUE TITLE
[Question] Minimizing to pamac tray icon removed on Gnome Startup?

### ISSUE THREAD

**Issue by ceyhunnabiyev** [manjaro/pamac#332]
I can't see Pamac after Gnome-shell is started.
Gnome-shell - 3.24.3 version

**Comment by guinux** [comment]
You have to use top icon plus extension.

**Comment by ceyhunnabiyev** [comment]
@guinux , top icon plus extension also  doesn't show  tray icon. I manually started pamac, then there is no pamac tray icon. Seems like it doesn't work in Gnome. By the way, I have Gnome 3.24.3 version, not Gnome 3.26 in order to use top icon plus extension. One more I mentioned that top icon plus extension development has been stopped (https://github.com/phocean/TopIcons-plus/issues/91)..

**Comment by Ste74** [comment]
Guys .. @guinux @ceyhunnabiyev .. i have lost this .. ping me for gnome edition 😄  pamac-tray in gnome edition is disable in favour of gnome-shell-extension-update-manjaro . If the extension is installed pamac-tray is disabled ( but the extension use pamac to work ) . I have do this for not redundant application on top panel . If you remove the extension ( de install ) pamac-tray show again 😉

**Comment by ceyhunnabiyev** [comment]
@Ste74 , thanks for info.. I like gnome-shell-extension-update-manjaro, but it doesn't have integration with pamac. It would be nice to add this feature..

**Comment by Ste74** [comment]
A little addition is in work to open pamac with it .. hope release for 17.1 rel 😉
