### ISSUE TITLE
Wrong information and confirmation on updates

### ISSUE THREAD

**Issue by RalphBike** [manjaro/pamac#335]
pamac is behaving weird in regards of user notification and confirmation about updates. 

It shows me one AUR update. I confirm the update. Then Pamac secretly downloads and installs all other Manjaro updates. The only hint is a bigger download size, I do not get any other information on the updates from the manjaro repositories and can not select or confirm them.

Is this not a critical bug but not great in terms of transparency and user-friendliness.

**Comment by philmmanjaro** [comment]
Please see #331 and check if you have the lastest **pamac v6.0.3-3** installed on your end.

**Comment by RalphBike** [comment]
Hi Phil, 
Pamac is on version 6.0.3.3.

At the first glance #331 does not really fit. Pamac DOES find the updates but I am not informed and do not have the chance to confirm the Manjaro updates.

**Comment by philmmanjaro** [comment]
Are you sure? We have two taps when you do upgrades. You simply just viewed the AUR one. Next update, simply switch to the other tab before updating. And yes, pamac normally selects all packages to be updated at once. If you deselect, you simply mark it to be ignored.

**Comment by RalphBike** [comment]
Sure about what? I can tell you what I see and what I confirm. Pamac give me the feeling to confirm one AUR update. The other updates seem to appear "magically". Besides that pamac seems to start downloading the other databases after the confirmation click.

The order seems to be as follows:
1. Start of Pamac. 
2. Pamac loads something
3. Pamac displays an available AUR update
4. I confirm it
5. Pamac synchronizes the 3 manjaro package databases
6. Pamac downloads and installs all manjaro updates
7. Pamac asks me to confirm the build for the AUR update

(I hope I was able to reconstruct this correctly. I am happy to provide more info on the next update.)

**Comment by atiredman** [comment]
Just wanted to mention I saw the same thing RalphBike is mentioning. I got notified of an update, checked pamac saw 1 AUR package update (papirus-icon-theme) however when I clicked update I noticed it was way too large a download and saw it doing a full system update. Pamacs history confirms a full system update was done.  

It is probably as philm said and I was simply on the wrong tab I was not even aware there were two tabs until just now.  I will look more carefully next update but still it seems easy to miss updates like this.

**Comment by philmmanjaro** [comment]
You can check the **pacman.log** file to see what got updated. You can simply test it by downgrading a normal package and one of AUR to see how **pamac** will notify you on both cases simultaneously.

**Comment by guinux** [comment]
Yes it was fixed with #331.
Upgrading to pamac v6.0.3-3 and reboot should fix this bug.

**Comment by RalphBike** [comment]
Sorry guys, I do not find the old versions of that AUR package in the cache :-/

**Comment by guinux** [comment]
So I close it because I think it's fixed. If the problem occurs again with v6.0.4 after a reboot please reopen.

**Comment by RalphBike** [comment]
Just to be sure, which version contains the bugfix: 6.0.4 or 6.0.3.3?

**Comment by philmmanjaro** [comment]
both. **v6.0.3-3** is only on Manjaro. **v6.0.4** is the tagged tarball for Antergos.
