### ISSUE TITLE
New release? [pretty please]

### ISSUE THREAD

**Issue by karasu** [manjaro/pamac#336]
Hi!

Version 6.0.3 is a non functional release. Could you be so kind and release a new version with the latest (@guinux) patches? If not, you're forcing packagers to either package a non functional version or package a version that includes some manually added patches.

(Maybe I'm missing something so correct me if I'm wrong).

Thanks!

**Comment by philmmanjaro** [comment]
I've tagged **v6.0.4** for you.

**Comment by karasu** [comment]
Thanks, that was real quick!

**Comment by philmmanjaro** [comment]
No problem at all @karasu
