### ISSUE TITLE
v6.1.0 Build Fails With Error

### ISSUE THREAD

**Issue by lots0logs** [manjaro/pamac#338]
@guinux 
```sh
error: Argument 1: Cannot pass ref argument to non-reference parameter
				ignorepkgs_liststore.remove (ref iter);
				                             ^^^^^^^^
```

**Comment by cromerc** [comment]
@lots0logs I assume you have vala 0.36? This should be fixed in 0.38.

**Comment by lots0logs** [comment]
Actually I have 0.38 (since that's what's current in Arch repos right now). :thinking:

**Comment by cromerc** [comment]
Hmmm, in manjaro stable it is still at 0.36. I had someone else with the same issue say it had fixed itself after upgrading to 0.38. Guess it was something else that fixed it then. Are you using the new meson build?

**Comment by guinux** [comment]
Duplicate of #235

**Comment by philmmanjaro** [comment]
Seems not to be an issues with Manjaro right now. Current PKGBUILD can be found [here](https://github.com/manjaro/packages-extra/tree/master/pamac).

**Comment by lots0logs** [comment]
@guinux This does appear to be a valid error. `Gtk.ListStore.remove()` does not accept a ref argument: https://valadoc.org/gtk+-3.0/Gtk.ListStore.remove.html

**Comment by philmmanjaro** [comment]
And why does it compile on my end? What if reverting https://github.com/manjaro/pamac/commit/2aaf2f7ecf1aae06e5085a7a7b04e7eedf302137

**Comment by lots0logs** [comment]
If I understand correctly, you guys are using vala 0.36 so I assume that is the reason for the different results.

**Comment by cromerc** [comment]
I am using vala 0.38 and it is working fine for me. I have built pamac on Artix, Cromnix, and Arch Linux without any issues.

**Comment by philmmanjaro** [comment]
I'm also using vala 0.38.2 in **unstable** branch. Had no issues in building it.

**Comment by lots0logs** [comment]
Weird. I'm not sure what the difference could be then. But if I revert  2aaf2f7 it builds fine.

**Comment by lots0logs** [comment]
```
pacman -Qi vala
Name            : vala
Version         : 0.38.2-1
Description     : Compiler for the GObject type system
Architecture    : x86_64
URL             : https://wiki.gnome.org/Projects/Vala
Licenses        : LGPL
Groups          : None
Provides        : valadoc
Depends On      : glib2  gtk-doc  graphviz  libgee  ttf-dejavu  pkg-config  gcc
Optional Deps   : None
Required By     : gnome-builder  valabind
Optional For    : gnome-code-assistance
Conflicts With  : valadoc
Replaces        : valadoc
Installed Size  : 13.97 MiB
Packager        : Jan Alexander Steffens (heftig) <jan.steffens@gmail.com>
Build Date      : Sun 08 Oct 2017 01:19:13 PM CDT
Install Date    : Mon 09 Oct 2017 08:19:38 PM CDT
Install Reason  : Installed as a dependency for another package
Install Script  : No
Validated By    : Signature
```

**Comment by philmmanjaro** [comment]
Really weird. We will see. At least you found a solution for it ...

**Comment by lots0logs** [comment]
If the docs are up-to-date then a ref should not be passed to that function which means this a legit bug.

**Comment by lots0logs** [comment]
This appears to be an issue with my local system environment. It does not occur on our build server. So evidently the vala docs are out-of-date ¯\_(ツ)_/¯
