### ISSUE TITLE
v6.1.0 fails to download

### ISSUE THREAD

**Issue by kleshas** [manjaro/pamac#339]
ERROR: Failure while downloading https://github.com/manjaro/pamac/archive/V6.1.0.tar.gz

I manually tried the URL above, but with a lower case v in the filename and it downloaded fine.  Upper case gave a 404.

**Comment by guinux** [comment]
Where do you find this link?

**Comment by philmmanjaro** [comment]
AUR PKGBUILD needs to be updated. Not yet released anyway.
