### ISSUE TITLE
"Install updates" from notification dont work

### ISSUE THREAD

**Issue by prescott66** [manjaro/pamac#34]
In gnome shell notification with new updates available, after clicking Install updates, nothing is done(pamac window with updates should be opened). Using version 2.2rc1 from antergos repo.

**Comment by philmmanjaro** [comment]
Did you check 2.2rc2 (738df885d84619046cdf033cc93d718b0caabca5) or 2.2rc3 (7c2119566a6d795936a96d3ceaffd81c15a88992) already?

**Comment by prescott66** [comment]
not yet.but that there are only translation updates, or not?

**Comment by philmmanjaro** [comment]
No, they have also code fixes.

**Comment by philmmanjaro** [comment]
Ok, I can confirm that rc3 it doesn't also not work. Seems we have to fix **pamac-tray**.
