### ISSUE TITLE
[Enhancement] Bigger sidebar entries

### ISSUE THREAD

**Issue by KSXGitHub** [manjaro/pamac#342]
I've just update to pamac 6.1.1 recently and notice that the top tabs are moved to sidebar and *I like it*. However, the entries are too small, they should be at least as big as their sub-entries (or as big as gnome-control-center's sidebar entries)

### A comparison of the two sidebars

![image](https://user-images.githubusercontent.com/11488886/31604624-1ce4cac8-b28e-11e7-9638-c56e3a6ec1de.png)

**Comment by hogar1977** [comment]
Agreed, and they shouldn't hide or go away as they do now, forcing you to make a 'Back' action to pick another category... It should be in line with Gnome desktop settings, preferably with icons for categories to maintain the same look...

**Comment by KSXGitHub** [comment]
@hogar1977 Hmm, GNOME Settings 3.26 does force you to click the 'Back' button to go back to parent menu.

![image](https://user-images.githubusercontent.com/11488886/31773691-b1c02990-b50d-11e7-999f-05dd94fba97e.png)

![image](https://user-images.githubusercontent.com/11488886/31773717-c4dc3aaa-b50d-11e7-8d94-2537db375fab.png)

**Comment by guinux** [comment]
fixed in v6.2.0
