### ISSUE TITLE
[Problem] Buttoms missing

### ISSUE THREAD

**Issue by yiping-huang** [manjaro/pamac#343]
![Image](https://i.imgur.com/mRkJwLK.png)
Some buttoms in the top row are missing.

OS: Arch, Openbox with some goodies from XFCE and LXDE.
Theme: 0nyX. I have tried other themes, same result.

Tell me what else I need to provide.

Edit:
Sorry, I suddenly realize that this is the new layout in 6.1.1.
It just look like it has been broken.

**Comment by philmmanjaro** [comment]
We moved them to the left. All buttons are there.
