### ISSUE TITLE
Appears packages with the same name in official repositories and aur needing upgrading

### ISSUE THREAD

**Issue by kouros17** [manjaro/pamac#344]
Pamac  6.1.1-1 appears packages with the same name in official repositories and aur needing upgrading maybe because the aur packages are newer than those of the official repositories. 
If I select to upgrade them nothing happens but the color of the pamac remains red.

![2017-10-17 03-14-24](https://user-images.githubusercontent.com/27904795/31641009-8fade7a4-b2ea-11e7-8c6c-f3481c155008.jpg)

**Comment by philmmanjaro** [comment]
Seems we should ignore packages from AUR when we have similar in our binaries.

**Comment by guinux** [comment]
This should not already appears.
I tried with plymouth-legacy which is newer in AUR than in repos and pamac doesn't show any update.
