### ISSUE TITLE
Add graphics while updating repos

### ISSUE THREAD

**Issue by prescott66** [manjaro/pamac#350]
When you open Pamac and then click "Updates" button, there is a empty white area, until is displayed "Your system is up to date".

It would be nice have there some graphics or label displayed, that informs user about updating repositories.

For example this spinner:
https://developer.gnome.org/gtk3/stable/GtkSpinner.html

...with label Updating repositories, or something.

**Comment by guinux** [comment]
fixed in v6.2.0
