### ISSUE TITLE
mpg123 icon 

### ISSUE THREAD

**Issue by luzpaz** [manjaro/pamac#354]
From the mpg123 SF page: https://sourceforge.net/projects/mpg123/

https://a.fsdn.com/allura/p/mpg123/icon?1355301383
![image](https://user-images.githubusercontent.com/4140247/31972480-ff743462-b8ee-11e7-877c-44ed1caaa086.png)

**Comment by gabrc52** [comment]
Which leads to a wider issue: how can we add an icon (or a screenshot would be great too, if a section is added for them) to an app so it appears on Pamac. Where does Pamac fetch the icons from?

**Comment by guinux** [comment]
Pamac fetches icons from archlinux-appstream-data package.

**Comment by luzpaz** [comment]
So all the missing icons in pamac are because those ivons are missing in said data packages (aside from apps/libs that don't have icons/logos)?

**Comment by guinux** [comment]
yes
