### ISSUE TITLE
Startup time is too long (most of the time)

### ISSUE THREAD

**Issue by KSXGitHub** [manjaro/pamac#356]
It goes like this:
1. User clicks 'Add/Remove Packages' from app menu
2. Transparent window appear for a while
3. Pamac window finally become visible, but unresponsive (for a while), no packages appear in the list
4. GNOME Shell tells me that the app is not responding and ask me to 'Force Quit' to continue to 'Wait'
5. Package list finally appears, the app stop being unresponsive, I can now use pamac

**Comment by philmmanjaro** [comment]
@guinux: maybe we should load the app first and then try to sync DBs and other tasks ...

**Comment by KSXGitHub** [comment]
@philmmanjaro  Syncing DB takes time, especially in machine with over 200 packages, it takes a really long time. IMHO, pamac shouldn't sync DB unless user decide to.

Meanwhile, `pacman -Q` list all installed package names almost instantly

**Comment by guinux** [comment]
Pamac can takes some times to start but only the first time you launch it and if pamac-tray didn't check updates yet (or was not started).
It's due to libalpm which takes some time to load the databases in memory the first time you access them. If you disable pamac-tray at startup, reboot then run `pacman -Su`,  it will takes some time. The next call of pacman will be fast, it's exaclty the same thing with pamac.

**Comment by lots0logs** [comment]
@guinux Actually it's not the same. I reported this issue previously and it still exists today. Pamac always downloads the files databases no matter what. That is what takes so much time. Pacman does not do that. Pacman only downloads the regular databases when performing system updates.

**Comment by guinux** [comment]
@lots0logs: Databases are not refreshed at startup so it's not related.

**Comment by lots0logs** [comment]
Sorry I just saw that you mentioned running `pacman -Su` so I thought this was about opening the updates tab. I was in a hurry earlier and didn't read the entire thread :sweat_smile:

**Comment by philmmanjaro** [comment]
@guinux: can we somehow transfer some of the function to the **daemon** so we speed up the lauch of **pamac** in general?
