### ISSUE TITLE
Using space in search is not possible

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/pamac#358]
A [user reported an issue](https://forum.manjaro.org/t/pamac-6-2-0-1-problem-with-spaces-in-search-some-freeze-gnome) not able to search for `google music`. Space can't be used at all. Intended that way? @guinux

**Comment by 1LinuxGuy** [comment]
Note : The problem happens after writing a word, if you wait a second or two, then hit the space bar.

**Comment by guinux** [comment]
Pamac waits for 500 ms after you stop typing and then start to search.
The reported issue occurs when typing a space and wait after the timeout to continue typing.
So **using space is of course possible** if you wait less than 500 ms between a space and the next character.

**Comment by 1LinuxGuy** [comment]
@guinux Could it be possible to increase the time ? 500 ms is pretty short.

**Comment by guinux** [comment]
@philmmanjaro @1LinuxGuy what would be a good delay between stop typing and start searching in your opinion ?

**Comment by philmmanjaro** [comment]
Make it an option and set the default to 1000ms. The user can then always change the default to its needs. Everybody types differently to be honest.

**Comment by guinux** [comment]
I increased the timeout to 1000 ms, let's see if it's enough.

**Comment by mirh** [comment]
Actually, I don't think timeout was the problem (0.5s was kinda good, for google instant-like purposes). 
I'm trying to look for `git cola`, and it doesn't show (even though it's there in yaourt)
