### ISSUE TITLE
Last AUR package doesn't clear from the list

### ISSUE THREAD

**Issue by alexandruianu** [manjaro/pamac#36]
With pamac 2.2, the last AUR package that's updated by the program stays in the "to be updated" list after the process is finished. Only canceling and restarting the pamac-tray process will remove it from the list and keep the icon clear.

Ex: I have google-chrome to be updated, I update, then it appears again in the list and it wants to update again (despite being correctly updated). Or, I have insync and insync-thunar, I update both, then insync-thunar (the last one to be built) appears again as needing an update.

**Comment by prescott66** [comment]
Confirmed

**Comment by philmmanjaro** [comment]
So this is a regression, which was not present in Pamac 2.1.2?

**Comment by prescott66** [comment]
i think this bug is present since 2.2 RC versions

**Comment by korrode** [comment]
confirmed here too.

**Comment by philmmanjaro** [comment]
regression seems to be added within eb9ace7b82abb0422382b8757f85e216a0ecc274

**Comment by philmmanjaro** [comment]
#37 creates regression. Maybe followed patch might fix it:
<pre>diff --git a/src/daemon.vala b/src/daemon.vala
index bfd1e10..d6ae0f1 100644
--- a/src/daemon.vala
+++ b/src/daemon.vala
@@ -1050,6 +1050,7 @@ namespace Pamac {
 		public void start_trans_commit (GLib.BusName sender) {
 			trans_commit.begin (sender, (obj, res) => {
 				var err = trans_commit.end (res);
+				refresh_handle ();
 				aur_updates_checked = false;
 				trans_commit_finished (err);
 			});</pre>

**Comment by philmmanjaro** [comment]
I tested now several things. All the same result. Updated AUR package will be still in list until you close updater and reopen it ... Hmm ...

**Comment by prescott66** [comment]
still not fixed in 2.2.1

**Comment by guinux** [comment]
Can someone else confirm this ?

**Comment by prescott66** [comment]
since update to 2.2.1 (Antergos repo) i get updates two times from AUR. i can confirm that in both situations.

**Comment by philmmanjaro** [comment]
Funny, on my end it works as it should. @prescott66: which package do you use from AUR?

**Comment by philmmanjaro** [comment]
Ok, I tested the package **abe**. It is not in the list anymore but pamac-tray don't get triggered. It still says one package is available for update. If you press on refresh it goes for normal. So only icon is not switching back to neutral. Updater is fixed, though ...

**Comment by prescott66** [comment]
i have used lollypop package for example.today i get this issue with colorhug-client package
