### ISSUE TITLE
[Feature Request] pacaur as default for AUR packages

### ISSUE THREAD

**Issue by ceyhunnabiyev** [manjaro/pamac#360]
I see, pacaur caught the first place in  AUR  popularity . Why don't you use this as default? Even I heard that pacaur is more secure than yaourt.

**Comment by tabepic** [comment]
Pamac doesn't use yaourt, it builds packages itself (with makepkg of couse).

**Comment by ceyhunnabiyev** [comment]
Ok, sorry..
