### ISSUE TITLE
[Feature Request] Audio cue to let you know all tasks have finished

### ISSUE THREAD

**Issue by acerspyro** [manjaro/pamac#361]
I often leave pamac running in the background, waiting for it to be done updating so I can install a new package, but I often forget it.

It would be nice to have an audio cue as well as a desktop notification option, GNOME's default "Ding!" sound would do nicely for the notification sound.

**Comment by notramo** [comment]
What do you think about a desktop notification?

**Comment by Huluti** [comment]
Some desktop notifications would be nice.

**Comment by guinux** [comment]
Fixed with a notification in v6.3
