### ISSUE TITLE
Files Databases Are Always Downloaded When Installing Updates

### ISSUE THREAD

**Issue by lots0logs** [manjaro/pamac#368]
This was originally reported on #272 and it still occurs in the latest version of pamac.

From #272:
>Currently Pamac automatically refreshes the databases when you click install updates. Often times refreshing is unnecessary because it was just refreshed prior to showing the available updates. However, I know that depending on the user's settings there will be times when the refresh is necessary. I think it would better if the *.files databases for each repo were not downloaded when performing a refresh prior to installing updates. The *.files databases are much larger than the normal databases and so it delays the whole process quite a bit.

PR coming shortly...

**Comment by petsam** [comment]
It would be nice if there was an option like:
>Auto-Refresh databases if they are older than [xxx] minutes (default:20?)

and don't refresh on Software Install mode.
Any thoughts?

**Comment by lots0logs** [comment]
@guinux I thought of [a way to solve this issue](https://github.com/manjaro/pamac/pull/414). Let me know what you think.
