### ISSUE TITLE
Status icon of installed AUR package

### ISSUE THREAD

**Issue by prescott66** [manjaro/pamac#37]
After successfull installation of package from AUR repo, status of installed packages stays unchanged (empty white box) and they should be "green" as is after installation of non-AUR package.

Pamac version: 2.2

**Comment by philmmanjaro** [comment]
This is mostly related to #36.

**Comment by prescott66** [comment]
can be :)

**Comment by philmmanjaro** [comment]
Please check if 68c8820f3bddd132ad96da24027bfd662a91f7bf fixes your issue ...

**Comment by philmmanjaro** [comment]
Hi Guillaume,

I'm getting compile errors here:

<pre>daemon.vala:88.19-88.22: error: `File' is an ambiguous reference between `GLib.File' and `Alpm.File'
			var lockfile = File.new_for_path ("/var/lib/pacman/db.lck");
			               ^^^^
daemon.vala:88.8-88.62: error: var declaration not allowed with non-typed initializer
			var lockfile = File.new_for_path ("/var/lib/pacman/db.lck");
			    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
daemon.vala:90.9-90.16: error: The name `lockfile' does not exist in the context of `Pamac.Daemon.check_pacman_running'
				if (lockfile.query_exists () == false) {
				    ^^^^^^^^
daemon.vala:95.9-95.16: error: The name `lockfile' does not exist in the context of `Pamac.Daemon.check_pacman_running'
				if (lockfile.query_exists () == true) {
				    ^^^^^^^^
Compilation failed: 4 error(s), 0 warning(s)</pre>

**Comment by philmmanjaro** [comment]
Fixed with 43e1042e09beb5d1bf4b53fefde62de585747df2

**Comment by philmmanjaro** [comment]
#36 is fixed, but **pamac-tray** don't get the update. It still claims to have at least the AUR package(s) for installation in queue ...

**Comment by philmmanjaro** [comment]
Here we go for a better clarification: if you downgrade an AUR package, in my example **abe** you get a notification that this package is outdated. You click on the notification and you find **abe** listed in **pamac-updater**. **pamac-tray** signals **red** using **Faenza** icons.

You update the package as usual by building it thru **yaourt**. After installing it on your system, **pamac-updater** signals no update available. **pamac-tray** still claims to have one package for update:

![pamac-37](https://cloud.githubusercontent.com/assets/5050022/6787883/05d20642-d196-11e4-84c8-c4afe25eb4ab.jpg)

Clicking on refresh, brings **pamac-tray** to neutral ...

**Comment by philmmanjaro** [comment]
For me it works now ...
