### ISSUE TITLE
No information on available updates after partial update

### ISSUE THREAD

**Issue by RalphBike** [manjaro/pamac#371]
After doing a partial update of a number of packages, Pamac gives me visual feedback that my system is up to date (which is wrong as more updates are available). After closing and starting Pamac again, Pamac checks for updates but still tells me no updates were available.

I am well aware of the fact that partial updates are not supported by Manjaro and that they are not the best way to do updates. However there are still cases in which a partial update might be necessary (bad connection, urgent updates, etc.), so Pamac should support this to a certain extent. Otherwise users should not be able to select a subset of available updates in Pamac.

Tested versions were: 6.2.2-1 and 6.2.2-2.

**Comment by philmmanjaro** [comment]
This is no error. If you do a partial update it automatically blacklists the packages you had deselected. That is why you have an up-to-date system. Please check in settings to remove the blacklist packages.

**Comment by RalphBike** [comment]
Really? I am surprised to hear that and do not think this is intuitive. If a number of packages is blacklisted (for how long?), then the user should get feedback before or after the blacklisting, also for security reasons. For ignores from pacman.conf I frequently get feedback in Pamac.

Where can I undo this blacklisting? The ignore-box in the settings dialog does not contain anything, /etc/pacman.conf and /etc/pamac.conf do not contain anything suspicious either.

**Comment by lots0logs** [comment]
FWIW, I agree. Simply choosing not to update one package on the list shouldn't result in the package being blacklisted behind the scenes.

**Comment by notramo** [comment]
Blacklisting the package isn't bad, but it should give feedback to the user at every update.

**Comment by RalphBike** [comment]
@notramo I agree. In addition the user should also be able to undo the blacklisting from the GUI somehow.

IF the blacklisting is needed at all. My personal preference would be to get the updates displayed over and over again, until I decide to install them. 
Blacklisting should not happen automatically but be something special that the user performs seldom and probably manually.

**Comment by notramo** [comment]
What do you think about auto-deselecting in every update, until it is selected again, but not blacklisting?

**Comment by RalphBike** [comment]
Hi, sounds much better to me, as long as there is no wrong impression of the system status and the user has a way to quickly select all of them again.

There are two cases that need to be considered:
a) the users decides to do nearly all updates. only 1 or 2 are missing, which is done on purpose for some compatibility reasons and probably for several update cycles.
b) the users performs only 1 or 2 updates, all others remain but only for a short time, until the user has better network.

Both cases should be communicated transparently and the user should be able to handle both efficiently.

In my case I did b) and was wondering where all my 81 other updates had gone.

**Comment by cromerc** [comment]
Looking over transaction.vala, there is no code at all that adds those deselected packages to the "blacklist" known as IgnorePkg which is in /etc/pacman.conf.

I cannot reproduce this problem in neither pamac, nor pamac-classic. When I deselect a package from the updates, naturally it does  not update it. Then pamac asks me again if I want to update it. It keeps asking me if I want to update it until I finally do. The update never disappears from the update list nor is blacklisted. I believe this issue is bogus.

**Comment by RalphBike** [comment]
That sounds odd. As mentioned above I did not find any trace of blacklisting in one of the two config files pacman.conf and pamac.conf but could definitely not update the remaining 81 packages with pamac. Updating with pacman worked fine. 

I can recheck again during the next update or on the weekend (Sorry, I am on vacation at the moment). Which further information should I provide?

**Comment by tabepic** [comment]
@RalphBike Does the "blacklist" persist over reboots? (Or if the pamac folders in /tmp are cleared?)

**Comment by RalphBike** [comment]
@tabepic Sorry, I am on vacation at the moment. I will try to reproduce it on Sunday and see if I can do more tests.

**Comment by RalphBike** [comment]
Hi, I tested this again and am not able to reduce it on my other machine. On the first machine however it now looks like the pacmac db has to be restored. I will close this issue. Sorry for bothering.
