### ISSUE TITLE
Back button gone after DB refresh in Detail View

### ISSUE THREAD

**Issue by petsam** [manjaro/pamac#372]
How to reproduce:
1. Open Pamac
2. Click menu, select "Refresh Database"
3. Click Details (bottom button)
4. After refresh is finished the [Back] button Up-Left  disappears

Pamac ver: 6.2.2-2
DE: xfce4
GTK3 theme: Breeze maia dark (checked with other GTK3 themes too)
WM: Compiz (also checked with xfwm4 and several themes of either WM)

Edit: Just checked it in my Testing install in xfce and there is no issue.
Pamac: same version !!
Adwaita dark.
If I could check something that helps, please advise me.

Edit2: It exists with Gnome (Testing) pamac 6.2.2-3

**Comment by lorenzosu** [comment]
Hi I'm facing the same problem on Manjaro with pamac version 6.2.2-5 with the Breeze theme. This happens as reported after database update but also after e.g. a failed AUR install.

Let me know if you need any detail which may help.
