### ISSUE TITLE
[Question] Intercepting packages to be updated

### ISSUE THREAD

**Issue by Ste74** [manjaro/pamac#375]
Is there a way to show the pamac update?
gnome-shell-extension-manjaro-update can use to show the packages to be updated ...

**Comment by guinux** [comment]
Pamac-tray comes with pamac and show update notifications in GNOME.

**Comment by Ste74** [comment]
I know this, anyway don't know for many time pamac-tray show icon in gnome specially in wayland session since gnome dev remove system tray.. In gnome we use a native status indicator tweaked for manjaro. At the moment we  check the updates via bash script and very well so consider this request null.
