### ISSUE TITLE
the suggestion

### ISSUE THREAD

**Issue by tulliana** [manjaro/pamac#376]
Hi guys,

Updates should be shown in percentiles

example:
![ekran goruntusu_2017-12-03_21-43-40](https://user-images.githubusercontent.com/2324162/33528602-86a32192-d874-11e7-8e4b-fa9140c9fbbe.png)

thanks

**Comment by Huluti** [comment]
@guinux of more simple just write the percentage (without progressbar) under the title.

**Comment by luzpaz** [comment]
@tulliana would you be willing change the Issue summary to be more descriptive, just `the suggestion` is not helpful at all, IMHO.

**Comment by guinux** [comment]
Implemented in v6.3.0
