### ISSUE TITLE
feature request 

### ISSUE THREAD

**Issue by rahmanshaber** [manjaro/pamac#377]
There should be meta package to install a full desktop.
Like i want to install lxde-desktop , but i have to select specific package needed by the desktop all the time.I have to install build-essential package to build my apps.But i have to type it in terminal. 

I mean a meta package will include all the apps list to install all at once with out searching.

Also add meta package for QT ,GTK, APACHE, devlopment etc.
Aso for audio production,meta package fro gamers .
Also essential apps meta package for gtk and QT desktops.
A poll can be helpful to include packages in meta package.

Choice is good for user but simplicity is also needed.

**Comment by tabepic** [comment]
What exactly makes up a "full desktop"?

Do we define it as every package in a certain group? (the xfce group for example)?
Should it be defined as just a metapackage? If so, what dependancies should it bring in?

Because of all this controversy, I think it'd be best if choosing exactly what to install up to the user. (installing an entire group isn't hard in pamac)

**Comment by rahmanshaber** [comment]
So can use panel from xfce settings from cnnemon and file manager from KDE.
I like that idea .

**Comment by philmmanjaro** [comment]
Well, for that we have our project [desktop-settings](https://github.com/manjaro/desktop-settings), which is designed for that purpose. Also our [iso-profiles](https://github.com/manjaro/iso-profiles). Most desktops have groups already, so you may install KDE by typing `sudo pacman -S plasma kde-applications`. Also some meta packages exist for that desktop already.

**Comment by rahmanshaber** [comment]
i am talking in pamac

**Comment by philmmanjaro** [comment]
Already possible thru groups.

**Comment by rahmanshaber** [comment]
ok.got it

**Comment by petsam** [comment]
A more descriptive title would help people browsing issues.
Thanks @rahmanshaber

**Comment by guinux** [comment]
Use groups
