### ISSUE TITLE
[Bug] Pamac shows duplicated packages

### ISSUE THREAD

**Issue by ceyhunnabiyev** [manjaro/pamac#398]
https://forum.manjaro.org/t/stable-update-2018-01-07-browsers-nvidia-php-compiz-adapta/37835/56

**Comment by philmmanjaro** [comment]
Does it affect the install? A `pacman` search only shows one. Seems to be an `appstream` issue.

**Comment by ceyhunnabiyev** [comment]
> Does it affect the install?

No.

This is pamac issue. because when I select one, it automatically selects duplicated,  `pacman -Ss` and `pacman -Q` don't show duplicated one.

**Comment by guinux** [comment]
It's because there is two entries in appstream database, so it's an appstream issue.
