### ISSUE TITLE
Link for website on About does not work, running pamac as root

### ISSUE THREAD

**Issue by mrcasquinhas** [manjaro/pamac#405]
Click on it, nothing happens. 
Open paman on terminal with pamac-manager
When I click the link, this appears:
[7708:7708:0204/145903.093624:ERROR:zygote_host_impl_linux.cc(90)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
So it would be better to show some error or on the about window, show the background on red color, or something, so we would know we're running as root and links do not work.
Or show a message, you should run this as user, not root.

Antergos, with xfce, pamac version 6.2.3.

**Comment by guinux** [comment]
Pamac must be run as standard user.
