### ISSUE TITLE
[Feature Request] Edit PKGBUILD for AUR packages in pamac

### ISSUE THREAD

**Issue by ceyhunnabiyev** [manjaro/pamac#407]

**Comment by luzpaz** [comment]
Please. 
Use Case: https://aur.archlinux.org/packages/scribus-svn/#news
An AUR maintainer was asked by an AUR admin to `no longer use aur update bot for updating any package without a "real" PKGBUILD change. He said I was violating guidelines.`
The Scribus release cycle is painfully slow. So it's useful to update directly from their svn. This feature would allow that.

Another reason: From a security standpoint it's important to see the contents of PKGBUILD to make sure there are no shenanigans going on.

**Comment by guinux** [comment]
see #87
