### ISSUE TITLE
Feature Request : Allow disabling of Pamac scheduled mirrorlist regeneration and package cache cleaning

### ISSUE THREAD

**Issue by sueridgepipe** [manjaro/pamac#408]
There are two Pamac system timer services that schedule the auto mirrorlist generation and auto cache cleaning.
```
pamac-cleancache.timer
```
```
pamac-mirrorlist.timer
```
I keep disabling these services, but they keep being re-enabled by Pamac. Annoyingly there is no way to disable this, short of masking the services.

Please add Pamac configuration options to disable the scheduled auto regeneration of the mirrorlist and cleaning of the package cache, allowing the above systemd timer services to stay disabled if so desired.

Thx.

**Comment by sueridgepipe** [comment]
Is anything being done about this?

Every bloody time pamac updates it adds these services which clobbers my mirrorlist and my package cache.

Please provide a mechanism to disable this automatic behaviour in Pamac settings.

Masking all pamac services doesn't help, next pamac update and the bloody things are recreated.  Ridiculous.

**Comment by guinux** [comment]
It was a PKGBUILD issue, it should be fixed now
https://github.com/manjaro/packages-extra/commit/efd130f5d294fd8c2a098d3101118e1ca457f66f
