### ISSUE TITLE
Allow copying from the terminal area

### ISSUE THREAD

**Issue by Gooberpatrol66** [manjaro/pamac#41]
I frequently need to copy selected output from Progress > Details to look up errors and add keys to gpg. It would be nice if I could copy it to the clipboard instead of transcribing it. There isn't a context menu and I can't find anything about whether a keyboard shortcut exists.

**Comment by philmmanjaro** [comment]
I assume this is only regarding AUR packages and user interactivity needed in some cases?

**Comment by Gooberpatrol66** [comment]
Yes.

**Comment by vejobuj** [comment]
:+1:  
And allow to launch terminal output on demand - keep the terminal output opened and close after a timeout of 3 seconds for example like in Synaptic Package Manager.

**Comment by Gooberpatrol66** [comment]
I just discovered that Ctrl+Insert works, which is good enough for me. I guess anyone who specifically wants a context menu should make a new issue for that?
