### ISSUE TITLE
pamac does not show updates from Arch repositories on Gnome

### ISSUE THREAD

**Issue by glaubersm** [manjaro/pamac#412]
Hi
I use pamac-classic on Arch Linux installed from AUR.
On my system pacmac only shows updates from AUR, no update from Arch repositories is listed.
The computer affected runs Gnome 3.28. I have the same pamac installed on another computer running KDE Plasma and it's working as expected.

**Comment by philmmanjaro** [comment]
Please open an [issue](https://github.com/cromnix/pamac-classic/issues) on their project page.
