### ISSUE TITLE
How to integrate pamac with archlinux-updates-indicator?

### ISSUE THREAD

**Issue by kq01526** [manjaro/pamac#413]
Hi,

now that the pamac tray icon is no longer working with the latest GNOME release, the question is:

How do you integrate pamac with [archlinux-updates-indicator](https://github.com/RaphaelRochet/arch-update)?

[The Wiki](https://github.com/RaphaelRochet/arch-update/wiki) explains how to use CLI tools such as yaourt, but not GUI tools such as pamac.

What would be the "Check command" and what would be the "Update command" for pamac?

Regards

**Comment by guinux** [comment]
Pamac doesn't have a CLI. It's only a GUI.
If pamac can't integrate with archlinux-updates-indicator, pamac-tray runs well and gives update notifications in GNOME (even if you don't see the tray icon).

**Comment by kq01526** [comment]
@guinux @Ste74 Could you possibly have a look at https://github.com/RaphaelRochet/arch-update/issues/97 ?

**Comment by Ste74** [comment]
See my reply on `arch-update` repo
