### ISSUE TITLE
cp error on pamac 6.2.5-1

### ISSUE THREAD

**Issue by killajoe** [manjaro/pamac#417]
`org.manjaro.pamac.user[3428]: cp: the call of stat for '/var/lib/pacman//sync/*.{db,files}' is not possible: file or directory not found `

**Comment by lots0logs** [comment]
This has already been fixed. Package was updated to 6.2.5-2

**Comment by killajoe** [comment]
o yes i can see.. It has not yet been shipped across the pond...

**Comment by killajoe** [comment]
`org.manjaro.pamac.user [27843]: cp: unable to call stat for '/var/lib/pacman/sync/*.files': file or directory not found` may related to Antergos (where i get this) ? as there are no such **.files** only **.db**
