### ISSUE TITLE
pamac 6.2.5-2 app-info path missing (pamac-tray.desktop)

### ISSUE THREAD

**Issue by killajoe** [manjaro/pamac#421]
**Distro:** Antergos 
Error warning from journal:

`pamac-tray.desktop [27995]: /usr/share/app-info/icons/archlinux-arch-antergos/64x64/mate-utils_mate-disk-usage-analyzer.png: file »/ usr / share / app-info /icons/archlinux-arch-antergos/64x64/mate-utils_mate-disk-usage-analyzer.png «Could not open: file or directory not found`

```
ls /usr/share/app-info/icons/         
archlinux-arch-community  archlinux-arch-core  archlinux-arch-extra
```

backlink to original post:
https://github.com/Antergos/antergos-packages/issues/301#event-1541975067

**Comment by guinux** [comment]
It's an appstream database issue.
