### ISSUE TITLE
[Enhancement/Feature request] Ask for transaction commit only once

### ISSUE THREAD

**Issue by zegkljan** [manjaro/pamac#432]
Now, when one upgrades or installs packages both from repositories and AUR, the user may be asked to confirm the transaction commit if some new packages are to be installed (either because the user wants to install them or as a result of new versions' dependencies). However, the user is asked **again** once the repository packages are upgraded and it's time for the AUR packages.

This behavior is very inconvenient when there is a lot of repository packages to upgrade because the user has to monitor the progress and wait for the repository packages to be ready and then has to commit again. It would be much more convenient if the user was asked once at the start (or twice but both confirmations before the start of the process) so that the user could just confirm everything necessary and then leave it be.

**Comment by guinux** [comment]
Fixed with 04535a1
