### ISSUE TITLE
How does Pamac handle unused dependencies? 

### ISSUE THREAD

**Issue by Madis0** [manjaro/pamac#434]
[Quoting a post about Arch: ](https://www.reddit.com/r/archlinux/comments/2dsvp5/_/)

> - Some packages do not need some of their dependencies after the install (i.e. only needed for building)
> - When I fail to install a package from AUR, some of the dependencies remain installed
> - When I remove an AUR package, some of the dependencies remain installed 

I'm aware of an option to fix the third problem, but I'm wondering about the first two.

**Comment by guinux** [comment]
The packages related to the first two point are "Installed as a dependency for another package" so you can find them in the orphans view.

**Comment by Madis0** [comment]
So they are grouped, but not removed (or prompted to remove)? Does it show what packages they are/were they related to though?

**Comment by Madis0** [comment]
I browsed it a little and now I see how it works. However, why would it not automatically remove the dependencies it no longer needs after installing a package? Is it a compatibility concern?

**Comment by guinux** [comment]
I prefer to let them installed as it's totally harmless and they can be useful when updating the package.

**Comment by Madis0** [comment]
Right, I forgot that AUR always needs compiling, even when updating. That answered my questions well, thank you!
