### ISSUE TITLE
Hide AUR tab if disabled in settings

### ISSUE THREAD

**Issue by Madis0** [manjaro/pamac#437]
_Like #57, but that issue seemed to refer to some older behaviour of Pamac._

If the AUR is disabled in settings, it would make sense to hide the tab too in search.
Or, if you wish to keep it shown, at least gray out all items and checkboxes to indicate that they can not be used at this time.

**Comment by guinux** [comment]
It's already done. AUR tab is hidden when disabled in settings.

**Comment by Madis0** [comment]
Weird, when launching Pamac in Manjaro live CD, it shows the AUR tab on search while the option is disabled in settings.

**Comment by guinux** [comment]
Ok it's a bug which appears only because databases doesn't exist at live cd startup.
Well find :)
