### ISSUE TITLE
Pamac breaks -Syu update for Antergos, cyclic dependency prevents pamac uninstall without -Rdd

### ISSUE THREAD

**Issue by lyterk** [manjaro/pamac#439]
The update error I was getting was:

`resolving dependencies...`
`looking for conflicting packages...`
`error: failed to prepare transaction (could not satisfy dependencies)`
`:: pamac: installing pacman (5.1.0-1) breaks dependency 'pacman<5.1'`

I run antergos, which installs pamac by default. Arch Linux just released pacman-5.1.0-1.

So, first off I was able to `-Syu` by `IgnorePkg = pacman`. That wasn't a good enough solution for me, so I tried removing pamac. 

I think there was some sort of cyclical dependency there-- `pacman -Rsn pamac` failed with:

`error: failed to prepare transaction (could not satisfy dependencies)`
`:: pamac-tray-appindicator: removing pamac breaks dependency 'pamac'`

At that point, I ran `pacman -Rdd pamac`, and that removed it and solved my problems.

I think you might get Antergos users coming across this more, I assume i won't be alone. I realize it is strictly solvable with pacman commands, but it's a solution that isn't readily google-able.

**Comment by philmmanjaro** [comment]
This is no issue. The compiled **pamac** only works with **pacman 5.0.1** and not with the just released **pacman 5.1.0**. Please contact the Antergos maintainer to re-compile their package of **pamac**.
