### ISSUE TITLE
[Bug] pamac always shows "Your system is up-to-date"

### ISSUE THREAD

**Issue by mjc666** [manjaro/pamac#442]
Despite pacman -Syu reporting available updates, pamac never does.  I've tried to manually "Refresh Databases", "Refresh Mirrorlist" and "Clean Cache".  I'm running latest version of Manjaro XFCE (17.1), pacman 5.1.0-2, and pamac 6.3.92-1

![screenshot_2018-06-01_09-37-00](https://user-images.githubusercontent.com/16667907/40846559-9129fa80-657f-11e8-9e93-6d18cb5d543d.png)

**Comment by mjc666** [comment]
More info - I rebooted & it started working again.

**Comment by RalphBike** [comment]
I had the same effect two weeks ago with Pamac 6.3.1, but was not able to reproduce it after a reboot.

**Comment by RalphBike** [comment]
Not for me.
