### ISSUE TITLE
Error message can not be copied to clipboard

### ISSUE THREAD

**Issue by RalphBike** [manjaro/pamac#443]
I can not copy an error message from Pamac as text to the clipboard, e.g. for searching for that error on the forum. 

It would be nice if I could either select the error message and copy it with the standard hotkeys or if there was a button or context menu "Copy to clipboard"

Message: Some failed dependany during an update.
Version used: Pamac 6.3.1.

**Comment by guinux** [comment]
I will fix it but know you can copy it from details view
