### ISSUE TITLE
Show AUR details for installed packages

### ISSUE THREAD

**Issue by Madis0** [manjaro/pamac#446]
It would be useful to show AUR details for packages that are installed too.
Details include:

- package website
- votes
- first submitted
- last modified

**Comment by guinux** [comment]
It's already the case:
![capture du 2018-06-02 11-42-21](https://user-images.githubusercontent.com/958891/40873091-35100f1a-665a-11e8-8488-f9ff38f40718.png)

**Comment by Madis0** [comment]
Since 6.4.0? 
For some reason I have 6.3.92-1, though I updated it yesterday. I also see the auto-download option in settings.

**Comment by philmmanjaro** [comment]
@Madis0: by default AUR support is disabled. Therefore it doesn't connect to AUR. It was first added via https://github.com/manjaro/pamac/commit/00fd98ae27ea33623033c4913a91c0262d98b984

**Comment by Madis0** [comment]
I had AUR enabled for a long time in the settings, that same package is installed from it. Now I re-enabled it and still can't see this.

**Comment by philmmanjaro** [comment]
![pamac-aur](https://user-images.githubusercontent.com/5050022/40873741-bdee733a-6655-11e8-9ba3-bbd52c89af18.jpg)
It might be only displayed when the package is not installed ...

**Comment by guinux** [comment]
@Madis0: it's because you installed firefox-nightly. Url is shown for uninstalled aur pkgs :)

**Comment by Madis0** [comment]
Right, can confirm now.
![screenshot from 2018-06-02 15-51-54](https://user-images.githubusercontent.com/8611110/40874816-f05e0674-667c-11e8-912f-001cd79d1775.png)
Editing the issue to reflect this.

**Comment by philmmanjaro** [comment]
Well, it might be possible to check if the installed package is available in AUR also. However, **pamac** currently uses a different engine to check for details on installed packages. Here we currently use the info the local DB provides us.

**Comment by yochananmarqos** [comment]
AUR packages do not have Appstream data.
