### ISSUE TITLE
[bug] unable to ignore package updates in Pamac

### ISSUE THREAD

**Issue by ghost** [manjaro/pamac#448]
As of the latest update, Pamac no longer respects which updates are selected, instead trying to update all regardless of selections. 
Currently on Antergos the x265 and ffmpeg packages have dependency issues if attempting to update them. As Pamac will not respect selections, this means any inexperienced or otherwise unknowledgeable Antergos users are completely unable to do updates.

Pamac properly displays the modified download sizes before commiting to the update and which packages are being updated or ignored, the failure is likely only in the transaction. 

OS is Antergos, Pamac version is 6.3.2-2 (latest on Antergos repository)

**Comment by philmmanjaro** [comment]
**v6.3** only supports **pacman <= 5.1**. Please update with **pacman** and use **v6.4** series.

**Comment by guinux** [comment]
fixed
