### ISSUE TITLE
Adapt to pacman v7.0.0 and libalpm v15.0.0

### ISSUE THREAD

**Issue by galegovski** [manjaro/pamac#449]
Pamac must be adapted to pacman v7.0.0 and libalpm v15.0.0, as these new versions of pacman and libalpm have modified some procedures.

**Comment by romangg** [comment]
Do you know what all needs to be changed? 

@yochananmarqos built Pamac against latest libalpm15, and it built and worked in early tests without issues.

**Comment by yochananmarqos** [comment]
@romangg I'm not so sure that anything does. Neither Octopi nor Pamac has ever supported all Pacman features to begin with.

Either way, @guinux is really the only one that can answer that question.

**Comment by galegovski** [comment]
With the latest version of pacman and libalpm released on Arch Linux on Sept. 14, 2024, there was an “incompatibility” of pamac with the new version of libalpm. I simply had to uninstall pamac to update pacman and libalpm, but there may be no bugs. If it has already been tested and works, please disregard my question.

**Comment by galegovski** [comment]
I noticed it here, it was actually a mistake on my part. Please disregard. Sorry!

**Comment by romangg** [comment]
No problem. Closing

**Comment by philmmanjaro** [comment]
The following changes were made in API:

```
API CHANGES BETWEEN 6.1 AND 7.0
===============================

[ADDED]
- sandbox functions
 - alpm_option_get_sandboxuser()
 - alpm_option_set_sandboxuser()
 - alpm_option_set_disable_sandbox()
 - alpm_sandbox_setup_child()
```

As soon as the user is enabling sandbox features **pamac** will break.

**Comment by philmmanjaro** [comment]
These are the changes made so far in **libalpm v15**: [libalpm-15.diff.txt](https://github.com/user-attachments/files/17021211/libalpm-15.diff.txt)

**Comment by romangg** [comment]
Had been confirmed by @guinux, that the additional functionality is unproblematic for pamac.
