### ISSUE TITLE
Auto-Switch for Keyserver if key not found

### ISSUE THREAD

**Issue by suther** [manjaro/pamac#453]
From time to time I have trouble with pamac, that some Keys for packages are not found on the keyserver. 

For example, today it was package kdesignerplugin

I had to import this key from another key-server manually via CLI. 
```bash
gpg --keyserver hkp://keys.gnupg.net --recv-keys 53E6B47B45CEA3E0D5B7457758D0EE648A48B3BB
```

#Feature-Wish

It would be awesome, if pamac wouldn't just try one Keyserver to get the keys, but would have a fallback for at least 3 different Keyservers. 
If key is not at first Keyserver (or keyserver is unavailable) it should look on second one and on third one, if second one also fail.

This would be a much smoother experience as forcing the user to go to cli and doing it manually.

**Comment by yochananmarqos** [comment]
`kdesignerplugin` was dropped from the repos to the [AUR](https://wiki.manjaro.org/index.php/Arch_User_Repository) recently. More than likely, you no longer need the package.

Either way, this is not related to Pamac at all. Some AUR packages required importing the key. See [Acquire a PGP public key if needed](https://wiki.archlinux.org/title/Arch_User_Repository#Acquire_a_PGP_public_key_if_needed)
