### ISSUE TITLE
Feature Request: build AUR packages in chroot

### ISSUE THREAD

**Issue by username227** [manjaro/pamac#454]
Hi,

I was hoping that you guys would consider adding an option to build AUR packages in a chroot. This is helpful to me for a couple of packages that need a chroot to build properly (that I haven't been able to troubleshoot successfully). paru has this option, and it would be a great addition to pamac.
Thanks!

**Comment by yochananmarqos** [comment]
We already have a tool. See [manjaro-chrootbuild](https://gitlab.manjaro.org/tools/development-tools/manjaro-chrootbuild).

This is out of scope for Pamac, so I'm going to close it.
