### ISSUE TITLE
Big cursor in pamac

### ISSUE THREAD

**Issue by goglm** [manjaro/pamac#456]
Installed Arch
![Снимок экрана_20241006_093837](https://github.com/user-attachments/assets/ba2fed5a-5104-45d0-adbf-9959dd15e59e)
![Снимок экрана_20241006_093946](https://github.com/user-attachments/assets/bede5e0e-ccbd-40db-8284-9dc83b88397f)

**Comment by philmmanjaro** [comment]
Known issue. See here: https://bbs.archlinux.org/viewtopic.php?pid=2199244#p2199244

**Comment by yochananmarqos** [comment]
This is a Gtk issue, not a Pamac issue. By the way, it's fixed with `gtk4` 1:4.16.3-1.
