### ISSUE TITLE
pamac-manager - Error dispatching to Wayland

### ISSUE THREAD

**Issue by benjamimgois** [manjaro/pamac#466]
I have just installed pamac-aur in arch linux via the command:

yay -S pamac-aur

This procedure have always worked fine for me, but after the last update i got this error when running pamac-manager:

`Gdk-Message: 22:06:57.428: Error 71 (Erro de protocolo) dispatching to Wayland display.`

I was only able to start the interface by forcing it in XWayland mode with:

GDK_BACKEND=x11 pamac-manager

**Comment by benjamimgois** [comment]
sorry, it was a misconfig in my system.

**Comment by phoropter** [comment]
@benjamimgois what was the misconfig for you? I'm encountering the same issue and am not sure where to look.

**Comment by phoropter** [comment]
Interesting that those packages are needed for pamac to work with wayland lol. Thanks!

**Comment by benjamimgois** [comment]
> Interesting that those packages are needed for pamac to work with wayland lol. Thanks!

does it worked for you ?
