### ISSUE TITLE
Dependency conflicts are shown in gibberish with 2024-11-30 Stable Update

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/pamac#469]
Some people report gibberish dependency conflict messages when doing the 2024-11-30 Stable update in Manjaro.

![image](https://github.com/user-attachments/assets/a9d90fdb-9841-41de-819a-20632128671c)

**Comment by guinux** [comment]
fixed with https://github.com/manjaro/libpamac/commit/23a509b3fd5219c363109b6b34486a147aba80df
