### ISSUE TITLE
Add option to remove database lock-file

### ISSUE THREAD

**Issue by manjaro** [manjaro/pamac#5]
Octopi has a feature to remove pacman's lock-file if needed. We might think about to add this also to pamac.

**Comment by prescott66** [comment]
great idea

**Comment by philmmanjaro** [comment]
We already have our error window if we fail to unlock our databases. We should add a button to delete the lock and try again to do what we tried to do before.

**Comment by prescott66** [comment]
Maybe option in options to automatically remove lock file will be great

**Comment by philmmanjaro** [comment]
Why that? You may do some packaging management. This file has a reason. I know we have an issue #10 with having a lock file on every bootup. I can reproduce it with our latest 0.9.0-dev build on XFCE. Might be related to pamac-daemon, pamac-refresh and pamac-try.

**Comment by philmmanjaro** [comment]
If we have the case ALPM_ERR_HANDLE_LOCK we should enable a button in transaction_info_dialog to delete db.lck file. Will work on this later today.

**Comment by philmmanjaro** [comment]
In transaction we have to use handle_error and trigger there all needed changes when we catch ALPM_ERR_HANDLE_LOCK. Still thinking about how to start this feature and get hold of the error as an trigger ...

**Comment by philmmanjaro** [comment]
In C it would be like this:

<pre>void trans_samething(void)
{
	alpm_errno_t err = alpm_errno(config->handle);
	if(err == ALPM_ERR_HANDLE_LOCK) {
		do something here
	}
}</pre>

**Comment by manjaro** [comment]
Here is another snippet in C:

<pre>#ifdef HAVE_LIBCURL
#include <curl/curl.h>
#endif

/* libalpm */
#include "util.h"
#include "alpm.h"
#include "handle.h"

alpm_errno_t SYMEXPORT alpm_errno(alpm_handle_t *handle)
{
	return handle->pm_errno;
}

const char SYMEXPORT *alpm_strerror(alpm_errno_t err)
{
	switch(err) {
		case ALPM_ERR_HANDLE_LOCK:
			return _("unable to lock database");
		/* Unknown error! */
		default:
			return _("unexpected error");
	}
}</pre>

Maybe I find some similar in alpm_config to use ...

**Comment by guinux** [comment]
Implemented in 6bb6de0
