### ISSUE TITLE
removal of lock file

### ISSUE THREAD

**Issue by kairuku** [manjaro/pamac#58]
I guess this is more of a question than anything. I was wondering how the pacman database lock removal and restore process works, because I notice that after running pamac, and then, before a reboot, running pacman in the terminal, I get the below pacman warning (which seems like it is just hidden by pamac, based on a [previous](https://github.com/manjaro/pamac/issues/39) pamac issue here on GitHub, unless I am misunderstanding something):
```
Warning: lock file missing /var/lib/pacman/db.lck
```
I notice after a reboot, but before running pamac, if I run pacman in the terminal I no longer have the warning. Is the lock only created at boot up? Is it not something pacman generates itself on the fly if it actually relies on a lock file for any length of time during the transaction?

Should pamac itself be restoring the lock if pamac is removing it and this is deviating from pacman behavior? I tend to use pamac for more convenient discovery and still use the terminal for updates, removals, etc, so it seems like I am always going to see this warning if I continue to use both methods.

Thank you for any insight :)

**Comment by guinux** [comment]
It's maybe because you close pamac (which removes the lock file) when pacman is running?

**Comment by kairuku** [comment]
I tried this combination of actions and it does cause that warning in pacman.

Notably, it seemed very awkward for me when trying to intentionally close pamac after starting pacman though, since when there is nothing to do, pacman completes pretty quickly (and I've seen this warning persist in the past during repeated runs of `pacman -Syu` when there was nothing to upgrade). I don't recall ever having both pamac and a terminal running pacman open at the same time, and just this awkwardness of the combined actions for me when doing it intentionally make it seem unlikely that I did it unwittingly before. But who knows.

However, with this intentional test just now, once I run pacman again,  the warning is gone, whereas before, the warning was persisting for me on any subsequent re-run of pacman, seemingly until I reboot. So in theory if I had accidentally closed pamac during a pacman run before, wouldn't I get the same results (i.e., only seeing the warning once, but not after immediately re-running pacman again, now some additional time after pamac was closed)?

**Comment by guinux** [comment]
Indeed, it's strange. If you say that you don't run packages transaction with pamac and the warning persists at every pacman execution before a reboot, it's two facts that make me say it doesn't seems to be a trouble related to pamac.

**Comment by kairuku** [comment]
*"it's two facts that make me say it doesn't seems to be a trouble related to pamac."

Just an update: I uninstalled pamac after opening this issue, and reverted to just using pacman and CLI pacman wrappers like powerpill, pacmatic and yaourt, and I've never had the problem again. I never had the problem in a year of using Arch without ever trying pamac either. So the only variable that has change is that I have stopped using pamac. That, to me, makes it seem like it is trouble with pamac, and there was mention of "past bugs" with pamac on the Antergos forums as well (I'd never even encountered pamac until doing a separate install of Antergos after having already used vanilla Arch).

**Comment by guinux** [comment]
Please try with v2.4.0, I made some changes about the lock file, this issue should be fixed.

**Comment by kairuku** [comment]
It seems to work, I have pamac-tray open when I run my script in the terminal and so far I'm not getting the warning anymore. I even tried opening the pamac updater GUI and the pamac add/remove GUI, then closing them while running pacman, and I didn't get a warning : -)

**Comment by philmmanjaro** [comment]
Great. Hopefully we don't have to reopen this one soon ;)
