### ISSUE TITLE
[Enhancement] 'Optional For' and other dependencies not being shown

### ISSUE THREAD

**Issue by joca-bt** [manjaro/pamac#61]
The ```Optional For``` dependencies are not being shown. For example, for ```gtk3``` (https://www.archlinux.org/packages/extra/x86_64/gtk3/) many dependencies are not being shown.

Maybe also show other types of dependencies? A suggestion, e.g. show:
Provides.
Dependencies: normal, optional, make.
Required by: normal, optional, make.

**Comment by guinux** [comment]
I just add "optional for" dependencies but, as "required by", pamac only shows installed deps, uninstalled ones are unuseful.
Alpm library doesn't give access to make deps.
