### ISSUE TITLE
antergos - pamac doesn't search for packages, if aur enabled

### ISSUE THREAD

**Issue by subjectdenied** [manjaro/pamac#64]
i guess this happened after the aur-repository was switched on august 8th

i can't search for archlinux packages in pamac anymore, until i disable the "search in aur" switch, after disabling the switch, the search-result appears

https://bugs.archlinux.org/task/45944

**Comment by philmmanjaro** [comment]
We will look into it ...

**Comment by philmmanjaro** [comment]
I'll upload a new package to our repositories.
