### ISSUE TITLE
Virtualbox hook: [vboxhost] not working, change install order for linux-headers

### ISSUE THREAD

**Issue by v17564** [manjaro/pamac#65]
Hello.

Pamac installs the package linux-headers after creating the images of the kernel and the "hook" of vboxhost does not work because vboxhost need the linux-headers.

From the last update:

[2015-08-17 13:52] >>> Updating module dependencies. Please wait ...
[2015-08-17 13:52] >>> Generating initial ramdisk, using mkinitcpio.  Please wait...
[2015-08-17 13:52] ==> Building image from preset: /etc/mkinitcpio.d/linux41.preset: 'default'
[2015-08-17 13:52]   -> -k /boot/vmlinuz-4.1-x86_64 -c /etc/mkinitcpio.conf -g /boot/initramfs-4.1-x86_64.img
[2015-08-17 13:52] ==> Starting build: 4.1.5-1-MANJARO
[2015-08-17 13:52]   -> Running build hook: [base]

[2015-08-17 13:52]   -> Running build hook: [shutdown]
**[2015-08-17 13:52]   -> Running build hook: [vboxhost]
[2015-08-17 13:52] Building virtualbox host modules for 4.1.5-1-MANJARO kernel...
[2015-08-17 13:52] Error! echo
[2015-08-17 13:52] Your kernel headers for kernel 4.1.5-1-MANJARO cannot be found at
[2015-08-17 13:52] /usr/lib/modules/4.1.5-1-MANJARO/build or /usr/lib/modules/4.1.5-1-MANJARO/source.
[2015-08-17 13:52] Ok.**
[2015-08-17 13:52] ==> Generating module dependencies

[2015-08-17 13:52] Upgraded linux41 (4.1.4-1 -> 4.1.5-1)

-- more updates --

[2015-08-17 13:52] Upgraded libpcap (1.6.2-1 -> 1.7.4-1)
**[2015-08-17 13:52] Upgraded linux41-headers (4.1.4-1 -> 4.1.5-1)**
[2015-08-17 13:52] Upgraded linux41-ndiswrapper (1.59-2 -> 1.59-3)

**Comment by philmmanjaro** [comment]
Don't use the **dkms** packages. Install **linux41-virtualbox-host-modules**.

**Comment by v17564** [comment]
Ok. I use dkms. The web page of Arch where it explains how to install virtualbox says that you can install vboxhost to avoid having to manually run the dkms every time the kernel is upgraded.

**Comment by v17564** [comment]
I read bad the 1º time. If i don't use dkms, how I install vboxdrv? I use OpenRC.

**Comment by philmmanjaro** [comment]
Then you install **linux41-virtualbox-guest-modules**. So always **[kernel-prefix]-virtualbox-guest/host-modules**.

**Comment by v17564** [comment]
I have installed linux41-virtualbox-host-modules  5.0.0-3, with its package i don't need dkms? The drivers automatically update with new kernels?.

**Comment by philmmanjaro** [comment]
Ah, yes, it will update automatically if needed with new point-releases of the same kernel series. If you want to install for example **linux42** then you use [mhwd-kernel](https://wiki.manjaro.org/index.php?title=Manjaro_Kernels) for that or [msm](https://wiki.manjaro.org/index.php?title=Manjaro_Settings_Manager).

**Comment by v17564** [comment]
Well, when i read the Arch web page it say: 
Install the VirtualBox kernel modules
Next, to fully virtualize your guest installation, VirtualBox provides the following kernel modules: vboxdrv, vboxnetadp, vboxnetflt, and vboxpci. *These must be added to your host kernel. *

But in web page don't say that this package made the job. And later spoke  about the dkms and vboxhost .... I am learning things.
Thanks.

**Comment by philmmanjaro** [comment]
Well, here on Manjaro we use our own tools and have all extramodules pre-compiled for all our kernels. If you use Manjaro, please always search our [wiki](https://wiki.manjaro.org/) first.

**Comment by v17564** [comment]
Ok.

**Comment by v17564** [comment]
Hi
I uninstalled all the modules of Virtuabox and i deleted all traces in the OS. I have reinstalled only the required modules, without neither vboxhost, dkms.
linux41-virtualbox-host-modules  5.0.0-3
virtualbox  5.0.0-1
virtualbox-guest-iso  5.0.0-1
And extension-pack.

By installing the xx-virtualbox-host-modules does not load the drivers at boot, something more is needed.

I have been reviewing the wiki of Manjaro about Virtualbox and i haven't found how to load the drivers in the boot.

Looking for internet i've found a page of Gentoo about Virtualbox and it explains how to do this in OpenRC:

https://wiki.gentoo.org/wiki/VirtualBox
Load the modules upon boot. When using OpenRC, edit /etc/conf.d/modules file. Add the following modules:
FILE /etc/conf.d/modules

modules="... vboxdrv vboxnetadp vboxnetflt vboxpci ..."

I think it would be interesting to put this information in the wiki of Manjaro. What do you think?

**Comment by philmmanjaro** [comment]
Now we are talking. I always thought you used **systemd**, as this is our default initsystem. However, it makes sense that it might differ in **openrc**.

**Comment by v17564** [comment]
Ok. From now always i specify that use OpenRC to avoid confusion.
Many thanks and sorry for the inconvenience.
