### ISSUE TITLE
[feature request] pamac 2.40

### ISSUE THREAD

**Issue by ringo32** [manjaro/pamac#66]
i know the last time on post. it worked, but can there a extra option for Aur support, how must i call..

Sleep Mode ?

is just you activate aur on, but standard is set off you have to push on with button thats the way i perosnal like :)  just extra option ? i dont use it always but when i want to use, i like to 'use' aur with a button... :)

not that is standard off... you have to edit config is also not confort to use, but is just a feature request. just that aur support is on but when loading Pamac the switcher is just off..  further seems fine.

**Comment by ringo32** [comment]
a good feature would be when you enable Aur, you see Aur only...  not that is mixing in the list.

**Comment by ringo32** [comment]
just inteded to be an checkbox in settings, you enable aur, but when started aur, you see the switcher but it would be standard on off. so you dont have to go everytime to settings to switch it on.

**Comment by guinux** [comment]
If I understand you would like to have the search in AUR button in package manager to be off by default even if AUR support is enabled? It's a good idea. Any other opinions?

**Comment by philmmanjaro** [comment]
No opinion on my side. Fine with me.

**Comment by ringo32** [comment]
guinux yes,   is a good option to in te setting.. eventuall..

**Comment by lots0logs** [comment]
@guinux I think best solution is to add an option in the settings (for whether or not the AUR is included in search results by default). Simply flipping the default value of the search's toggle button will disrupt the workflows of some users (obviously).

**Comment by philmmanjaro** [comment]
Hmm. That is true. Lets see what the community says.

**Comment by guinux** [comment]
Ok, I will add another option, with this last one I think AUR support will be totally modular for everyone.

**Comment by ringo32** [comment]
modularity is good
