### ISSUE TITLE
[bug] pamac 2.4 some quirks

### ISSUE THREAD

**Issue by ringo32** [manjaro/pamac#67]
http://i.imgur.com/t5lQPbE.png

system is up to date and send update icon in red :) 

aur check updates is disable... stil he want check aur on this...

only if you switch off aur in Settings...so this quirk does not work properly  as it should.

you can eventual change the aur update icon color eventual... if you do in package manager to off still send Red but if you swithc off then it goes off.

**Comment by philmmanjaro** [comment]
Works as designed. I think you assume that the search switch turned off disables the update search on AUR. No, you have to disable AUR to have what you want, well for the moment.

**Comment by ringo32** [comment]
if you see the picture , was just assumed, there is a selectionbox, aur, check for updates. but thats not selected.

sure i have now turn of the Aur to remove the red icon.. i asumed when you check the aur updates box, after the check it should check for aur updates? this case its not checked.. get only a screen, your system is up2date... So i have to switch off aur....completely then ?

**Comment by philmmanjaro** [comment]
Currently the checkbox is just for AUR search inside of pamac, but not to disable AUR support temporally. Seems you want to have a switch to also turn of checking for AUR updates without the need to type in your root password ?!?

**Comment by ringo32** [comment]
that mix for me atleast :) if there stand for pamac-tray if you see a head, activate Aur support.
you see under check for updates from aur, but if that is unchecked... my idea atleast on me, pamac-tray should not give the icon in red...

pamac 2.40 is now very straight enable aur or not, and sure i use aur support with pamac only i must set it every time off , so to go to settings you must add your password to turn it off... im personal used too, just switch the aur switch to on.... that option isnt.. but its more octopi alike i used too :)
thats probably other story..
personal i think octopi is better integrated aswell.. but thats a opinion ;) beside leave the rest a side...


if you activate your aur support, but ''unchecked"" check for updates from aur, should pamac-tray go to red. and when you click on it. will say system is up to date?
That is also not what you want. even if you push to stable need some information on working i gues ?  but for me  if check for aur unchecked.. i think personal pamac-tray should not open to red. if you have checked then it can be red... and show the updates.

rater i see also a option you activate aur, but you have also that option that de aur support is suspended automatical that you can enable it when want to use , not that you have to go to setting.

**Comment by philmmanjaro** [comment]
I understand your reasons. I also don't know how Arnt is doing it with Octopi. Maybe Guillaume will come up with something. AUR support with Pamac is now optional. If Yaourt is not installed it is disabled by default, completely.

**Comment by ringo32** [comment]
i just leave other beside, will adapt because octopi have those not in the settings but if you used too octopi i will notice, because is behind a button and you see aur only and if there new updates as example you notices even in package manger in red but is mostly used too must say pamac load  quicker so yeah :) And qt5 and xfce-panel are mostly no friends. , bit for this is just the mixture ''check for aur updates'' is unchecked. personal i would think pamac-tray leave aur out..
even aur support is on. that bugged me.. because i dont want update aur packages or will notice , only when i want offcourse. atleast i hope is clear what i in for this bug report :)

short : if check for updates is unchecked, pamac-tray must leave total out... because it showe red.
because pamac-tray doesnt suppport multiple colors for repo level like own repo and aur. so only red and say its up2date is mixture for me a bug.
:)

**Comment by guinux** [comment]
If check AUR updates is disable and tray icon is red because there are only AUR updates, it's a bug. Is it that issue you describe ringo? I will check it ASAP.

**Comment by ringo32** [comment]
yep...it showed red, if i turn check aur updates on, it showed aur updates.

**Comment by philmmanjaro** [comment]
What Guillaume ment here. Does it happen if you turn off AUR support or only if you turn off search for AUR packages. That is a difference.

**Comment by philmmanjaro** [comment]
Ah ok, now I get it. If the checkbox "Check for AUR updates" is unchecked but AUR-Support on in general. Yes, then it is a bug. Good catch.

**Comment by ringo32** [comment]
if you turn off Aur, support you dont have it..

but if you turn on aur support... but
in setting you have check for aur updates.. but thats unchecked
it should not show up basicly.


i should think Pamac-tray wont bother with a red icon if that is turn off.
if you look it at update ; no update.

other wise have it no use to split the parts..


its unclear if it show red for updates when aur updates is unchecked
only show up updates when that is checked. personal pamac-tray should not bother if that is unchecked.

**Comment by ringo32** [comment]
mayby brabling too much :)

**Comment by philmmanjaro** [comment]
Well, pamac-tray should show red in following cases:
1) AUR check for updates enabled: for binary and AUR packages on updates
2) AUR check for updates disabled: only for binary packages (**not for AUR packages**)

So, do you have case 2 and fully updated but newer AUR available and pamac is showing red?

**Comment by ringo32** [comment]
yes case 2, aur is enabled  but check for aur updates is disabled / unchecked. is not selected.

when open pamac-tray it said is up to date... when i check te boxes then it show up.

**Comment by philmmanjaro** [comment]
Ok, then we have no bug. All works as designed. So what is your issue then? I think you still don't understand why we have the AUR search inside of the manager and the AUR support. There is no different colour if an update is available. Do you like to have different colour when an AUR package is outdated?

**Comment by ringo32** [comment]
is not about differe nt color, is just show red and no updates....if aur is activated

**Comment by ringo32** [comment]
:< to impatint..myby bug on my side ...impatience... pfff sorry
did work...
as should :/

**Comment by ringo32** [comment]
this can be closed*

**Comment by philmmanjaro** [comment]
Ok, once again. To be clear. AUR check for updates disabled, you have that unchecked. So pamac only checks for binary packages (not for AUR packages). Do you have it red somehow when you know that you have an old AUR package installed. If that is true, then it is a bug as **AUR check for updates** is clearly disabled, as in unchecked. Obviously, if you enable the check by checking the checkbox it works as desigend. You have an old AUR package installed and Pamac shows red. So what is the case?

**Comment by ringo32** [comment]
bug is me , had to reboot. have downloaded a old aur package i set on sourceforge somewhere, didnt show red :/ sorry 

i was very convinced was a bug.. since i didnt reboot... i should not made this treath.

works as it should.

aur activated :  on 
check for aur update = unchecked.

grey icon.. only if you check, it became red.

works as it should

this can be closed

**Comment by philmmanjaro** [comment]
Ok. Thx for clarifying it. If you find something, always report. Else we won't get notified ;)

**Comment by guinux** [comment]
Yes, I checked and there's no bug, it works as expected
