### ISSUE TITLE
"Do not ask for confirmation when building packages" still waits for password input

### ISSUE THREAD

**Issue by geckolinux** [manjaro/pamac#69]
Hello,

I think it would look more professional if users didn't have to look at the terminal output while an AUR package is installing. I like the Pamac option of building packages without confirmation, but even with this enabled it still requires the root password. Could you make it ask for the password with `gksudo` or something similar? Users are often confused by the terminal, where nothing is echoed to show it is receiving their password input.

Thanks!

**Comment by guinux** [comment]
Fixed in v4.2.9
