### ISSUE TITLE
Pamac-daemon crashes when trying to search for packages using the GUI

### ISSUE THREAD

**Issue by lots0logs** [manjaro/pamac#71]
This just started happening within the last 24 hours. Can anyone that's using Arch's repos directly confirm it?
```
systemd[1]: Started Pamac.
Sep 29 04:31:05 dUsTiN-XPS pamac-daemon[1986]: (process:1986): GLib-CRITICAL **: g_variant_new_string: assertion 'string != NULL' failed
Sep 29 04:31:05 dUsTiN-XPS kernel: pamac-daemon[1986]: segfault at 20 ip 00007f75fa9b27f0 sp 00007ffe8490b708 error 4 in libglib-2.0.so.0.4400.1[7f75fa92e000+10c000]
Sep 29 04:31:05 dUsTiN-XPS systemd[1]: pamac.service: Main process exited, code=dumped, status=11/SEGV
Sep 29 04:31:05 dUsTiN-XPS systemd[1]: pamac.service: Unit entered failed state.
Sep 29 04:31:05 dUsTiN-XPS systemd[1]: pamac.service: Failed with result 'core-dump'.
Sep 29 04:31:05 dUsTiN-XPS systemd-coredump[2008]: Process 1986 (pamac-daemon) of user 0 dumped core.
```

**Comment by philmmanjaro** [comment]
Hmm. Do you use the **testing** branch of Arch? Maybe a rebuild is needed. On my end with the latest stable packages from today it still works as usual. A newer **glib2** is in the **Staging** repo for Gnome 3.18. Currently I'm using **2.44.1-1** here ...

**Comment by lots0logs** [comment]
@philmmanjaro Hmm..No I'm not using stable. Its very strange. I'll try rebuilding it and let you know how it goes. Cheers!

**Comment by lots0logs** [comment]
@philmmanjaro So it turns out that it only crashes when I try to search the following string: `git`

**Comment by philmmanjaro** [comment]
![pamac-search-for-git](https://cloud.githubusercontent.com/assets/5050022/10226001/9bfacb5c-6865-11e5-899e-991a41ed4649.png)

hmm. works on my end ...

**Comment by lots0logs** [comment]
I'm going to close this, not sure what was causing it but its not doing it anymore :confused:
