### ISSUE TITLE
Pamac doesn't show some AUR package installations in the history

### ISSUE THREAD

**Issue by sb56637** [manjaro/pamac#73]
Hi, I just noticed that the Pamac gear menu -> "View History" doesn't show some packages. It would appear that the missing ones are AUR packages installed through Pamac, although it does show their removal.

As an example, here's the Pamac history before and after I installed and uninstalled Teamviewer from the AUR via Pamac:
https://pastebin.mozilla.org/8848907

And here's the relevant part of my /var/log/pacman.log:
https://pastebin.mozilla.org/8848908

**Comment by philmmanjaro** [comment]
Please look at **/var/log/pacman.log** as those are installed by **yaourt** and not **pamac**. This is not a bug, it's a feature.
