### ISSUE TITLE
[feature request] Add confirmation dialog to remove db.lck

### ISSUE THREAD

**Issue by budimanjojo** [manjaro/pamac#74]
Sometimes the db.lck is not removed when you open up pamac without having another pacman session opens. It will be better if pamac asks the user if they want to delete it and warns the user to make sure there's not another pacman opened in background. More info about it can be read here: https://forum.manjaro.org/index.php?topic=23871

**Comment by philmmanjaro** [comment]
This is a dublicate of https://github.com/manjaro/pamac/issues/5
