### ISSUE TITLE
Add more infos in pamac-updater

### ISSUE THREAD

**Issue by Salamandar** [manjaro/pamac#78]
Hi there !
Coming from LinuxMint, I find the Arch pamac-updater not verbose enough.
It'd be great to have : (for each package)
* the old (installed) and new (update) versions of each packages,
* the repo (core/, community/ aur/, and I forget some)
* a choice box ("i want or not update this package")
* the download / package / net upgrade sizes
* Even some colours if it's a minor (revision), medium (sub-version) or major (version) update would be amazing
Anyways, what do you thing about that ?
Salamandar

**Comment by guinux** [comment]
Implemented in v4.0.0 except colors
