### ISSUE TITLE
Attempting to install MySQL from AUR installs MariaDB instead

### ISSUE THREAD

**Issue by MagnusOxlund** [manjaro/pamac#79]
Attempting to install the Oracle MySQL version from AUR initiates a MariaDB installation. 

The description links to the Oracle website and the AUR web page which does not list MariaDB as a dependency. I can confirm that it is indeed MariaDB that gets installed if you carry out the installation, and the MySQL item on the Pamac search results page is unchecked again after the installation is completed.

![screenshot_2015-10-30_22-09-05](https://cloud.githubusercontent.com/assets/10921083/10858218/a8cc7290-7f53-11e5-9c2e-bbaf7e82e590.png)

**Comment by philmmanjaro** [comment]
That is simply cos **mariadb** provides **mysql**:

```
  conflicts=('mysql')
  provides=("mysql=$pkgver")
```

We have to look into it.

**Comment by guinux** [comment]
Fixed in v4.2.9
