### ISSUE TITLE
Links are always opened in Firefox as opposed to the preferred browser

### ISSUE THREAD

**Issue by MagnusOxlund** [manjaro/pamac#80]
I have set Google Chrome as my preferred browser in the Preferred Applications settings section, but all links on Pamac pages are opened in Firefox.

**Comment by MagnusOxlund** [comment]
Why has the issue been closed? It's still a problem.

**Comment by guinux** [comment]
It's a user configuration problem.
See https://wiki.archlinux.org/index.php/Default_applications

**Comment by MagnusOxlund** [comment]
Can you be more specific? Are you saying that Pamac is checking some other list for default applications that I haven't configured?

**Comment by guinux** [comment]
Not at all. Just be sure to remove all lines with "firefox" in your .config/mimeapps.list file.
