### ISSUE TITLE
[Feature Request] Add support for other AUR helpers

### ISSUE THREAD

**Issue by zoqaeski** [manjaro/pamac#84]
Yaourt has issues with certain packages, and also sources PKGBUILDs which makes it insecure and risks that a malicious PKGBUILD could do damage to the system. I've been using pacaur for a while before I tried using pamac as a nice front-end, and I modified the sources in my own fork to call that instead—it seems to work—so I think it might be possible to add support for both helpers (and others). Pacaur uses the same arguments as pacman, with lowercase ones to only download and install packages from the AUR, and I think most other AUR helpers are similar if they aid in searching, building and installing AUR packages.

[pacaur.patch](https://github.com/manjaro/pamac/files/42534/pacaur.txt)

**Comment by ItachiSan** [comment]
It would be nice to create some switch that allows people to define the preferred AUR helper and not using a fixed value in the sources.It would be nice to create some switch that allows people to define the preferred AUR helper and not using a fixed value in the sources.

**Comment by guinux** [comment]
own build functions in v4.2.9
