### ISSUE TITLE
[feature-request] Pacmac-tray , update log

### ISSUE THREAD

**Issue by ghost** [manjaro/pamac#85]
It would be a nice feature as philm wrote the update stable text, in such structure as he does, make it in an package lijke manjaro-update-log , as example... pamac can pick such script as that up, how it will do, people can click on that  in pamac updater and see what change, so , does not need rss or forum whatever. thats the idea :) how it will be structured i dont know probably that text should be start like  |testing-{textdate} on first row if it get add so pamac tray read it out.., would be some markt up eventually... dont know how it gona be marked... but will see :)

**Comment by eduncan911** [comment]
Couldn't you just:

    $ tail -n 100 /var/log/pacman.log

?

In the GUI, one could just parse this same log as the feature.

(I speak of the above, coming from ArchLinux and Antergos installs)

**Comment by tele1** [comment]
+1 :-)

**Comment by guinux** [comment]
#49
