### ISSUE TITLE
Black window while loading

### ISSUE THREAD

**Issue by dtluna** [manjaro/pamac#89]
After starting pamac-manager its window is black for some seconds.
![pamac black screen](https://cloud.githubusercontent.com/assets/10116666/12529901/95442360-c1db-11e5-91e1-6672405afd20.png)
It is confusing and frustrating. If pamac is busy loading package lists, there should be some sort of indication (i.e. spinner or progress bar).
I am more than willing to fix that myself though, but I would like to know about your coding standards.

**Comment by philmmanjaro** [comment]
Which desktop environment and theme was used?

**Comment by dtluna** [comment]
I am using Xfce 4.12
WM Theme: Radiance-Flat-Aqua
GTK Theme: Radiance-Flat-Aqua

**Comment by philmmanjaro** [comment]
Ok, seems this has to do with the loading of databases. I just checked it with v3.0 of pamac. @guinux: can we add a progressbar or wheel during the loading?

**Comment by dtluna** [comment]
@philmmanjaro @guinux Thank you very much!
