### ISSUE TITLE
Clearing Notifications Opens Pamac

### ISSUE THREAD

**Issue by MrOats** [manjaro/pamac#91]
DE: Cinnamon 2.8.6-1
Pamac Version: 2.4.3-5

Under Cinnamon since the 2.4.3-5 update for pamac: Whenever I clear the notification for pamac update notifier it opens pamac-updater.

**Comment by pointhi** [comment]
This functionality was implemented in  #88

One question: is Cinnamon displaying a closing sign on the notification like gnome does? Otherwise we should probably implement different behaviour for different desktop enviroments.

Basically, clicking on the notification should normaly open the corresponding application (If I have understand you issue correctly)

**Comment by MrOats** [comment]
Cinnamon just has a Clear All Notifications button, clicking on the notification just opens the application associated with the notifications and clears that specific one.

![cinnamonnotifications](https://cloud.githubusercontent.com/assets/13208087/12696773/8ee8cb44-c738-11e5-9e20-8e640987a971.png)

**Comment by pointhi** [comment]
thanks for your report.

Here is the corresponding code:

https://github.com/manjaro/pamac/pull/88/files#diff-a2af56d3dea29ec45577e8a072472b84R189

I found some documentation which could probably solve this issue, and I would look into it soon.

**Comment by MrOats** [comment]
Thank you! Have a great weekend

**Comment by guinux** [comment]
To connect to the closed signal to run the updater is the problem.

**Comment by pointhi** [comment]
@MrOats It should now work as expected. Could you test it please?

**Comment by MrOats** [comment]
Removed my packaged version from Manjaro repo, and did a make install from the master branch. Installed successfully and started the pamac daemon and and tray, restored my config and ran pamac-refresh. **Results were successful!**

Thank you

**Comment by pointhi** [comment]
have you applied my patch from #88?

**Comment by MrOats** [comment]
Oops.. no I did not. I've redownloaded the master and replaced the tray.vala with your version, and continued with the same steps. Ran pamac-refresh, the notification came up and I hit "Clear Notifications" and the issue did not occur (Success Again)!

Interesting that before and after the patch, the issue did not occur.

**Comment by philmmanjaro** [comment]
Each desktop behaves differently. I'm glad that we found a proper solution. @pointhi keep it up ;)
