### ISSUE TITLE
Merge separate "Repository" and "AUR" tabs

### ISSUE THREAD

**Issue by Zorgodon** [manjaro/pamac#93]
This is my first comment on github. The 3.0 update probably did some magic in the background and optimized pamac, but it introduced a very annoying feature: the separate tabs between the AUR and direct repositories. Is there any way you could add the AUR back under the Repositories tab? Maybe @guinux you could look at this please?

**Comment by philmmanjaro** [comment]
No, we want to have it separted. This way we showcase which packages are located in AUR. Also the columns are different in AUR than in the binary repositories. Well, on the other hand it might be possible to join them back. This however is Guillaumes decision.

**Comment by guinux** [comment]
It's a wanted feature to avoid confusion for newbies between repos packages and AUR.
It also permits to display packages lists faster.

**Comment by Zorgodon** [comment]
Is there any way you could program an on-off switch into the latest version to switch the combination of the repos and the AUR on or off, so for new users, as you say, they can be separate to make the difference clear, but more experienced arch and pamac users could switch on the combination to make pamac's search work like it used to before 5.0?

If this is unrealistic, I will duly close the issue :)

**Comment by philmmanjaro** [comment]
Well, we can hide the tab if AUR is disabled so new users won't notice and it would be the old style. however to join it back together is not possible, as we have to recode the engine once again. This way it is now faster in loading and browsing.

**Comment by Zorgodon** [comment]
OK. Closed.

**Comment by tgharib** [comment]
I absolutely hated this change until I realized that if you disable "Search in AUR by default" then it will give significant performance improvements to the search times! Now I'm happy about this change because there were a lot of times where I wanted to search for a package in the regular repos but the AUR would slow down the search.
