### ISSUE TITLE
Keep Update Window/Text/Details open

### ISSUE THREAD

**Issue by eduncan911** [manjaro/pamac#96]
The core issue is when Pamac is done upgrading packages, it closes the Details window.

Please, leave it open! Or, out in an option to allow it to stay open and not close immediately.

Coming from pure Arch, I was religious in issuing:

    # pacman -Syu

And carefully eviewing the output for any notes or tips.

With Pamac though, I have lost this ability to review the package output and have missed several important config file changes.

It's come down to me having to:
- run the updates.
- fake an install of some random AUR package.
- click Details, just for me to scroll up and view the previous output.
- CTRL-C, to cancel the random AUR package install.

**Comment by guinux** [comment]
So guys, do you think it could be better to not auto-close the progress window at the end of an transaction?

**Comment by philmmanjaro** [comment]
Add an option to enable auto-closure but keep it disabled by default so the window will kept open if details got extended.

**Comment by guinux** [comment]
I can also auto-close the window if there is no special output.

**Comment by philmmanjaro** [comment]
Or so. Sounds fine for me.
