### ISSUE TITLE
Cannot access AUR from manjaro unstable

### ISSUE THREAD

**Issue by nam1962** [manjaro/pamac#97]
Hi there,
I suddenly connot access AUR packages from Pamac 3.0.0-4 .
I still get them from yaourt though..
Preferences look ok : 
```
~]$ cat /etc/pamac.conf
### Pamac configuration file
## How often to check for updates, value in hours:
RefreshPeriod = 4
## Allow Pamac to search and install packages from AUR:
EnableAUR
## When removing a package, also remove those dependencies
## that are not required by other packages (recurse option):
RemoveUnrequiredDeps


CheckAURUpdates

#SearchInAURByDefault
```
..is it a bug or do I miss something ?

**Comment by philmmanjaro** [comment]
![pamac3](https://cloud.githubusercontent.com/assets/5050022/12933174/085e0a9c-cf87-11e5-9f0e-b8e894aa7107.png)

... come again. I don't get your question ...

**Comment by nam1962** [comment]
Oooops ! My own shame :  I did'nt notice you harmonized the UI, thus I did'nt noticee the gray tab (as it appeart with Adwaita theme) I just concentrated on the empty panel ! 
Sorry for that and thank you for the Pamac job !

![capture d ecran_2016-02-10_07-54-51](https://cloud.githubusercontent.com/assets/7419235/12940746/95b007e8-cfcc-11e5-8d1e-ad481a67223d.png)

![capture d ecran_2016-02-10_07-56-54](https://cloud.githubusercontent.com/assets/7419235/12940798/fb39658c-cfcc-11e5-9ea9-adbf43f94320.png)

![capture d ecran_2016-02-10_07-57-12](https://cloud.githubusercontent.com/assets/7419235/12940758/a55755f2-cfcc-11e5-99fe-c5f4e35c7f42.png)
