### ISSUE TITLE
Automatically refresh Pamac mirror list on fresh Manjaro installs

### ISSUE THREAD

**Issue by MagnusOxlund** [manjaro/pamac#99]
I recently installed the most recent version of Manjaro XFCE and ended up waiting roughly an hour for a Pamac system update before I realized I wasn't using the fastes mirror available. 

Since I'm probably not the only knucklehead who is going to run into this on their first Manjaro install, I suggest that the mirror list be updated automatically on the first launch of Pamac.

**Comment by guinux** [comment]
@philmmanjaro: would not it be the work of the installer ?

**Comment by philmmanjaro** [comment]
@guinux: we should add that to the package manager on startup when it noticed that the database was not generated yet. Update procedure will do it anyway, but delayed (minimal one hour). However, we can add it also to the installer, but the package manager should be able to handle it also.

**Comment by guinux** [comment]
Integrated to calamares:
http://github.com/calamares/calamares-manjaro/commit/23a776efc17f12c37c810a5186c6a8f6ff973a19
